networkservicemesh/networkservicemesh

README.md

Signed-off-by: Fabian Deutsch <fabiand@fedoraproject.org>

README: Add a link to the slides

---

README.md

Signed-off-by: Frederick Kautz <fkautz@redhat.com>

Adding information on how to get involved

---

README.md

Add Build Status and License headers

---

README.md

Signed-off-by: Ed Warnicke <eaw@cisco.com>

Added IRC channel and video of slides to Readme

---

.travis.yml
pkg/nsm/apis/pod2nsm/doc.go

Note: the first patch will fail because the code does not clear the fmt check.
A follow up patch will fix it :)

Add go fmt check to .travisci

---

README.md

Meeting info updates

---

cmd/nsm/main.go
nsmdp/nsmdp.go

Experimenting with a more go-friendly way of handling signals.

Use a goroutine to block for the signal

---

.gitignore

Ignore Goland files

---

scripts/build.sh

Add travis test for self vendoring

---

README.md

- Link to NSM NW Interface slides
- Link to NSM Distributed CNFs slies
- Link to Use Case Doc

Update README.md with additional resources:

---

RUN.md
conf/networkservice.yaml

makes label consistent, updates imagePullPolicy in networkService yaml

---

README.md

Add new presentations to README.md

---

plugins/crd/crd_queue.go
plugins/crd/plugin_impl_crd.go

While I'm in here, add in per-CRD channels as well.

Fix informer factory usage

---

plugins/crd/plugin_impl_crd.go

Add CRD validation

---

cmd/netmesh/main.go

handles error from EventLoopWithInterrupt, fixes #51

---

plugins/crd/crd_queue.go
plugins/crd/plugin_impl_crd.go

Closes #82
This commit refactors the workqueue code so it can be more effectively shared
by all CRD handlers. It also moves the workqueue definitions themselves into
the crd_queue.go file where they more naturally belong.

Refactor queue handling code

---

scripts/integration-tests

Disable failing test until the timing issue is addressed

---

cmd/netmesh/doc.go
deviceplugin/deviceplugin.go
netmesh/model/netmesh/netmesh.proto
nsmdp/nsmdp.go

Add copyright notices to files without them

---

scripts/cluster-up-minikube.sh

This relates to #138 since we'll have to keep a close eye on the removal of localkube.

Update minikube version to v0.28.0

---

.travis.yml

Ensure shellcheck is checking sample scripts

---

plugins/crd/api.go
plugins/crd/crd_queue.go
plugins/crd/crd_utils.go
plugins/crd/doc.go
plugins/crd/options.go
plugins/crd/options_test.go
plugins/crd/plugin_impl_crd.go
plugins/crd/plugin_impl_crd_test.go
plugins/nsmcommand/deps.go
plugins/nsmcommand/options.go

Rename the CRD plugin package to simply crd

---

cmd/nse/nse.go
cmd/nsm-init/nsm-init.go
conf/sample/nsm-client.yaml
pkg/tools/tools.go
plugins/nsmserver/nsmserver_client.go
plugins/nsmserver/nsmserver_reg.go

PR addresses some TODOs and moves duplicated code into a tools library.

Addressing TODOs #1

---

plugins/nsmserver/nsmserver_client.go

Adding cleanup function for succeeded or failed connection requests.

TODOs #3 adding cleanup call

---

scripts/cluster-up-minikube.sh

Update Minikube version to v0.28.1

---

conf/sample/teardown.sh

Make sure to stop the simple-dataplane in teardown.sh

---

cmd/simple-dataplane/simple-dataplane.go

Alternative solution to bring veth pars Up 

Adding alternative solution for LinkUp fix

---

.gitignore
docs/GETTING-STARTED.md
docs/README.md

Add a getting started guide to show how to stand up a VM from bare metal to a running Network Service Mesh.
Includes installing all prerequisites, packages etc.
Signed-off-by: Thomas F Herbert <therbert@redhat.com>

Add getting started guide.

---

Gopkg.lock
Gopkg.toml

Update cn-infra constraint to v1.4.1

---

.nsm.mk

Do not pass an email address to `docker login`

---

.nsm.mk

Change how we login to docker

---

.nsm.mk

Enable debug of docker push

---

README.md

Add IRC link at the top of README.md

---

README.md

Add a note about our usage of Dependabot

---

docs/QUICK-START.md
docs/README.md
docs/complete-startup-guide.md

In response to comments from reviewers of merged PR #176
rename GETTING-STARTED.md and create new doc specific
to starting NSM.
Signed-off-by: Thomas F Herbert <therbert@redhat.com>

Add Quick Start Document.

---

docs/minikube-cni.md

Closes #96
Add some notes around using CNI plugins with Minikube.

Add a document on using CNI with Minikube

---

build/Dockerfile
build/Dockerfile.nsm-test
cmd/nsm-generate-sriov-configmap/nsm-generate-sriov-configmap.go

Adding header package

---

cmd/nsm-generate-sriov-configmap/nsm-generate-sriov-configmap.go
cmd/nsm-generate-sriov-configmap/nsm-generate-sriov-configmap_test.go

Transfer enhancements added to configmap generator

Add enhancements

---

controllers/sriov-controller/sriov-client.yaml
controllers/sriov-controller/sriov-controller.yaml

sriov controller yaml changes

---

plugins/crd/crd_utils.go

Closes #135
When creating CRDs, attempt the following:
- First, see if the CRD already exists.
- If it does not, try to create.
- If creating fails, return an error.
- If creating succeeds, great, we're done!
- If it exists, try to update the CRD to the latest version.

Make CRD creation more robust

---

pkg/nsm/apis/netmesh/netmesh.proto

Correct comment in netmesh.proto

---

scripts/ci-dind-images.sh

Skip the netmesh-test image and remove some debug

---

.circleci/config.yml
dataplanes/vpp/yaml/vpp-daemonset.yaml
scripts/integration-test-helpers.sh
scripts/integration-tests.sh

This allows us to use bind mounts to share directories between two Pods.

Mark vpp-daemon mount bidirectional

---

dataplanes/vpp/pkg/nsmdataplane/nsmdataplane_server.go
dataplanes/vpp/pkg/nsmvpp/nsm_vpp.go
dataplanes/vpp/pkg/nsmvpp/nsm_vpp_noimpl.go
dataplanes/vpp/pkg/nsmvpp/nsm_vpp_xconnect.go

Abstracting connect mechanism implementation in VPP dataplane

VPP Dataplane: Abstracting mechanism

---

controlplane/scripts/build-and-run.sh

This PR fixes build-and-run script for nsmd containers.

Fix build and run script for nsmd

---

dataplanes/vpp/pkg/nsmdataplane/nsmdataplane_server.go
dataplanes/vpp/pkg/nsmvpp/nsm_vpp.go
dataplanes/vpp/pkg/nsmvpp/nsm_vpp_kernel.go
dataplanes/vpp/pkg/nsmvpp/nsm_vpp_noimpl.go
dataplanes/vpp/pkg/nsmvpp/nsm_vpp_xconnect.go

tested with nsmd, ready for @lobkovilya to add memif stuff... There is more work required here, especially recovery from errors in the middle of cross-connect set up, like if we have one interface up, and second failed.

Any-any (extensible) cross-connects in vpp dataplane

---

.circleci/config.yml
dataplanes/vpp/Makefile
dataplanes/vpp/build/Dockerfile.memif-test

This change takes the final memif-test container
from 1G -> 182Mb
It also builds it as part of the CI

Lean down the memif-test container and add to CI

---

controlplane/cmd/nsc/nsc.go
controlplane/pkg/nsmd/clients.go
controlplane/pkg/nsmd/nsmd.go
controlplane/pkg/nsmdapi/nsmd.pb.go
controlplane/pkg/nsmdapi/nsmd.proto
k8s/build/Dockerfile.nsmdp
k8s/cmd/nsmdp.go
k8s/cmd/nsmdp/nsmdp.go
k8s/conf/nsc.yaml
k8s/conf/nse.yaml
k8s/conf/nsmd.yaml
k8s/scripts/build.sh

nsmdp seems to be working. All components deployed into k8s does not -- it looks like we have problems in vpp-daemon (vpp-daemon communicate with vpp and nsm in some messy way and very likely that code was not tested well).

Initial nsmdp implementation

---

dataplanes/vpp/pkg/nsmvpp/transactions.go

Fix index in for-loop

---

scripts/vagrant/README.md
scripts/vagrant/skydive.yaml

Add notes about skydive deployment

---

dataplanes/vpp/pkg/nsmvpp/nsm_vpp_kernel.go
dataplanes/vpp/pkg/nsmvpp/nsm_vpp_local.go
dataplanes/vpp/pkg/nsmvpp/nsm_vpp_memif.go

Successfully tested case memif -- vpp -- memif

Implement memif to other mechanism connection using VPP

---

controlplane/Makefile
controlplane/build/Dockerfile.nsc-debug
controlplane/build/Dockerfile.nsmd-debug
controlplane/docs/Debug.md
docs/Debug.md

Allow to debug controlplane components.

Allow controlplane components debug enabled.

---

controlplane/pkg/model/mode_test.go
controlplane/pkg/model/model.go

Allow delete dataplane operation

---

.k8s.mk
.vagrant.mk
examples/cmd/icmp-responder-nse/nse.go
k8s/cmd/nsmd-k8s/main.go

Introduce resource cleanup to NSE and NSM-K8s.
Not tested in HA/multi-service environment.

NSM cleanup

---

controlplane/cmd/nsmd/nsmd.go
controlplane/pkg/model/mode_test.go
controlplane/pkg/monitor_crossconnect_server/monitor_crossconnect_server.go
controlplane/pkg/nsmd/nsmd.go
controlplane/pkg/nsmd/nsmd_crossconnect_client.go
controlplane/pkg/nsmd/nsmd_crossconnect_client_test.go

Resolving StartNSMCrossConnectServer from #490

---

.k8s.mk

Fix makefile in order to build vppagent based NSC and NSE

---

controlplane/pkg/apis/nsmdapi/nsmd.pb.go
controlplane/pkg/apis/nsmdapi/nsmd.proto
controlplane/pkg/nsmd/nsmd.go
k8s/cmd/nsmdp/nsmdp.go

Dynamically expand nsmdp pool of DeviceIds #496, Refactor nsmdp to have DeviceId match nsmd's id for ClientConnections #495, Refactor nsmdapi to better match device plugin api #494

nsmdp refactorings no.2

---

examples/cmd/nsc/nsc.go
examples/cmd/nsc/utils/nsc_utils.go
examples/cmd/nsc/utils/nsc_utils_test.go
k8s/conf/nsc.yaml

Issue #554: Generalize the nsc to be used as an init container.

---

controlplane/pkg/tests/nsmd_local_test.go
controlplane/pkg/tests/nsmd_remote_test.go

Fix unit tests caused by changes in requesting workspaces

Fix integration tests

---

dataplane/vppagent/pkg/converter/memif_interface_converter.go
dataplane/vppagent/pkg/converter/memif_interface_converter_test.go

Fix memif converter

---

.circleci/config.yml
.k8s.mk
dataplane/vppagent/pkg/vppagent/vppagent.go
examples/cmd/vppagent-nsc/vppagent.go
k8s/conf/vppagent-nsc.yaml
scripts/integration-tests.sh
scripts/nsc_ping_all.sh

Also disable direct memif connection while bind mounts are not propagated from host to vppagent based container

Add vppagent-nsc to integration test

---

.docker.mk
.k8s.mk
conf/skydive.yml
docker/Dockerfile.skydive
k8s/conf/skydive.yaml

Deploy skydive with makefiles

---

.k8s.mk
controlplane/pkg/nsmd/network_service_server.go
controlplane/pkg/nsmd/serviceregistry.go
scripts/integration-tests.sh
scripts/nsc_ping_all.sh

Also fixed two panic inducing bugs I found in the process.

Add vpn-gateway into makefile machinery

---

.k8s.mk
controlplane/pkg/model/model.go
controlplane/pkg/nsmd/serviceregistry.go
controlplane/pkg/remote/network_service_server/remote_network_service_server.go
controlplane/pkg/serviceregistry/serviceregistry.go
controlplane/pkg/tests/nsmd_test_utils.go
controlplane/pkg/vni/vni.go
scripts/integration-tests.sh

Solved the problem of VNI collision across two nodes by
comparing local and remote ips, and having one side have
even vni and the other odd.

Fix bug in VNI allocation

---

.skydive.mk

Add skydive port-forward makefile rule

---

k8s/conf/skydive.yaml

Get rid of useless skydive configMap and ovs part

---

controlplane/pkg/vni/vni.go
dataplane/vppagent/pkg/vppagent/vppagent.go
scripts/nsc_ping_all.sh

vppagent-nsc tests were not failing even if failing.
Fixed that, and discovered VNI allocation had a silly one
char mistake.

Fix vppagent-nsc test to fail if failing.  Fix VNI Selection.

---

k8s/conf/skydive.yaml

Update Skydive highlight

---

k8s/conf/skydive.yaml
k8s/conf/vpn-gateway-nsc.yaml
k8s/conf/vpn-gateway-nse.yaml
k8s/conf/vppagent-firewall-nse.yaml

Add skydive filter for secure-intranet-connectivity components only

---

dataplane/vppagent/build/Dockerfile.vppagent-dataplane
docker/Dockerfile.vppagent-firewall-nse
docker/Dockerfile.vppagent-icmp-responder-nse
docker/Dockerfile.vppagent-nsc

Update vppagent to just released 1.8

Update vppagent to just released 1.8

---

.dockerignore

Improve docker build by copying only the relevant folders.

---

controlplane/pkg/monitor_crossconnect_server/inode_set.go
controlplane/pkg/monitor_crossconnect_server/monitor_crossconnect_server.go
controlplane/pkg/monitor_crossconnect_server/monitor_netnsinode_server.go
dataplane/vppagent/pkg/converter/acl_converter.go
dataplane/vppagent/pkg/converter/converter.go
dataplane/vppagent/pkg/converter/cross_connect_converter.go
dataplane/vppagent/pkg/converter/kernel_connection_converter.go
dataplane/vppagent/pkg/converter/memif_interface_converter.go
dataplane/vppagent/pkg/converter/memif_interface_converter_test.go
dataplane/vppagent/pkg/converter/remote_connection_converter.go
dataplane/vppagent/pkg/vppagent/server.go
dataplane/vppagent/pkg/vppagent/vppagent.go
examples/cmd/vppagent-firewall-nse/vppagent.go
examples/cmd/vppagent-icmp-responder-nse/vppagent.go
examples/cmd/vppagent-nsc/vppagent.go
scripts/integration-tests.sh
utils/fs/fsutils.go

Implement monitor for netns inodes

---

docs/QUICK-START.md

Update the quick start instructions as per #616

---

docs/BUILD.md

Should be the same as the content on the site.

docs: BUILD.md cleanups and sync

---

k8s/pkg/registryserver/nse.go

Partial fix for #626. 
Without this fix, if we register 1000 variants of same NSE, Find will take about 3-4minutes.

Partial fix for #626

---

controlplane/pkg/selector/match_selector_test.go
controlplane/pkg/selector/round_robin_selector_test.go

Adds testing for RoundRobin and Match selectors.

Selector tests

---

examples/cmd/nsc/nsc.go

NSC request timeout

---

scripts/vagrant/Vagrantfile

Add IDs to have vagrant sync all folders normally

Add IDs to have vagrant sync all folders normally

---

test/integration/nsc_deploy_test.go
test/kube_testing/k8s.go

Have timeouts for integration test pod deployments

Have timeouts for integration test pod deployments

---

sdk/client/client.go
sdk/endpoint/endpoint.go

* Port #653
* Fix endpoint tracing

Fixes after SDK merged

---

test/integration/death_handling_test.go

Issue #659: Add tests for nsc/nse dies handling

---

.circleci/config.yml
.gitignore

Trying to use gotestsum and collect individual test into CircleCI interface
https://circleci.com/blog/level-up-go-test-with-gotestsum/

Capture unit test a better way

---

docs/QUICK-START.md

Correcting "setuo" by "setup"
Signed-off-by: William Caban <william.caban@redhat.com>

Simple spelling correction

---

controlplane/pkg/monitor/tests/monitor_server_test.go

Fix Monitor server test stability

Fix Monitor server test stability

---

test/integration/nsmd_test_utils/test_utils.go

Fix TestSingleCrossConnectMonitorBeforeXcons concurrency

Fix TestSingleCrossConnectMonitorBeforeXcons concurrency

---

.k8s.mk

Add jaeger-build target for k8s-build to work

---

.k8s.mk
docker/Dockerfile.admission-webhook
go.mod
go.sum
k8s/cmd/admission-webhook/main.go
k8s/conf/admission-webhook-cfg.yaml
k8s/conf/admission-webhook.yaml
pkg/tools/tools.go
scripts/webhook-create-cert.sh
scripts/webhook-patch-ca-bundle.sh

Admission Webhook implementation according to spec #708 
See #708

Admission Webhook

---

.circleci/config.yml

Fix docker-push-latest

---

docs/spec/TEMPLATE.md

The intention is to have a dedicated spec file that can be used to describe a new feature. 
It consolidates the content from the spec doc file used during the implementation and may include some content like example usages and configurations, references to PRs and related issues.
When needed, the user will copy and fill the `TEMPLATE.md` based on the given context.
Added an additional folder in `./docs/` called `spec` and a template file called `TEMPLATE.md`

Create a spec template in docs/spec

---

.circleci/config.yml

Fix docker push of latest

---

.circleci/config.yml

Update testing infrastructure a bit.

Reduce test time to be less.

---

controlplane/cmd/nsmd/nsmd.go
k8s/cmd/nsmd-k8s/main.go
k8s/cmd/nsmdp/nsmdp.go

Follow up of #686 containing rebase

Fix the nsmd containers handling of signals so they terminate fast.

---

.github/stale.yml

Adding .github/stale.yml

---

k8s/conf/vpn-gateway-nsc.yaml

vpn-gateway-nsc use admission webhook to inject nsc initContainer

vpn-gateway-nsc use admission webhook

---

CHANGELOG.md

Created an initial version of a `CHANGELOG.md` file.
Currently, the content is pretty much filled using the [NSM Release 0.1.0 Project on Github](https://github.com/networkservicemesh/networkservicemesh/projects/7).
* Considering the ongoing release effort, thought that it makes sense to have a `CHANGELOG.md` file. 
* By spending some time looking at how other projects manage that process, got inspired by [Vagrant's](https://github.com/hashicorp/vagrant/blob/master/CHANGELOG.md) solution for tracking their releases. And thus decided to use it more or less as a starting point for our initial version. 
Basically, the format is mostly self-explanatory:
* Three different sub-chapters - FEATURES, IMPROVEMENTS and BUG-FIXES
* Each entry in …

Initial CHANGELOG.md file

---

.circleci/config.yml

A temporary solution for golang/lint issue which causes build failures
All recent builds fail because of golang/lint [issue](https://github.com/golang/lint/issues/436) 
Please see #789

Temporary pin golang/lint version

---

scripts/vagrant/Vagrantfile
scripts/vagrant/scripts/coredump.sh

Configure Vagrant VMs to always collect core files.

---

.circleci/config.yml

Env CONTAINER_TAG wasn't set on circle-ci, so integration tests used images with tag 'latest'

Fix CI, add export CONTAINER_TAG

---

.circleci/config.yml
build/Dockerfile.nsmd-k8s
controlplane/build/Dockerfile.nsmd
dataplane/vppagent/build/Dockerfile.vppagent-dataplane
docker/Dockerfile.admission-webhook
docker/Dockerfile.crossconnect-monitor
docker/Dockerfile.vppagent-firewall-nse
docker/Dockerfile.vppagent-icmp-responder-nse
docker/Dockerfile.vppagent-nsc
examples/build/Dockerfile.icmp-responder-nse
examples/build/Dockerfile.nsc
k8s/build/Dockerfile.nsmdp

Go mod download fails sometimes.  Add retries to CI and Dockerfiles to make it robust.

---

.circleci/config.yml

Increase resource class of sanity check to avoid out of memory failures.

---

dataplane/vppagent/build/Dockerfile.vppagent-dataplane
docker/Dockerfile.vppagent-firewall-nse
docker/Dockerfile.vppagent-icmp-responder-nse
docker/Dockerfile.vppagent-nsc

Switch to using the new vppagent:v1.8.1

---

docs/spec/release.md

Transform the Release spec to md

---

k8s/cmd/nsmd-k8s/main.go
test/integration/basic_monitor_crossconnect_test.go
test/integration/basic_nsc_deploy_test.go
test/integration/basic_nsmd_deploy_test.go
test/integration/basic_nsmd_k8s_test.go
test/integration/nsmd_test_utils/test_utils.go
test/integration/recover_death_handling_test.go
test/integration/recover_nse_dataplane_heal_test.go
test/integration/recover_nse_heal_test.go
test/integration/usecase_nsc_icmp_configuration_test.go
test/integration/usecase_vpn_test.go
test/kube_testing/crds/networkservice.go
test/kube_testing/k8s.go

Fixed most of the typos and applied a consistent naming pattern, so the testing code looks better.

Refactor and fix style guide formatting in tests

---

README.md
docs/guide-build.md
docs/guide-quickstart.md

Add how to trigger integration tests in the Quickstart docs

---

k8s/cmd/nsmdp/nsmdp.go

Fixed NSMDp if more of 10 devices are required.
Fixed NSMDp if more of 10 devices are required.

#801 Fixes NSMDp

---

controlplane/pkg/nsmd/client.go
controlplane/pkg/nsmd/dataplanes.go
controlplane/pkg/nsmd/serviceregistry.go
controlplane/pkg/nsmd/workspace.go
controlplane/pkg/tests/nsmd_test_utils.go
dataplane/impl/dataplaneregistrarclient/dataplaneregistrarclient.go
dataplane/vppagent/cmd/vppagent-dataplane.go
k8s/cmd/nsmdp/nsmdp.go
pkg/tools/tools.go
sdk/common/connection.go
test/integration/dataplane_standalone_test.go
test/integration/nsmd_test_utils/test_utils.go

Write integration tests for data-plane
See #752

DataPlane Integration Tests (#752)

---

.circleci/config.yml
.mk/docker.mk
.mk/k8s.mk
.mk/packet.mk
dataplane/vppagent/build/Dockerfile.vppagent-dataplane-dev
dataplane/vppagent/conf/supervisord/supervisord-dev.conf
dataplane/vppagent/scripts/prepare_postmortem.sh
dataplane/vppagent/scripts/vpp_listener.py
docker/Dockerfile.vppagent-dataplane-dev
scripts/terraform/download-postmortem-data.sh
test/kube_testing/pods/vppagent_dataplane.go

Collect vpp postmortem data. 
See #738

Collect vpp postmortem data (simplified)  #738

---

test/integration/basic_dataplane_standalone_test.go

Improve dataplane tests.
1. Improve standalone dataplane tests stability
2. Print pod logs on failure 
See #850
Sometimes standalone dataplane tests fail because 
1. client connecting to dataplane while it is still being initialized
2. some nodes from a previous failed runs are not destroyed

Improve dataplane tests (#850)

---

controlplane/pkg/nsm/nsm.go
controlplane/pkg/nsmd/nsmd.go
controlplane/pkg/tests/nsmd_local_test.go
controlplane/pkg/tests/nsmd_test_utils.go
sdk/client/client.go

Improve handling of context timeouts
Right now client had 5second connection timeout, and dataplane could not work with it properly.
Have more stable connection establish.

Improve handling of context timeouts.

---

scripts/terraform/start-master.sh
scripts/vagrant/scripts/configureK8smaster.sh

Issue https://github.com/networkservicemesh/networkservicemesh/issues/859

Update version of etcd to 3.3.12

---

k8s/pkg/registryserver/nsm.go
k8s/pkg/registryserver/registry_cache.go
test/integration/basic_nsmd_k8s_test.go

Possible fix of TestUpdateNSM

---

dataplane/vppagent/pkg/memif/memif_direct_connection.go

`DirectMemifConnector` performs unprotected concurrent read/write operations on map, which may cause `panic` when handling multiple simultaneous memif-requests to dataplane.  
Fix concurrency issue in dataplane `DirectMemifConnector`

Fix memif concurrency issue

---

test/integration/basic_dataplane_standalone_test.go
test/integration/basic_monitor_crossconnect_test.go
test/integration/basic_nsc_deploy_test.go
test/integration/basic_nsmd_deploy_test.go
test/integration/basic_nsmd_k8s_test.go
test/integration/basic_nsmdp_test.go
test/integration/recover_death_handling_test.go
test/integration/recover_nse_dataplane_heal_test.go
test/integration/recover_nse_heal_test.go
test/integration/recover_nse_nsm_heal_test.go
test/integration/usecase_nsc_icmp_configuration_test.go
test/integration/usecase_vpn_test.go
test/kube_testing/k8s.go

Use all default prepares in integration tests

Make all tests close all pods before launch

---

scripts/terraform/start-master.sh
scripts/vagrant/scripts/configureK8smaster.sh

Error during `packet-deploy`:
```
your configuration file uses a deprecated API spec: "kubeadm.k8s.io/v1alpha3"
```

Revert etcd version

---

.gitignore

Remove cluster-config.yaml from .gitignore

---

controlplane/pkg/nsm/nsm.go
controlplane/pkg/nsmd/constants.go
controlplane/pkg/nsmd/nsmd.go
controlplane/pkg/prefix_pool/prefixpool.go
controlplane/pkg/prefix_pool/prefixpool_test.go
controlplane/pkg/tests/nsmd_local_test.go
controlplane/pkg/tests/nsmd_test_utils.go
test/integration/basic_excluded_prefixes_test.go

Issue https://github.com/networkservicemesh/networkservicemesh/issues/842

Add nsmd check for violation of excluded_prefixes

---

controlplane/cmd/nsmd/nsmd.go
controlplane/pkg/monitor/remote_connection_monitor/remote_connection_monitor_server.go
controlplane/pkg/nseregistry/nse_registry.go
controlplane/pkg/nsm/nsm_heal.go
controlplane/pkg/nsmd/dataplanes.go
controlplane/pkg/nsmd/nsmd_crossconnect_client.go
controlplane/pkg/nsmd/probes.go
controlplane/pkg/nsmd/registry.go
controlplane/pkg/nsmd/workspace.go
controlplane/pkg/services/client_connection_manager.go
controlplane/pkg/tests/mode_test.go
controlplane/pkg/tests/nse_registry_test.go
controlplane/pkg/tests/nsmd_registry_test.go
controlplane/pkg/tests/test-listener.go
dataplane/README.md
dataplane/vppagent/cmd/vppagent-dataplane.go
dataplane/vppagent/pkg/converter/kernel_connection_converter.go
pkg/tools/tools.go
sdk/client/client.go
test/integration/recover_death_handling_test.go
test/integration/usecase_nsc_icmp_configuration_test.go
test/kube_testing/k8s.go
test/kube_testing/pods/vppagent_dataplane.go

Bump cleanup signal handling before anything else

---

.env/vagrant.env
.mk/vpp_agent.mk
controlplane/pkg/nsmd/serviceregistry.go
controlplane/pkg/tests/nsmd_test_utils.go
dataplane/vppagent/build/Dockerfile.vppagent-dataplane-dev
dataplane/vppagent/pkg/converter/acl_converter.go
dataplane/vppagent/pkg/converter/converter.go
dataplane/vppagent/pkg/converter/cross_connect_converter.go
dataplane/vppagent/pkg/converter/kernel_connection_converter.go
dataplane/vppagent/pkg/converter/memif_interface_converter.go
dataplane/vppagent/pkg/converter/memif_interface_converter_test.go
dataplane/vppagent/pkg/converter/remote_connection_converter.go
dataplane/vppagent/pkg/vppagent/vppagent.go
deployments/gcb/cloudbuild.yaml
examples/cmd/vppagent-firewall-nse/interface.go
examples/cmd/vppagent-firewall-nse/vppagent.go
examples/cmd/vppagent-icmp-responder-nse/vppagent.go
examples/cmd/vppagent-nsc/vppagent.go
go.mod
go.sum
pkg/tools/tools.go
test/integration/basic_dataplane_standalone_test.go
test/integration/recover_nse_nsm_heal_test.go
test/kube_testing/pods/utils.go

Use latest VPP agent
Switch to latest VPP agent

Use latest VPP agent

---

examples/cmd/vppagent-icmp-responder-nse/composite.go
examples/cmd/vppagent-icmp-responder-nse/nse.go
test/integration/basic_memif_test.go
test/kube_testing/pods/vppagent_icmp_responder.go
test/kube_testing/pods/vppagent_nsc.go

Turns out that we don't have any test to cover memif functional
Add simple memif test, fix vppagent-icmp-responder-nse

Integration tests for memif

---

controlplane/pkg/nsm/endpoint_client.go
controlplane/pkg/nsm/remote_nsm_client.go

Issue https://github.com/networkservicemesh/networkservicemesh/issues/901

Fix fatal error: concurrent map iteration and map write

---

.circleci/cleanup-packet.sh
.circleci/config.yml

Prepare build for muti-cloud support. Integration test parameters:
- `cloud_provider` - one of supported cloud providers (e.g.: `packet`, `gke`, `azure`, `aws`)
- `cluster_id` - an id of kubernetes cluster unique for the given cloud provider (e.g.: `1`, `2`, `3`, etc.)
Adapt existing integration-testing job to support multiple cloud providers.

Prepare build for muti-cloud support

---

controlplane/pkg/apis/nsm/nsm.go
controlplane/pkg/apis/nsm/nsm_properties.go
controlplane/pkg/nsm/nsm.go
controlplane/pkg/nsm/nsm_heal.go
controlplane/pkg/nsmd/serviceregistry.go

Fixes recovery of remote NSMD die, fist check NSE we found during healing wait cycle.
Fixed issue #853

Fix Recovery in case of remote NSM die

---

test/integration/basic_memif_test.go

Add missing custom tag for TestSimpleMemifConnection

---

.circleci/config.yml
controlplane/pkg/nsm/nsm.go
controlplane/pkg/tests/nsmd_remote_test.go
dataplane/pkg/common/egress_interface.go
dataplane/pkg/common/egress_interface_test.go
dataplane/vppagent/pkg/converter/acl_converter.go
dataplane/vppagent/pkg/converter/kernel_connection_converter.go
dataplane/vppagent/pkg/converter/memif_interface_converter.go
dataplane/vppagent/pkg/converter/remote_connection_converter.go
dataplane/vppagent/pkg/vppagent/vppagent.go
examples/cmd/vppagent-firewall-nse/vppagent.go
examples/cmd/vppagent-icmp-responder-nse/vppagent.go
examples/cmd/vppagent-nsc/vppagent.go
pkg/tools/tools.go
scripts/aws/create-kubernetes-cluster.go
scripts/aws/cubernetes-cluster.go
scripts/aws/destroy-kubernetes-cluster.go
test/kube_testing/pods/nsmd.go
test/kube_testing/pods/vppagent_dataplane.go

Format cleanup

---

docs/spec/glossary.md

Adding the NSM Glossary as specified by the Documentation Call.

spec: add the glossary

---

OWNERS.md

Add an OWNERS.md file.

---

.circleci/config.yml
.circleci/gke/cleanup-gke.sh
.circleci/gke/init-gke.sh
.mk/gcb.mk
.mk/gke.mk
.mk/k8s.mk
dataplane/vppagent/pkg/vppagent/vppagent.go
deployments/gcb/cloudbuild.yaml
scripts/gke/install-gcloud-sdk.sh
scripts/install-kubectl.sh
scripts/prepare-circle-integration-tests.sh
test/integration/basic_nsmd_k8s_test.go
test/integration/nsmd_test_utils/test_utils.go
test/integration/recover_nse_dataplane_heal_test.go
test/integration/recover_nse_heal_test.go
test/integration/recover_nse_nsm_heal_test.go

GKE enabled building & testing.
GKE enabled building & testing.

Initial GKE enabled build

---

.circleci/config.yml

Add license scan from fossa to CI

---

test/integration/basic_memif_test.go
test/integration/basic_monitor_crossconnect_test.go
test/integration/nsmd_test_utils/test_utils.go
test/integration/recover_death_handling_test.go
test/integration/recover_nse_dataplane_heal_test.go
test/integration/recover_nse_heal_test.go
test/integration/recover_nse_nsm_heal_test.go
test/integration/usecase_nsc_icmp_configuration_test.go
test/integration/usecase_vpn_test.go

Expand 'recover' tests

---

README.md

- add presentations for KubeCon EU and KubeCon China 
- https://sched.co/NxZ5
- https://sched.co/NxZi
- https://sched.co/OB2V
- share upcoming NSM events

add upcoming events to README

---

controlplane/pkg/model/model.go
controlplane/pkg/nsm/nsm.go
controlplane/pkg/nsmd/serviceregistry.go
controlplane/pkg/tests/mode_test.go
controlplane/pkg/tests/select_dataplane_test.go

Adding ability to select dataplane with proper parameters
Provide a selector function as an argument of SelectDataplane. Selector accepts dataplane as argument and it should return true if dataplane fulfill the confitions.
SelectDataplane method returns first dataplane from available.

Select Dataplane by parameters (#897)

---

README.md

Add the slack communication channel and the CII Best practices badeg.
We have moved to Slack.
Adding the CII Best practices badge as per #938.

README.md: Replace IRC with Slack and add CII badge

---

examples/cmd/vppagent-firewall-nse/interface.go
examples/cmd/vppagent-icmp-responder-nse/composite.go
k8s/cmd/admission-webhook/main.go
sdk/README.md
sdk/client/clientlist.go
sdk/client/const.go
sdk/common/configuration.go
sdk/endpoint/client.go
sdk/endpoint/composite.go
sdk/endpoint/connection.go
sdk/endpoint/ipam.go
sdk/endpoint/monitor.go

Update the SDK docs and small refactoring.
The docs were misaligned with the latest changes.

Update sdk doc

---

docker/Dockerfile.vppagent-firewall-nse
docker/Dockerfile.vppagent-icmp-responder-nse
docker/Dockerfile.vppagent-nsc

vpp-agent has been upgraded and changes provided by #900 are now provided upstream in vpp-agent 2.0.1 (https://github.com/ligato/vpp-agent/pull/1260)

Revert PR #900 now that vpp-agent has been upgraded

---

.circleci/config.yml

Disable FOSSA

---

.circleci/config.yml

Rearrange the CircleCI config to have a better structure. Also, fix the Packet leftover resources once we have failing tests.
Clean up CircleCI config.yml.
We have stale Packet resources. Cleanup the config and fix the packet destroy process.

Refactor circleci

---

.circleci/config.yml
.mk/k8s.mk
scripts/nsc_ipconfig_all.sh
scripts/nsc_ping_all.sh
scripts/verify_vpn_gateway.sh

Fix make check for ns

---

.mk/integration.mk

Fix taking into account the namespace in make target

---

.mk/jaeger.mk
.mk/skydive.mk

makefile: fix Skydive and Jaeger with namespaces

---

test/integration/nsmd_test_utils/test_utils.go
test/integration/recover_remote_nse_nsm_heal_test.go

Will be fixed and enabled in PR https://github.com/networkservicemesh/networkservicemesh/pull/989

Skip TestNSMHealRemoteDieNSMD_NSE

---

docs/guide-kind.md

Fix some typos in the kind guide

Fix nits in guide-kind.md

---

.circleci/config.yml

Disable Azure until we sort out the quota issue on deployments.

---

.mk/aws.mk
.mk/docker.mk
scripts/aws/create-kubernetes-cluster.go
scripts/aws/kube-config-template
scripts/aws/scp-config-template

AWS as CONTAINER_BUILD_PREFIX support
Copying nsm to eks node
Build nsm on eks node
Load nsm docker images to another nodes

AWS as CONTAINER_BUILD_PREFIX support

---

controlplane/pkg/apis/nsm/nsm.go
controlplane/pkg/apis/nsm/nsm_properties.go
controlplane/pkg/model/model.go
controlplane/pkg/nsm/nsm.go
controlplane/pkg/nsm/nsm_heal.go
controlplane/pkg/nsm/nsm_mechanims.go
controlplane/pkg/nsmd/nsmd_crossconnect_client.go
controlplane/pkg/services/client_connection_manager.go
controlplane/pkg/tests/heal_nse_test.go
controlplane/pkg/tests/mode_test.go
controlplane/pkg/tests/nsmd_test_utils.go
controlplane/pkg/tests/select_dataplane_test.go
controlplane/pkg/vni/vni.go
k8s/pkg/registryserver/discovery.go
pkg/tools/tools.go
test/integration/basic_excluded_prefixes_test.go
test/integration/basic_memif_test.go
test/integration/basic_nsmdp_test.go
test/integration/nsmd_test_utils/test_utils.go
test/integration/recover_death_handling_test.go
test/integration/recover_remote_nse_nsm_heal_test.go
test/integration/usecase_nsc_icmp_configuration_test.go
test/kube_testing/k8s.go
test/kube_testing/pods/nsmd.go

Fix NSM Remote healing handling.
Fixes NSM Remote healing, also adds different handling of remote NSE and remote NSM die sitiations.

Fix remote healing tests

---

test/integration/nsmd_test_utils/test_utils.go

Add incorrectly removed line by #974 merge.
https://github.com/networkservicemesh/networkservicemesh/pull/974/files#diff-a0c13d91a5f0ba48661e93302e84e934L59

Add incorrectly removed line

---

.circleci/config.yml
.mk/azure.mk
scripts/azure/create-aks-cluster.sh

Deploy was broken because of attempt to deploy aks-monitoring. I believe that we can disable it for CI.
From documentation: *Azure Monitor for containers is a feature designed to monitor the performance of container workloads deployed to either Azure Container Instances or managed Kubernetes clusters hosted on Azure Kubernetes Service (AKS). Monitoring your containers is critical, especially when you're running a production cluster, at scale, with multiple applications.*

Enabling azure

---

controlplane/pkg/nsm/nsm_prefix_collector.go
controlplane/pkg/tests/nsmd_local_test.go
controlplane/pkg/tests/nsmd_test_utils.go

Stabilization of TestExcludePrefixesMonitor

---

test/integration/basic_monitor_crossconnect_metrics_test.go

Disable TestSimpleMetrics test for now
Disable TestSimpleMetrics test for now

Disable TestSimpleMetrics for now.

---

.circleci/config.yml
test/integration/basic_excluded_prefixes_test.go
test/integration/basic_memif_test.go
test/integration/basic_monitor_crossconnect_metrics_test.go
test/integration/nsmd_test_utils/test_utils.go
test/integration/recover_death_handling_test.go

[WIP] Stabilization of TestSimpleMemifConnection on GKE

---

.gcloudignore

Fix breakage in gcb build due to missing entry in .gcloudignore

---

controlplane/pkg/apis/nsm/nsm.go
controlplane/pkg/nsm/healer.go
controlplane/pkg/nsm/nse_manager.go
controlplane/pkg/nsm/nsm.go
controlplane/pkg/nsm/nsm_heal.go
controlplane/pkg/nsm/nsm_heal_processor.go
controlplane/pkg/nsm/utils.go
controlplane/pkg/services/client_connection_manager.go

Extract NSM healing logic to the separate class.
**networkServiceManager** is a very complicated class. It holds a lot of logic so it is almost impossible to cover it with unit tests.
This refactoring has been done to make unit testing of connection healing feature possible.

Refactor NSM

---

test/kube_testing/k8s.go

Cleans up k8s services, deployments, mutating webhook configurations, secrets on test startup.
Issue #1024

Cleanup more resources on test startup

---

controlplane/pkg/apis/connectioncontext/helpers.go
controlplane/pkg/apis/local/connection/helpers.go
controlplane/pkg/apis/remote/connection/helpers.go
controlplane/pkg/tests/connection_context_test.go
dataplane/vppagent/pkg/vppagent/vppagent.go

https://github.com/networkservicemesh/networkservicemesh/issues/811

Check for IPNeighbor without HW address in vppagent-dataplane and return error

---

k8s/pkg/registryserver/resource_cache/ns_cache.go
k8s/pkg/registryserver/resource_cache/nse_cache.go
k8s/pkg/registryserver/resource_cache/nsm_cache.go
k8s/pkg/tests/nsm_cache_test.go

Inappropriate work with pointers in `cache.replace` method 
Sometimes leads to fail of heal test (was noticed on azure)

Fix bug with incorrect cache.replace method

---

controlplane/pkg/metrics/metrics_collector.go
dataplane/vppagent/pkg/vppagent/vppagent.go
test/integration/basic_monitor_crossconnect_metrics_test.go
test/integration/nsmd_test_utils/test_utils.go

#1029
**Ready for reivew/merge**

Stabilization of TestSimpleMetrics on CI

---

deployments/helm/icmp-responder/templates/icmp-responder-nse.tpl
deployments/helm/icmp-responder/templates/nsc.tpl
deployments/helm/nsm-monitoring/templates/crossconnect-monitor.tpl
deployments/helm/nsm-monitoring/templates/skydive.tpl
deployments/helm/nsm/charts/admission-webhook/templates/admission-webhook-secret.tpl
deployments/helm/nsm/templates/cluster-role-binding.tpl
deployments/helm/nsm/templates/nsmgr.tpl
deployments/helm/nsm/templates/vppagent-dataplane.tpl
deployments/helm/vpn/templates/vpn-gateway-nsc.tpl
deployments/helm/vpn/templates/vpn-gateway-nse.tpl
deployments/helm/vpn/templates/vppagent-firewall-nse.tpl
deployments/helm/vpp-icmp-responder/templates/vppagent-icmp-responder-nse.tpl

Fix helm to use namespaces.

---

README.md

Update README with the new logo

---

.circleci/config.yml

Increase aws-deploy no_output_timeout to 20m

---

.circleci/config.yml

Extend timeout for AWS destroy.

---

test/integration/basic_nsmd_k8s_test.go
test/kube_testing/k8s.go

Implement method `DescribePod` that prints events related to Pod
Not enough information in logs to fix https://github.com/networkservicemesh/networkservicemesh/issues/1020

Describe pod

---

.circleci/config.yml
.mk/k8s.mk

Fix `icmp` example and add example checks to CI.
Fix #1072 and verify all examples.

Add CI examples

---

.circleci/config.yml
.mk/aws.mk
.mk/packet.mk

Fix circleci workflows 
Stop CircleCI aws and packet testing on cloud start fail
Destroy cloud clusters on integration tests fail
Circleci continue testing on aws start fail
Cloud clusters are not deleting on integration test fail

Fix circleci workflows

---

test/integration/nsmd_test_utils/test_utils.go

Fix issue with invalid container name for mutating webhook client tests.
Issue #1091

Fix mutating container name

---

deployments/helm/icmp-responder/templates/icmp-responder-nse.tpl
deployments/helm/nsm/templates/cluster-role-admin.yaml

Signed-off-by: Lars Ekman <lars.g.ekman@est.tech>
Fix for issue #1094 
* Add the same apiGroups in the helm template as in the corresponding manifest
* Make the "command" item an array for icmp-responder
Fix for issue #1094

Corrected helm-charts. Issue #1094

---

test/integration/basic_excluded_prefixes_test.go
test/integration/basic_nsmdp_test.go
test/integration/bench_connection_test.go
test/integration/recover_remote_nse_nsm_heal_test.go
test/integration/usecase_nsc_icmp_configuration_test.go

Adding the default dataplane variables to tests with the custom config.

Add default dataplane variables to tests with custom config

---

test/integration/usecase_vpn_test.go
test/kube_testing/k8s.go

Issue https://github.com/networkservicemesh/networkservicemesh/issues/1099

Enhance logs for createAndBlock

---

controlplane/pkg/nsm/nse_manager.go
controlplane/pkg/nsm/nsm_heal_processor.go
controlplane/pkg/nsm/nsm_heal_processor_test.go
controlplane/pkg/tests/utils/verifier.go

Adds unit tests for `nsmHealProcessor::healDstDown()`
Issue #1051

Unit tests for nsmHealProcessor::healDstDown()

---

test/integration/nsmd_test_utils/test_utils.go
test/integration/usecase_vpn_test.go

https://circleci.com/gh/networkservicemesh/networkservicemesh/50717

Enhance logs for VPN tests

---

deployments/helm/vpn/templates/vpn-gateway-nse.tpl

Fix to vpn helm chart

---

controlplane/pkg/nsm/nse_manager.go

Return correct error instead of nil
Issue https://github.com/networkservicemesh/networkservicemesh/issues/1132

Return error correctly to avoid nsmd crush

---

.circleci/config.yml
.mk/aws.mk
.mk/azure.mk
.mk/gke.mk
.mk/packet.mk
.mk/vagrant.mk

Print kubelet log on circleci tests fail
Print kubelet log on circleci tests fail
Get more information about fail

Print kubelet log on circleci tests fail

---

scripts/azure/destroy-aks-cluster.sh

https://github.com/networkservicemesh/networkservicemesh/issues/1106

Add attempts for destroying azure cluster to avoid job failing

---

.mk/k8s.mk
test/kube_testing/k8s.go

1. Fix issue with `k8s-icmp-responder-` make targets
2. Fix issue with array out of bound panic

Fix small issues

---

docs/guide-debug.md
test/integration/basic_excluded_prefixes_test.go
test/integration/basic_memif_test.go
test/integration/basic_monitor_crossconnect_metrics_test.go
test/integration/basic_monitor_crossconnect_test.go
test/integration/basic_nsmd_deploy_restart_test.go
test/integration/basic_nsmd_deploy_test.go
test/integration/basic_nsmd_deploy_time_test.go
test/integration/basic_nsmd_k8s_test.go
test/integration/basic_nsmdp_test.go
test/integration/bench_connection_test.go
test/integration/recover_death_handling_test.go
test/integration/recover_nse_dataplane_heal_test.go
test/integration/recover_nse_heal_test.go
test/integration/recover_nse_nsm_heal_test.go
test/integration/recover_remote_nse_nsm_heal_test.go
test/integration/usecase_nsc_icmp_configuration_test.go
test/integration/usecase_vpn_test.go
test/integration/utils/utils.go

In order to satisfy linter requirements and https://github.com/networkservicemesh/networkservicemesh/pull/1135#discussion_r286277596

Rename nsmd_test_utils to utils

---

controlplane/pkg/nsm/nse_requests.go
test/integration/recover_nse_heal_test.go

Fix issue with healing connection from local NSE to remote NSE.
Issue #1150

Fix healing from local to remote NSE

---

.circleci/config.yml

Fix config file for CircleCI

---

.circleci/provision.sh
controlplane/pkg/model/client_connection.go
controlplane/pkg/tests/test-listener.go
scripts/terraform/packet.tf
test/kubetest/utils.go

https://circleci.com/gh/networkservicemesh/networkservicemesh/60093

TestOneToOneConnection fix: check result on nil before casting

---

.mk/packet.mk

Set parameter -parallelism=2 to terraform apply

---

.circleci/config.yml
controlplane/pkg/model/listener_test.go
controlplane/pkg/nsmd/nsmd_crossconnect_client.go
k8s/pkg/registryserver/nsm.go
test/integration/basic_monitor_crossconnect_test.go
test/integration/recover_xcon_monitor_test.go
test/kubetest/monitor_utils.go

Properly write to crossconnect monitor during heal

Fix writing to xcon monitor during heal, add tests

---

test/integration/recover_remote_nse_nsm_heal_test.go

Fix test TestNSMHealRemoteDieNSMD_NSE
Fix CI test TestNSMHealRemoteDieNSMD_NSE

Fix for #1195

---

deployments/helm/nsm/templates/crd-networkserviceendpoints.yaml
deployments/helm/nsm/templates/crd-networkservicemanagers.yaml
deployments/helm/nsm/templates/crd-networkservices.yaml

Update resources version in helm charts.
Missed in #1170.

Update resources version in helm charts

---

test/integration/recover_death_handling_test.go
test/integration/recover_nse_dataplane_heal_test.go
test/integration/recover_remote_nse_nsm_heal_test.go
test/kubetest/testing_pod_fixture.go
test/kubetest/utils.go

https://github.com/networkservicemesh/networkservicemesh/issues/1188

Expand dataplane healing tests

---

Makefile
examples/Makefile

Remove Travis CI leftovers

---

deployments/helm/nsm/templates/crd-networkserviceendpoints.yaml
deployments/helm/nsm/templates/crd-networkservicemanagers.yaml
deployments/helm/nsm/templates/crd-networkservices.yaml

Update resource version in helm charts

---

controlplane/pkg/apis/nsm/nsm.go
controlplane/pkg/nsm/nsm.go
controlplane/pkg/nsm/nsm_prefix_collector.go
controlplane/pkg/tests/nsmd_local_test.go
test/integration/recover_xcon_monitor_test.go

Fix excludePrefix unit tests

---

.circleci/config.yml
.mk/docker.mk
.mk/integration.mk
.mk/k8s.mk
.mk/vpp_agent.mk
Makefile
test/integration/basic_dataplane_standalone_test.go
test/integration/basic_excluded_prefixes_test.go
test/integration/basic_nsmd_deploy_test.go
test/integration/basic_nsmdp_test.go
test/integration/recover_death_handling_test.go
test/integration/recover_nse_dataplane_heal_test.go
test/integration/recover_remote_nse_nsm_heal_test.go
test/integration/usecase_nsc_icmp_configuration_test.go
test/integration/usecase_vpn_test.go
test/kubetest/common.go
test/kubetest/k8s.go
test/kubetest/pods/common.go
test/kubetest/utils.go
test/kubetest/vpp_utils.go

Refactor the integration testing and some of the Makefiles so the forwarding plane is not that tightly coupled.

Decouple the forwarding plane dependencies

---

controlplane/cmd/nsmd/nsmd.go
controlplane/pkg/apis/nsm/nsm.go
controlplane/pkg/model/client_connection.go
controlplane/pkg/nsm/nsm.go
controlplane/pkg/nsm/nsm_heal.go
controlplane/pkg/nsm/nsm_heal_processor.go
controlplane/pkg/nsmd/nsmd.go
controlplane/pkg/nsmd/nsmd_crossconnect_client.go
controlplane/pkg/nsmd/workspace.go
controlplane/pkg/services/client_connection_manager.go
controlplane/pkg/tests/heal_nse_test.go
controlplane/pkg/tests/nsmd_crossconnect_client_test.go
controlplane/pkg/tests/nsmd_test_utils.go
sdk/endpoint/endpoint.go
test/applications/cmd/monitoring-nsc/nsc.go
test/applications/cmd/nse/icmp-responder-nse/nse.go
test/integration/basic_delete_dirty_nse_test.go
test/integration/recover_update_local_connection_test.go
test/kubetest/k8s.go
test/kubetest/pods/icmp_responder_nse.go
test/kubetest/pods/vppagent_icmp_responder.go
test/kubetest/pods/vppagent_nsc.go
test/kubetest/utils.go

Added NSE monitoring to NSM. If connection to NSE dies, NSE is getting deleted from the registry.
If connection to NSE is not getting alive in 10 seconds, NSE is getting deleted from the registry.
NSMD should periodically check NSE without connections are alive and update registry since field. #836

Added NSE monitoring to NSM

---

controlplane/pkg/nsm/nse_requests.go
controlplane/pkg/nsm/nsm.go
dataplane/vppagent/pkg/vppagent/vppagent.go
test/kubetest/k8s.go

The local mechanisms supported by the data plane are not taken into account but hardcoded instead.

Take into account the local mechanisms when creating a connection

---

.circleci/config.yml

Publish additional images needed for people to run example to Dockerhub.

---

scripts/lint-download.sh

Fix "‘/go/bin’: Operation not permitted" error on CI

---

docs/guide-kind.md

Signed-off-by: Faseela K <faseela.k@ericsson.com>

Minor modification to guide-kind.md

---

.golangci.yml

Fix 'Can't run linter depguard' error on CI

---

.circleci/config.yml

This shoudl make the target pass
Static analysis is failing.

Move the static analysis class to large

---

test/integration/recover_xcon_monitor_test.go

Issue https://github.com/networkservicemesh/networkservicemesh/issues/1208

Add FailLogger to monitor tests

---

test/kubetest/ip.go
test/kubetest/utils.go
test/kubetest/vpp_utils.go

So one can have more Clients in the tests
Add IP detection the integration testing infra.
Allow for more complicated multi-client tests.

Make CheckNSC detect local and remote IPs

---

controlplane/pkg/nsmd/nsmd.go
k8s/pkg/apis/networkservice/v1alpha1/types.go
k8s/pkg/registryserver/discovery.go
k8s/pkg/registryserver/helpers.go
k8s/pkg/registryserver/nse.go
k8s/pkg/registryserver/nsm.go
k8s/pkg/tests/nse_cache_test.go
test/integration/basic_delete_dirty_nse_test.go
test/integration/basic_nsm_restart_restore_nse_test.go
test/kubetest/k8s.go
test/kubetest/utils.go

Refactor NSE restore on NSM restart.
Issue #1215.

Refactor NSE restore on NSM restart

---

sdk/README.md
sdk/common/configuration.go

There is some stale configuration about configuring routes.

Remove mentions of ROUTES in configuration

---

.mk/code_analysis.mk

1) `make lint-install` could update linter
2) `make lint...` could work with environments where  GO111MODULE=auto or something else

Add GO111MODULE=on for linter

---

test/kubetest/monitor_utils.go

Increase timeout for event waiting
Issue #1284

TestXconMonitorSingleNodeHealFailed: Increase timeout for event waiting

---

test/kubetest/pods/admission_webhook.go
test/kubetest/utils.go

Admission-webhook used `latest` tag

Pass TAG to admission-webhook in integration tests

---

scripts/kind.yaml

Update to the new kind v1alpha3 API

---

test/cloudtest/pkg/commands/main.go
test/cloudtest/pkg/providers/packet/packet_provider.go
test/cloudtest/pkg/providers/providers.go
test/cloudtest/pkg/providers/shell/shell_provider.go
test/cloudtest/pkg/shell/shell_manager.go
test/cloudtest/pkg/tests/all_cluster_fail_test.go

We need to report error in case some of cluster could not start at all.
Update CloudTest app to generate junit.xml report entry in case all instances of configured cluster could not start.
To make our CI testing more clean.

Report cluster startup failed

---

.cloudtest/aws.yaml
.cloudtest/azure.yaml
.cloudtest/gke.yaml
.cloudtest/packet.yaml
test/cloudtest/pkg/commands/main.go
test/cloudtest/pkg/config/config.go
test/cloudtest/pkg/k8s/validator.go
test/cloudtest/pkg/providers/packet/packet_provider.go
test/cloudtest/pkg/providers/shell/shell_provider.go
test/cloudtest/pkg/shell/env_manager.go
test/cloudtest/pkg/tests/shell_provider_test.go

Make a cluster names a bit better to find logs in CircleCI
Make a cluster names a bit better to find logs in CircleCI

Improve cluster names

---

controlplane/pkg/apis/nsm/nsm.go
controlplane/pkg/model/client_connection.go
controlplane/pkg/nsm/nsm.go
controlplane/pkg/nsm/nsm_heal_processor.go
test/kubetest/k8s.go

Refactor healing.
Healing should looks better :)

Refactor healing

---

sdk/README.md
sdk/endpoint/client.go
sdk/endpoint/composite.go
sdk/endpoint/connection.go
sdk/endpoint/custom_func.go
sdk/endpoint/endpoint.go
sdk/endpoint/ipam.go
sdk/endpoint/monitor.go
test/applications/cmd/icmp-responder-nse/main.go
test/applications/cmd/vppagent-firewall-nse/interface.go
test/applications/cmd/vppagent-icmp-responder-nse/composite.go

Factor out monitor from sdk/endpoint

---

sdk/README.md

Fix few typos in the doc

---

.circleci/config.yml

Enforce proper code formatting for the project

---

test/integration/usecase_vpn_test.go

https://github.com/networkservicemesh/networkservicemesh/issues/1152

Fix usecase_vpn_test tests are failing inconsistently

---

.circleci/config.yml
.mk/code_analysis.mk

release-0.1: Switch over to using the CI repo for non-push images.

---

.circleci/config.yml
.mk/k8s.mk
k8s/conf/admission-webhook.yaml
test/kubetest/pods/admission_webhook.go

Master: Switch over to using the CI repo for non-push images

---

.circleci/config.yml

Publish images from master under tag "master" instead of latest.

---

controlplane/cmd/nsmd/main.go
controlplane/pkg/nsmd/nsmd.go
controlplane/pkg/nsmd/probes.go
controlplane/pkg/tests/nsmd_test_utils.go
dataplane/pkg/common/dataplane.go
dataplane/pkg/common/dataplaneregistrarclient.go
dataplane/pkg/common/probes.go
dataplane/vppagent/cmd/vppagent-dataplane.go
test/integration/basic_nsmd_deploy_test.go

Readiness probe should be success only when all services are started.
Restart container if starting services returns error.
Readiness probe was success even if services was not ready yet.

Refactor readiness probe check

---

scripts/aws/create-kubernetes-cluster.go

Use Amazon AMI image with Kubernetes version 1.13.7

Update kubernetes version on aws clusters

---

test/integration/basic_dataplane_standalone_test.go

Dataplane standalone test should compile.
Fix Dataplane standalone test

Fix Dataplane standalone test

---

.circleci/config.yml

Build should fail if tests not compile
Build should fail if tests not compile. Right now it could continue running.
Build should fail if tests not compile

Build should fail if tests not compile

---

test/integration/basic_monitor_crossconnect_test.go

Security #1: Fix TestSeveralCrossConnects

---

.circleci/config.yml
scripts/kind.yaml

Fix version of circleci build image

---

test/integration/usecase_deployment_order_test.go

Disable TestDeploymentOrder*

---

test/integration/basic_monitor_crossconnect_test.go

Fix TestSingleCrossConnectMonitorBeforeXcons

---

.mk/k8s.mk
controlplane/pkg/sidecars/nsm-init.go
controlplane/pkg/sidecars/nsm-monitor.go
controlplane/pkg/sidecars/nsmapp.go
controlplane/pkg/tests/nsm_monitor_test.go
docs/spec/nsm-monitor.md
side-cars/cmd/nsm-init/main.go
side-cars/cmd/nsm-monitor/main.go
test/applications/cmd/monitoring-nsc/main.go
test/integration/recover_update_local_connection_test.go

Refactor monitoring-nsc with using nsm-monitor

---

side-cars/cmd/nsm-init/main.go
side-cars/cmd/nsm-monitor/main.go
test/applications/cmd/monitoring-nsc/main.go

After merges https://github.com/networkservicemesh/networkservicemesh/pull/1377, https://github.com/networkservicemesh/networkservicemesh/pull/1391 we have build problem on master branch https://circleci.com/gh/networkservicemesh/networkservicemesh/82891

Make format

---

.circleci/config.yml
.mk/formatting.mk
Makefile
dataplane/vppagent/pkg/vppagent/vppagent.go
docs/guide-build.md
test/applications/Makefile

Add 'install-formatter' target

---

README.md

Signed-off-by: Lucina Stricko <lucina@vulk.coop>
- added new biweekly zoom call to readme, every other Tuesday at 10-11am CET
- per NSM WG, an additional zoom call has been added for contributors in various time zones

add new biweekly zoom call to readme

---

controlplane/pkg/nsmd/nsmd_crossconnect_client.go
controlplane/pkg/tests/nsmd_test_utils.go

Fix unstable TestHealRemoteNSE test

---

scripts/azure/create-aks-cluster.sh

Add public ip to AKS nodes 
Allow Inbound traffic rule
Required for #1298

Azure public ip

---

.golangci.yml
scripts/lint-download.sh

If linter is disabled for tests it may generate false-positive deadcode results for test util files. See https://circleci.com/gh/networkservicemesh/networkservicemesh/84686?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-checks-link

Enable linter for tests

---

.cloudtest/aws.yaml

Temporary disabling testing on AWS cluster
#1424

Disable testing on AWS cluster

---

controllers/sriov-controller/dpapi-controller.go
controlplane/pkg/nsmd/dataplanes.go
controlplane/pkg/nsmd/nsmd.go
controlplane/pkg/nsmd/workspace.go
controlplane/pkg/plugins/registry.go
controlplane/pkg/tests/nsmd_crossconnect_client_test.go
dataplane/pkg/common/dataplane.go
dataplane/pkg/common/dataplaneregistrarclient.go
k8s/cmd/nsmdp/nsmdp.go
k8s/pkg/registryserver/server.go
pkg/tools/socket.go
pkg/tools/tools.go
sdk/endpoint/endpoint.go
test/applications/cmd/proxy-xcon-monitor/main.go
test/integration/basic_dataplane_standalone_test.go

- Add `tools.NewServer` function with opentracing support
- Add builder of dialFunc to simplify creating secure `Dial` and `NewServer`

Security #2.5: Create builder for dial functions, add NewServer to tools

---

test/kubetest/k8s.go

https://github.com/networkservicemesh/networkservicemesh/issues/1445

Fix TestDeleteDirtyNSE/TestDeleteDirtyNSEWithClient failed on most clusters 

---

controllers/sriov-controller/service-controller.go

Signed-off-by: ethan <guangming.wang@daocloud.io>
log message cleanup
make logging more natural, as you can see.

service-controller.go: cleanup error message

---

docs/guide-build.md
scripts/install-protoc.sh

Closes: #1444
Signed-off-by: Tim Swanson <tiswanso@cisco.com>
Make the doc refer to prepare-generate.sh
See #1444

Fix codegen section of build-guide

---

.cloudtest/aws.yaml

The fix for https://github.com/networkservicemesh/networkservicemesh/pull/1443 possibly fixed the issue with AWS.

Enable AWS

---

deployments/helm/nsm/templates/crd-networkserviceendpoints.yaml
deployments/helm/nsm/templates/crd-networkservicemanagers.yaml
deployments/helm/nsm/templates/crd-networkservices.yaml

We need to update the helm charts with the new CRD scope.
FIx the Helm charts for #1440.

Fix helm CRDs scope to namespaced

---

deployments/helm/nsm/templates/nsmgr.tpl
deployments/helm/vpn/templates/vpn-gateway-nse.tpl

Fix a typo in nsmgr.tpl

---

test/kubetest/utils.go

https://circleci.com/gh/networkservicemesh/networkservicemesh/87056

Fix NoHealNsmgr config

---

controlplane/pkg/nsm/nsm.go

some typos in logging message, cleanup it make it more human readable.
logging message make it right.
- [x ] Have not tested
not even a bug fix.

cleanup nsm.go logging message typos

---

.circleci/config.yml

Move linter resource class to xlarge

---

scripts/aws/create-kubernetes-cluster.go
scripts/aws/destroy-kubernetes-cluster.go

Run make format

---

test/integration/basic_nsm_restart_restore_nse_test.go

Add tag "basic" for TestNSMgrRestartRestoreNSE
TestNSMgrRestartRestoreNSE does not have tag

Tag TestNSMgrRestartRestoreNSE as basic

---

test/cloudtest/pkg/providers/packet/packet_provider.go

Check for packet.net key are properly created on delete, CloudTest tool should not fail.
Fixes for issue #1435

Fix CloudTest failure

---

deployments/helm/nsm/templates/cluster-role-admin.yaml
k8s/conf/cluster-role-admin.yaml

https://github.com/networkservicemesh/networkservicemesh/issues/1478

Add namespaces to cluster role admin

---

.cloudtest.yaml
.mk/helm.mk
deployments/helm/vpn/templates/vpn-gateway-nse.tpl
deployments/helm/vpn/templates/vppagent-passthrough-nse.tpl
scripts/helm-patch-tiller.sh

Eliminating "k8s/conf" dir #1: replace Example-vpn with Example-helm-vpn

---

.mk/docker.mk
.mk/helm.mk
.mk/k8s.mk
dataplane/kernel-forwarder/README.md
deployments/helm/icmp-responder/templates/icmp-responder-nse.tpl
deployments/helm/nsm/templates/vppagent-dataplane.tpl
deployments/helm/nsm/values.yaml
deployments/helm/proxy-nsmgr/.helmignore
deployments/helm/proxy-nsmgr/Chart.yaml
deployments/helm/proxy-nsmgr/templates/proxy-nsmgr.tpl
deployments/helm/proxy-nsmgr/values.yaml
docs/guide-quickstart.md
docs/spec/kernel-forwarding-plane.md

Eliminating "k8s/conf" dir #2: Move kernel-forwarder and proxy-nsmgr to Helm

---

controlplane/pkg/apis/plugins/gen.go
controlplane/pkg/apis/registry/constants.go
controlplane/pkg/plugins/connection_plugin.go
controlplane/pkg/plugins/registry.go
controlplane/pkg/plugins/utils.go
controlplane/pkg/tests/nsmd_plugin_registry_test.go
controlplane/pkg/tests/nsmd_test_utils.go

https://github.com/networkservicemesh/networkservicemesh/issues/1339

Plugins #2.3 Move name uniqueness check, other plugin registry fixes

---

.circleci/config.yml

The image is not being published to Dockerhub.
Closes #1530

Publish the Kernel-forwarder image in CI #1530

---

test/integration/basic_dns_test.go

Disable TestDNSMonitoringNsc

---

test/kubetest/k8s.go

https://github.com/networkservicemesh/networkservicemesh/issues/1511

Fix TestNSMHealRemoteDieNSMD_NSE periodically falls on CI

---

k8s/pkg/registryserver/registry_cache.go
k8s/pkg/registryserver/resource_cache/ns_cache.go
k8s/pkg/registryserver/resource_cache/nse_cache.go
k8s/pkg/registryserver/resource_cache/nsm_cache.go
k8s/pkg/registryserver/resource_cache/resource_cache.go
k8s/pkg/tests/ns_cache_test.go
k8s/pkg/tests/nse_cache_test.go
k8s/pkg/tests/nsm_cache_test.go

https://github.com/networkservicemesh/networkservicemesh/issues/1503

Fix failed to create or update nsm on deploy with custom ns

---

controllers/sriov-controller/dpapi-controller.go

Signed-off-by: Guangming Wang <guangming.wang@daocloud.io>
correct logging message misspelled words
- [x ] Have not tested

dpapi-controller.go: logging message fix typos

---

test/cloudtest/pkg/commands/main.go

Check that test has at least one available cluster in each required cluster group
https://circleci.com/gh/networkservicemesh/networkservicemesh/94351
There were not any available packet cluster but test was not skipped because available gke cluster

Fix available clusters in cloudtest for interdomain

---

controlplane/pkg/remote/proxy_network_service_server/proxy_network_service_server.go

Add connecting attempts and connection timeout into proxy-nsmd for proper heal 
Unstable TestInterdomainNSMHealRemoteDieNSMD (#1532)

Fix infinite nse request in proxy-nsmd

---

controlplane/cmd/nsmd/main.go
controlplane/pkg/apis/nsm/nsm.go
controlplane/pkg/apis/nsm/nsm_properties.go
controlplane/pkg/nsm/nse_manager.go
controlplane/pkg/nsm/nsm.go
controlplane/pkg/nsm/nsm_heal_processor.go
controlplane/pkg/nsm/nsm_heal_processor_test.go
controlplane/pkg/nsmd/nsmd.go
controlplane/pkg/nsmd/serviceregistry.go
controlplane/pkg/plugins/registry.go
controlplane/pkg/plugins/utils.go
controlplane/pkg/serviceregistry/serviceregistry.go
controlplane/pkg/tests/nsmd_registry_test.go
controlplane/pkg/tests/nsmd_test_utils.go
controlplane/pkg/tests/restore_state_test.go
go.mod
go.sum
pkg/tools/socket.go
sdk/common/span.go
test/kubetest/pods/jaeger.go
test/kubetest/pods/versioning.go

Opentracing should be used properly to ensure context is passing a correct span ids.
To see a full trace from client to endpoint. This is first part of improving traces.

Fixes in open tracing usage

---

.github/workflows/ci.yml
.github/workflows/scripts/test-charts.sh

First pass at Github Actions.

---

test/integration/interdomain_death_handling_test.go
test/integration/recover_death_handling_test.go

Replace "ip addr" attempts with waiting for logs entry
#1561

Fix stability of "death handling" tests

---

scripts/nsc_ping_all.sh

Update ip addresses in nsc_ping_all.sh

---

.circleci/config.yml
go.mod
go.sum
scripts/check_dependencies.sh
scripts/prepare-generate.sh

…xpected problems
After go build ./... go.sum or go.mod file could be changed. "Hidden dependencies" can be a reason of unexpected problems.

Add check for go.mod and go.sum after go build

---

.mk/docker.mk
.mk/vpp_agent.mk
build/Dockerfile.nsmd-k8s
build/Dockerfile.proxy-nsmd-k8s
controlplane/build/Dockerfile.nsmd
controlplane/build/Dockerfile.proxy-nsmd
dataplane/kernel-forwarder/build/Dockerfile.kernel-forwarder
dataplane/vppagent/build/Dockerfile.vppagent-dataplane
dataplane/vppagent/build/Dockerfile.vppagent-dataplane-dev
docker/Dockerfile.admission-webhook
docker/Dockerfile.crossconnect-monitor
docker/Dockerfile.nsm-coredns
k8s/build/Dockerfile.nsmdp
side-cars/build/Dockerfile.nsm-init
side-cars/build/Dockerfile.nsm-monitor
test/applications/build/Dockerfile.test-common
test/applications/build/Dockerfile.vpp-test-common

Add GOPROXY, get rid of 'apk --no-cache add git' in docker files

---

.circleci/config.yml
docs/guide-build.md
scripts/lint-check-diff.sh

Excludes case: https://circleci.com/gh/networkservicemesh/networkservicemesh/99232

Stabilization of linter

---

test/kubetest/monitor_utils.go

https://github.com/networkservicemesh/networkservicemesh/issues/1596

Fix unit test TestOrEventChecker_SecondSuccess is unstable

---

controlplane/cmd/nsmd/main.go
controlplane/pkg/plugins/registry.go
controlplane/pkg/plugins/utils.go
controlplane/pkg/tests/nsmd_plugin_test.go
k8s/cmd/nsmd-k8s/main.go
k8s/pkg/prefixcollector/collector_server.go

Fix nsmd k8s panic and re-registration error

---

.cloudtest.yaml
.golangci.yml
.mk/k8s.mk
scripts/logs_snapshot.sh
test/cloudtest/pkg/commands/main.go
test/cloudtest/pkg/runners/gotest_runner.go
test/cloudtest/pkg/runners/shelltest_runner.go
test/cloudtest/pkg/shell/shell_manager.go
test/cloudtest/pkg/utils/process.go
test/cloudtest/pkg/utils/shell_utils.go
test/integration/basic_memif_test.go
test/integration/usecase_deploy_wrong_nsc_test.go
test/kubetest/const.go
test/kubetest/log_utils.go

1) Improve archive logs naming
2) Archive logs for examples
3) Fix bug with force delete
4) Fix bug with running on_fail scripts
5) Fix bug with cleaning namespaces for configs with special root
6) https://github.com/networkservicemesh/networkservicemesh/issues/1605
7) Add possible to store previous logs from pods

Improve archive logs naming

---

k8s/pkg/prefixcollector/collector.go

Fix channel reading in monitorReservedSubnets() (#1950)

---

test/applications/cmd/icmp-responder-nse/main.go

https://github.com/networkservicemesh/networkservicemesh/issues/1612

Fix TestUpdateConnectionOnNSEUpdate fails on CI

---

controlplane/cmd/nsmd/main.go
controlplane/cmd/proxynsmd/main.go
dataplane/kernel-forwarder/pkg/kernelforwarder/kernelforwarder.go
dataplane/vppagent/pkg/vppagent/vppagent.go
docs/env.md
k8s/cmd/nsmd-k8s/main.go
k8s/cmd/nsmdp/main.go
k8s/cmd/proxy-nsmd-k8s/main.go
pkg/tools/socket.go
pkg/tools/tools.go
sdk/README.md
sdk/client/client.go
sdk/common/configuration.go
sdk/endpoint/endpoint.go
side-cars/pkg/nsm-init/nsm-init.go
side-cars/pkg/nsm-monitor/nsm-monitor.go
side-cars/pkg/nsm-monitor/nsm_monitor_test.go
test/applications/cmd/monitoring-nsc/main.go
test/applications/cmd/vppagent-nsc/main.go

1) Adds possible to disable opentracing for containers which uses opentracing.
2) Unifies the check is opentracing enabled

Fix opentracing env usage

---

go.sum
k8s/cmd/nsmdp/nsmdp.go
sdk/common/configuration.go
sdk/common/constants.go
test/applications/cmd/vppagent-nsc/main.go

Moved constants to sdk/ to remove spurious 'controlplane' dependencies.

---

utils/go.mod

Fix to module path for utils

---

docs/guide-build.md

helm-install-nsm --> make helm-install-nsm
Need to add _make_ to beginning of line. (x2)

Fix guide-build.md

---

controlplane/pkg/monitor/remote/remote_connection_monitor_server.go
controlplane/pkg/nsmd/nsmd.go
controlplane/pkg/tests/nsmd_crossconnect_client_test.go
sdk/go.mod
sdk/go.sum

Monitor had deep dependencies on controlplane that were easy
to factor out by simply 'wrapping' controlplane dependent parts
around monitor rather than *embedding* them.

Break monitor free from various controlplane/ pieces.

---

.cloudtest/packet/create-kubernetes-cluster.sh

Can lead to interesting 3 nodes clusters:
```
INFO[0383] prepare: packet-2 => kubectl get nodes       
INFO[0383] packet-2: prepare -> StdOut => NAME                                          STATUS   ROLES    AGE    VERSION 
INFO[0383] packet-2: prepare -> StdOut => master-packet-2-2019-9-23-104308-d012ca8255   Ready    master   109s   v1.15.4 
INFO[0383] packet-2: prepare -> StdOut => worker-packet-1-2019-9-23-104308-0b652d805d   Ready    <none>   66s    v1.15.4 
INFO[0383] packet-2: prepare -> StdOut => worker-packet-2-2019-9-23-104308-d012ca8255   Ready    <none>   66s    v1.15.4 
```

Separate /tmp folders for join-cluster.sh

---

.env/kind.env

Add .env/kind.env file

---

controllers/sriov-controller/go.mod
go.mod
k8s/go.mod
scripts/switch_k8s_version.sh
test/go.mod

Also restore missing comment in ./go.mod, k8s/go.mod, test/go.mod, and controllers/sriov-controller/go.mod

Fix the ./scripts/switch_k8s_version.sh to work in a multi-mod world.

---

dataplane/vppagent/build/Dockerfile.vppagent-dataplane
dataplane/vppagent/build/Dockerfile.vppagent-dataplane-dev
test/applications/build/Dockerfile.vpp-test-common

Note: This is because of:
https://github.com/ligato/vpp-agent/issues/1477
(and the fact we don't use that plugin)

Turn off vppagent telemetry plugin

---

.gitignore

.gitignore records for build artifacts

---

docs/guide-quickstart.md

Updated Quick start guide to reflect how to deploy NSM.
Split out the monitoring tooling and expected outcomes of applying the deploy
Updating docs so that it's easier for people to get started.

update quickstart guide to reflect codebase

---

test/integration/recover_remote_nse_nsm_heal_test.go

Turn on-failure log collection for TestNSMHealRemoteDieNSMDFakeEndpoint to get more information for resolving #1666 
#1666

Turn on logs collecting for TestNSMHealRemoteDieNSMDFakeEndpoint

---

.circleci/config.yml
go.mod
scripts/run_unit_tests.sh

Fix running unit tests from all modules
Currently cl shows:
```
DONE 0 tests in 0.093s
```

Fix running unit tests on cl

---

side-cars/pkg/nsm-monitor/nsm-monitor.go
side-cars/pkg/nsm-monitor/nsm_monitor_test.go

Fix TestNSMMonitorInit

---

scripts/for-each-module.sh

Fix master breakage on for-each excluding vendor

---

.circleci/config.yml
scripts/for-each-module.sh

Push networkservicemesh/spire-registration

---

scripts/for-each-module.sh

Related to https://github.com/networkservicemesh/networkservicemesh/pull/1677.
1677 was merged with an error on the sanity check
Fix a next case:
1) sh scripts/for-each-module.sh " go mod vendor"
2) sh scripts/for-each-module.sh "" 
Actual:
...
~/go/src/github.com/networkservicemesh/networkservicemesh/utils/**vendor**/github.com/sirupsen/logrus ~/go/src/github.com/networkservicemesh/networkservicemesh
~/go/src/github.com/networkservicemesh/networkservicemesh
~/go/src/github.com/networkservicemesh/networkservicemesh/utils/**vendor**/gopkg.in/yaml.v2 ~/go/src/github.com/networkservicemesh/networkservicemesh
~/go/src/github.com/networkservicemesh/networkservicemesh
...
Expected: output has only nsm modules

Exclude vendor folder for script 'for-each-module' #2

---

.mk/helm.mk
deployments/helm/nsm/templates/vppagent-dataplane.tpl

Disable spire until it can be fixed to work properly outside of CI

---

scripts/gke/load-images.sh

Fix `make gke-%-load-images`
Script required for the debug purposes

Fix gke load images script

---

deployments/helm/nsm/charts/spire/templates/agent-daemonset.tpl
docker/Dockerfile.spire-registration

Issue https://github.com/networkservicemesh/networkservicemesh/issues/1680

Build custom spire-agent and spire-server with fix for kind-cluster

---

.gitignore

Related to https://github.com/networkservicemesh/networkservicemesh/pull/1664
Adds missed `cmd` artifact to `.gitignore`

.gitignore records for build artifacts #2

---

.circleci/config.yml
.circleci/skip_job_on_pattern.sh
docs/aws-quickstart.md

We are getting an increased volume of doc only changes from the community that shouldn't require
lengthy CI.

Skip CI on doc only changes.

---

docs/guide-quickstart.md

Signed-off-by: Wayne <wayne@flickswitch.co.za>
Formatting of code blocks was wrong in quick start, degraded readability.
Better Docs

Update formatting of quickstart

---

controlplane/pkg/remote/proxy_network_service_server/proxy_network_service_server.go

Change Network Service name in interdomain request for properly healing
#1603 , #1701

Fix healing in interdomain tests

---

test/integration/usecase_deployment_order_test.go

MakeLogsSnapshot to TestDeploymentOrder* tests

---

.circleci/skip_job_on_pattern.sh

Fix skip_on_match to only run on PR branches.

---

.circleci/skip_job_on_pattern.sh

Note: Will fix in followup patch to make shellcheck run against this shell
script on PRs.  But first lets get master happy.

Fix shellcheck failures for skip_on_pattern.

---

.circleci/skip_job_on_pattern.sh

Really fix all shellcheck errors on skip_on_patter this time.

---

side-cars/pkg/nsm-monitor/nsm-monitor.go

One of the reason why test `TestUpdateConnectionOnNSEUpdate` fails.
Issue https://github.com/networkservicemesh/networkservicemesh/issues/1612

Fix condition for enabling JaegerTracing

---

dataplane/pkg/common/dataplane.go

Small fix about the sanity check as it was not handling as it should. 
For ex. in case of local mechanism types, it was failing with an error for missing remote mechanisms support.

Fix sanity check for supported mechanism types by the forwarding plane

---

.circleci/config.yml

Make sure we do shellcheck before skip_on_pattern

---

.gitignore

Related to https://github.com/networkservicemesh/networkservicemesh/pull/1678
Current git ignore ignores new files in cmd/*

.gitignore records for build artifacts #3

---

deployments/helm/nsm/charts/spire/templates/agent-configmap.tpl
deployments/helm/nsm/charts/spire/templates/agent-daemonset.tpl
deployments/helm/nsm/charts/spire/templates/server-configmap.tpl
deployments/helm/nsm/charts/spire/templates/server-secrets.tpl
deployments/helm/nsm/charts/spire/templates/server-statefulset.tpl
deployments/helm/nsm/charts/spire/templates/spire-roles.tpl

Issue https://github.com/networkservicemesh/networkservicemesh/issues/1661

Get rid of hardcoded 'bootstrap.crt', using k8sbundle plugin

---

sdk/README.md
sdk/client/client.go
sdk/common/configuration.go

Also, fix the behavior so it matches the Admission controller description.

Add SDK configuration NSC_INTERFACE_NAME

---

.cloudtest.yaml
.yamllint.yml
scripts/aws/aws-k8s-cni.yaml
scripts/aws/create-kubernetes-cluster.go

Downgrade aws k8s cni plugin version; 
Enable aws interdomain tests
Fixing interdomain issue on AWS cluster #1603

Downgrade aws k8s cni plugin version

---

test/cloudtest/pkg/commands/main.go
test/cloudtest/pkg/tests/shell_provider_test.go
test/cloudtest/pkg/utils/utils.go

Fix slow TestUsedClusterCancel test

---

test/cloudtest/pkg/tests/shell_provider_test.go

Fix TestUnusedClusterShutdownByMonitor

---

.circleci/config.yml
.mk/build.mk
.mk/k8s.mk
controlplane/build.mk
dataplane/build.mk
k8s/build.mk
side-cars/build.mk
test/build.mk

Reduce to a single (hopefully fast) build-containers

---

scripts/aws/create-kubernetes-cluster.go

Update EKS node image to kubernetes 1.14 (latest)

Update kubernetes version on AWS cloud

---

docs/env.md
docs/spec/dns-integration.md

1) Added part about using admission webhook.
2) Updated doc after the last DNS specific changes
https://github.com/networkservicemesh/networkservicemesh/issues/1716

Update DNS documentation

---

.cloudtest.yaml

need to cover basic functionality for kernel forwarder to avoid potential regressions related to new functionality
1) https://github.com/networkservicemesh/networkservicemesh/issues/1563
2) https://github.com/networkservicemesh/networkservicemesh/issues/1565

Add helm-icmp kernel forwarder test

---

controlplane/api/connection/connection_helpers.go
controlplane/api/connection/mechanism_helpers.go
controlplane/api/connection/mechanisms/cls/constants.go
controlplane/api/connection/mechanisms/common/constants.go
controlplane/api/connection/mechanisms/common/helpers.go
controlplane/api/connection/mechanisms/kernel/constants.go
controlplane/api/connection/mechanisms/memif/constants.go
controlplane/api/connection/mechanisms/vxlan/constant.go
controlplane/api/connection/mechanisms/vxlan/helpers.go
controlplane/api/networkservice/helpers.go

Helpers for Unified API.

---

sdk/compat/connection.go
sdk/compat/monitor_connection_client.go
sdk/compat/monitor_connection_server.go
sdk/compat/networkservice.go
sdk/compat/networkservice_client.go
sdk/compat/networkservice_server.go

Unified API Compatiblity Helpers.

---

controlplane/cmd/proxy-nsmd/main.go
controlplane/pkg/nsmd/nsmd.go
controlplane/pkg/nsmd/serviceregistry.go
controlplane/pkg/nsmd/workspace.go
controlplane/pkg/tests/nsmd_crossconnect_client_test.go
controlplane/pkg/tests/nsmd_test_utils.go
sdk/common/connection.go
sdk/compat/monitor_connection_server.go
sdk/endpoint/endpoint.go
sdk/endpoint/monitor.go
sdk/monitor/local/local_connection_monitor_client.go
sdk/monitor/remote/remote_connection_monitor_client.go

This commit applies the unified<->remote/local Adapters throughout
the code base.

Apply Adapters throughout the code base.

---

.mk/helm.mk
.mk/k8s.mk

Lets try re-enabling spire by default.

---

.cloudtest/aws.yaml
.cloudtest/azure.yaml
.cloudtest/gke.yaml
.cloudtest/packet.yaml
.mk/spire.mk
deployments/helm/nsm/charts/spire/templates/server-configmap.tpl
deployments/helm/nsm/charts/spire/templates/spire-namespace.tpl
deployments/helm/nsm/charts/spire/templates/spire-secret.tpl

Spire helm fix

---

.circleci/config.yml

Remove step mistakenly skipping helm tests.

---

.cloudtest/aws.yaml
.cloudtest/azure.yaml
.cloudtest/gke.yaml
.cloudtest/packet.yaml

Hopefully this speeds up our CI builds.

Increase number of cluster instances for CI to four

---

.mk/helm.mk
deployments/helm/nsm/charts/admission-webhook/templates/admission-webhook-secret.tpl
deployments/helm/nsm/templates/nsmgr.tpl
deployments/helm/nsm/templates/vppagent-forwarder.tpl
docs/env.md
k8s/cmd/admission-webhook/const.go
k8s/cmd/admission-webhook/main.go
k8s/cmd/admission-webhook/patches.go

Fix Jaeger to work again in helm.

---

controlplane/pkg/services/client_connection_manager.go
controlplane/pkg/tests/client_connection_manager_test.go
test/integration/basic_nsm_restart_restore_nse_test.go
test/integration/basic_nsmdp_test.go
test/integration/interdomain_nse_nsm_heal_test.go
test/integration/recover_remote_nse_nsm_heal_test.go
test/kubetest/utils.go

Fix ClientConnectionManager to properly handle connections in progress and broken ones. + add tests
ClientConnectionManager  could fail because some checks for missed.

Fix Client connection manager Exceptions

---

deployments/helm/icmp-responder/templates/icmp-responder-nse.tpl
deployments/helm/icmp-responder/values.yaml
deployments/helm/proxy-nsmgr/templates/proxy-nsmgr.tpl
deployments/helm/proxy-nsmgr/values.yaml
deployments/helm/vpn/templates/vpn-gateway-nse.tpl
deployments/helm/vpn/templates/vppagent-firewall-nse.tpl
deployments/helm/vpn/templates/vppagent-passthrough-nse.tpl
deployments/helm/vpn/values.yaml
deployments/helm/vpp-icmp-responder/templates/vppagent-icmp-responder-nse.tpl
deployments/helm/vpp-icmp-responder/values.yaml
go-header.yaml
sdk/compat/jaeger_local.go
sdk/compat/jaeger_remote.go
sdk/compat/jaeger_unified.go
sdk/compat/networkservice_client.go
sdk/compat/networkservice_server.go

Wrap Adapters in Jaeger for tracing.

---

deployments/helm/icmp-responder/templates/icmp-responder-nse.tpl
deployments/helm/icmp-responder/values.yaml
deployments/helm/proxy-nsmgr/templates/proxy-nsmgr.tpl
deployments/helm/proxy-nsmgr/values.yaml
deployments/helm/vpn/templates/vpn-gateway-nse.tpl
deployments/helm/vpn/templates/vppagent-firewall-nse.tpl
deployments/helm/vpn/templates/vppagent-passthrough-nse.tpl
deployments/helm/vpn/values.yaml
deployments/helm/vpp-icmp-responder/templates/vppagent-icmp-responder-nse.tpl
deployments/helm/vpp-icmp-responder/values.yaml

Enable Jaeger for all NSE helm charts

---

test/integration/basic_nsmd_deploy_time_test.go

https://github.com/networkservicemesh/networkservicemesh/issues/1784

Improve logging for integration test TestNSMDDeploy

---

controlplane/api/connection/mechanisms/memif/constants.go

Return MemifSocket const

---

.cloudtest/aws.yaml
.cloudtest/azure.yaml
.cloudtest/gke.yaml
.cloudtest/packet.yaml
.mk/spire.mk
pkg/security/scripts/registration.sh

Wait for spire-entries successfully registered before starting tests

---

build/Dockerfile.vppagent-forwarder
forwarder/build.mk
forwarder/vppagent/conf/supervisord/govpp.conf
test/integration/basic_monitor_crossconnect_metrics_test.go

https://github.com/networkservicemesh/networkservicemesh/issues/1763

Fix: TestSimpleMetrics failed with vpp-agent v2.3.0

---

forwarder/pkg/common/forwarder.go

https://circleci.com/workflow-run/36cd37cd-0dc4-41c1-82e8-e7a7ea599a2b

Fix forwarder env reading

---

sdk/compat/connection.go
sdk/compat/connection_test.go
sdk/compat/networkservice_test.go

Add unit tests for compat converters

---

.cloudtest/aws.yaml
docs/aws-quickstart.md
scripts/aws/aws-init.sh

Switch over to CNCF provided AWS for CI.

---

deployments/helm/nsm/charts/admission-webhook/templates/admission-webhook-secret.tpl
k8s/cmd/admission-webhook/const.go
test/kubetest/utils.go

https://github.com/networkservicemesh/networkservicemesh/issues/1817

Fix TestNSCAndICMPWebhook* is unstable

---

docs/guide-build.md
scripts/install-helm.sh

Update install-helm script and guide-build.md

---

controlplane/pkg/nsmd/nsmd_crossconnect_client.go
controlplane/pkg/nsmd/nsmd_monitor_test.go
sdk/monitor/crossconnect/crossconnect_monitor_client.go
sdk/monitor/monitor_client.go
test/kubetest/k8s.go

Root cause: connection monitor client not detected server shutdown.
https://github.com/networkservicemesh/networkservicemesh/issues/1666

Fix TestNSMHealRemoteDieNSMDFakeEndpoint is failed on CI

---

scripts/for-each-module.sh

Fix _**"find"**_ command arguments to get proper modules paths
Current for-each-module script searching in vendor and .git folders

Fix for-each-module script

---

sdk/README.md
sdk/endpoint/dns.go
test/applications/cmd/icmp-responder-nse/main.go

Add DNS to SDK and use in testing.

---

deployments/helm/nsm-monitoring/templates/crossconnect-monitor.tpl

Issue https://github.com/networkservicemesh/networkservicemesh/issues/1780

Fix issue: Cross connect fails to log events with spire enabled

---

.circleci/config.yml
.cloudtest/aws.yaml
.cloudtest/azure.yaml
.cloudtest/gke.yaml
.cloudtest/packet.yaml
.mk/build.mk
.mk/gcb.mk
.mk/gke.mk
.mk/k8s.mk

We have been using three variables:
COMMIT
TAG
CONTAINER_TAG
to communicate the same things.  This PR switches all of those
to using CONTAINER_TAG.

Use a consistent image tag throughout the system.

---

README.md

Remove FOSSA badge as FOSSA has become unreliable due to to many false positives

---

.circleci/config.yml

Fix docker-push to use CONTAINER_TAG rather than TAG

---

.circleci/config.yml
.cloudtest/aws.yaml
.cloudtest/azure.yaml
.cloudtest/gke.yaml
.cloudtest/packet.yaml
.mk/build.mk
.mk/gcb.mk
.mk/gke.mk
.mk/k8s.mk

We have been using three variables:
COMMIT
TAG
CONTAINER_TAG
to communicate the same things.  This PR switches all of those
to using CONTAINER_TAG.
Additionally, it switches the default CONTAINER_TAG to 'master' to match
the helm charts.

Use a consistent image tag throughout the system (release-0.2 version)

---

test/cloudtest/pkg/providers/packet/packet_provider.go

Try to create cluster in another facilities if error
#1851

Fix "packet facility has no provisionable server" error

---

docs/guide-quickstart.md

The quick-start guide was missing a couple of things:
* Helm is not mentioned in the required software
* The make command was missing in one line
Signed-off-by: Manuel Buil <mbuil@suse.com>

Correct the docs

---

go-header.yaml
scripts/lint-check-diff.sh

Fix go-header.yaml to compare to release-0.2 not master

---

deployments/helm/icmp-responder/Chart.yaml
deployments/helm/vpn/Chart.yaml
deployments/helm/vpp-icmp-responder/Chart.yaml

Rename example helm charts to 'examples' not 'use cases' (release-0.2)

---

deployments/helm/icmp-responder/Chart.yaml
deployments/helm/vpn/Chart.yaml
deployments/helm/vpp-icmp-responder/Chart.yaml

Rename example helm charts to 'examples' not 'use cases'

---

.circleci/config.yml

Added job to circleci to publish v0.2.0 when its tagged.

---

build/Dockerfile.spire-registration
deployments/helm/nsm/charts/spire/templates/agent-daemonset.tpl

[release-0.2.0] Updating spire image to 0.8.4

---

deployments/helm/icmp-responder/templates/nsc.tpl
scripts/nsc_ping_all.sh

Cleanups found while updating docs. [release-0.2]

---

deployments/helm/icmp-responder/templates/nsc.tpl
scripts/nsc_ping_all.sh

Cleanups found while updating docs.

---

deployments/helm/vpp-icmp-responder/templates/vpp-icmp-responder-nsc.tpl
deployments/helm/vpp-icmp-responder/templates/vpp-icmp-responder-nse.tpl

and vppagent-nsc vpp-icmp-responder-nsc to match pattern for docs.

Rename vppagent-icmp-responder-nse -> vpp-icmp-responder

---

deployments/helm/vpp-icmp-responder/templates/vpp-icmp-responder-nsc.tpl
deployments/helm/vpp-icmp-responder/templates/vpp-icmp-responder-nse.tpl

and vppagent-nsc vpp-icmp-responder-nsc to match pattern for docs.

Rename vppagent-icmp-responder-nse -> vpp-icmp-responder (release-0.2)

---

.circleci/config.yml
deployments/helm/crossconnect-monitor/values.yaml
deployments/helm/icmp-responder/values.yaml
deployments/helm/nsm/charts/admission-webhook/values.yaml
deployments/helm/nsm/charts/spire/values.yaml
deployments/helm/nsm/values.yaml
deployments/helm/proxy-nsmgr/values.yaml
deployments/helm/vpn/values.yaml
deployments/helm/vpp-icmp-responder/values.yaml

Set tags in helm to v0.2.0.  Set to public latest on v0.2.0 tag in git repo.

---

controlplane/pkg/common/monitor_service.go
controlplane/pkg/nsmd/nsmd.go
controlplane/pkg/nsmd/nsmd_crossconnect_client.go
controlplane/pkg/tests/nsmd_test_utils.go
controlplane/pkg/tests/restore_state_test.go

https://github.com/networkservicemesh/networkservicemesh/issues/1895

Fix: Nil pointer deference on restart nsmd 

---

netlify.toml

Setup to publish v0.2.0 for default for helm charts.

Do not merge until v0.2.0 has been released.

---

.circleci/skip_job_on_pattern.sh
netlify.toml
scripts/netlify.sh

Fix netlify redirect rule.

---

.gitignore
scripts/vagrant/Vagrantfile
scripts/vagrant/scripts/install_docker.sh
scripts/vagrant/scripts/install_kubernetes.sh
scripts/vagrant/scripts/install_sources.sh

Update vagrant setup and images upload

Update vagrant to use 19.04 and 2Gb

---

.mk/vagrant.mk

> /bin/bash: -c: line 1: syntax error: unexpected end of file
> make: *** [vagrant-admission-webhook-load-images] Error 2

Fix vagrant-load-images make script

---

test/cloudtest/pkg/providers/packet/packet_provider.go

https://circleci.com/gh/networkservicemesh/networkservicemesh/115649

Fix cloudtest crash when creating packet ssh keys

---

scripts/aws/aws-k8s-cni.yaml

Update AWS CNI plugin v1.5.5

---

controlplane/pkg/nsm/nsm.go

Waiting for proper state to start closing connection on timeout
#1561

Fix closing connection on heal starting timeout

---

.cloudtest.yaml
test/integration/usecase_deployment_order_test.go

Fix #1846 deployment order tests

Fix #1846 deployment order tests

---

pkg/tools/spanhelper/span_helper.go

Add limitation for span messages to avoid the problem with transport huge messages

---

.circleci/check_repo_uptodated.sh
.cloudtest.yaml
test/cloudtest/pkg/commands/main.go
test/cloudtest/pkg/config/config.go
test/cloudtest/pkg/tests/cloud_config_test.go
test/cloudtest/pkg/tests/config1.yaml

Finish cloud testing and close clouds if new commit pushed
Cloud test continues testing even if new commit is pushed. It continue holding clouds resources.

Stop cloudtest if new commit found

---

.cloudtest.yaml
test/cloudtest/pkg/commands/main.go

WIP: Fix resource leaking in case of test re-scheduling

---

docs/spec/prefix-service.md

Excluded prefixes documentation 

---

test/cloudtest/pkg/commands/main.go
test/cloudtest/pkg/tests/all_cluster_fail_test.go
test/cloudtest/pkg/tests/retest_test.go

cloudtest: report failure when skipping tests due cluster unavailability

---

build/Dockerfile.vpp-test-common
forwarder/vppagent/conf/supervisord/govpp.conf
test/build.mk

Wait for vpp socket more than 3 seconds
#1922

Increase vppagent attempts connecting to vpp

---

test/cloudtest/pkg/commands/main.go
test/cloudtest/pkg/tests/all_cluster_fail_test.go
test/kubetest/k8s.go
test/kubetest/log_utils.go

+ Make logs to be less vertical space consuming.

CloudTest should properly cleanup multi cloud tests

---

test/cloudtest/pkg/providers/packet/packet_cleanup/tool.go
test/cloudtest/pkg/providers/packet/packethelper/packet_helper.go

We should be able easy cleanup all orphaned clusters, this is tool for packet to do so. On next PR plan to integrate it usage into CloudTesting tool.

Packet cleanup tool

---

pkg/tools/spanhelper/span_helper.go

Messages send to log should not be truncated

Messages send to log should not be truncated

---

.mk/kind.mk
docs/guide-run-interdomain-tests-kind.md
test/kubetest/k8s.go
test/kubetest/pods/versioning.go

Add guide for run interdomain tests via kind

---

.cloudtest/aws.yaml
.cloudtest/azure.yaml
.cloudtest/gke.yaml
.cloudtest/packet.yaml
scripts/prepare-cluster.sh

https://github.com/helm/helm/issues/6361

Workaround for helm 2.15 issue: Delete unavailable apiservices from kubernetes and run prepare again

---

build/Dockerfile.spire-registration
deployments/helm/nsm/charts/spire/templates/agent-daemonset.tpl

Update spire to 0.9.0

---

controlplane/pkg/model/model.go
scripts/lint-check-diff.sh

Script for running linter ignores the status code. Some builds can pass CI with linter issues.

Fix 'script 'lint-check-diff' ignores status code'

---

.circleci/config.yml
.cloudtest/aws.yaml
.cloudtest/azure.yaml
.cloudtest/gke.yaml
.cloudtest/packet.yaml
scripts/aws/create-kubernetes-cluster.go
scripts/aws/destroy-kubernetes-cluster.go
scripts/aws/destroy-old-clusters.sh
scripts/aws/go.mod
scripts/aws/go.sum
scripts/aws/kubernetes-cluster.go
scripts/azure/destroy-old-clusters.sh
scripts/gke/destroy-old-clusters.sh
scripts/packet/destroy-old-clusters.sh
test/cloudtest/pkg/commands/main.go
test/cloudtest/pkg/providers/packet/packet_cleanup/tool.go
test/cloudtest/pkg/providers/packet/packet_provider.go
test/cloudtest/pkg/providers/providers.go
test/cloudtest/pkg/providers/shell/shell_provider.go

Desctroy clusters older then 4 hours when cloudtest run
Should help to avoid leaking clusters

Cleanup old clusters with cloudtest run

---

test/integration/usecase_deployment_order_test.go

Try to enable some broken deployment order tests

---

test/integration/recover_nse_heal_test.go

Add recover tests for vpp-agent nse/nsc

---

test/go.mod
test/go.sum

Update github.com/packethost/packngo to v0.2.0

---

scripts/logs_snapshot.sh

Condition for the exit for script logs_snapshot.sh looks complex.

logs_snapshot.sh script simplification

---

controlplane/pkg/services/client_connection_manager.go

Related to https://github.com/networkservicemesh/networkservicemesh/pull/2023
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0x9e5e98]
goroutine 267 [running]:
github.com/networkservicemesh/networkservicemesh/controlplane/pkg/services.(*ClientConnectionManager).isConnectionPending(...)
/home/user/go/src/github.com/networkservicemesh/networkservicemesh/controlplane/pkg/services/client_connection_manager.go:335
github.com/networkservicemesh/networkservicemesh/controlplane/pkg/services.(*ClientConnectionManager).UpdateXcon.func2(0xc000320780, 0xc95da0, 0xc000250460, 0xc95c60, 0xc0004392c0, 0xc9a320, 0xc00021aa80, 0xca14a0, 0xc0002503f0) …

Fix nil pointer exception on checking for connection pending

---

.circleci/config.yml
.circleci/dockerhub-image-remove
.mk/build.mk
controlplane/build.mk
forwarder/build.mk
k8s/build.mk
side-cars/build.mk
test/build.mk

Cleanup CI generated images from DockerHub

---

.circleci/config.yml

restore docker login command when pushing images to master repo

---

.circleci/config.yml

fix: CI generated images are not removed if testing fails

---

.mk/build.mk
.mk/monitor.mk
forwarder/build.mk
test/build.mk

Move common go build arguments to a variable

---

Release.md

Add release notes for v0.2.0

---

.circleci/config.yml

Used fixed CloudTest version v0.1-alpha

Used fixed CloudTest version v0.1-alpha

---

.cloudtest.yaml
docs/examples/vpp-icmp-example.md
scripts/nsc_ping_all.sh
test/applications/cmd/vppagent-nsc/main.go
test/shell/vpp_icmp_test.sh

vpp-icmp-responder test

---

controllers/sriov-controller/go.mod
controlplane/go.mod
forwarder/api/go.mod
forwarder/go.mod
k8s/api/go.mod
k8s/go.mod
sdk/go.mod
side-cars/go.mod
test/go.mod
utils/go.mod

v0.2.0 is on the release-0.2.0 branch, this should be distinct.

Change versions for networkservicemesh components in go.mod to v0.3.0

---

scripts/helm-nsm-uninstall.sh

Fix condition branches in helm-nsm-uninstall.sh 

---

.circleci/config.yml
.go-header.yaml
.license/README.md
.license/boilerplate.txt

Update license linter

---

.cloudtest/packet/create-kubernetes-cluster.sh
.cloudtest/packet/download-worker-images.sh
.cloudtest/packet/start-master.sh

Wait child process during cluster setup on packet

---

controlplane/pkg/nsmd/serviceregistry.go

Nsmd registry client: close connection  goroutine after timeout

---

README.md

Signed-off-by: Lucina Stricko <lucina@vulk.coop>
- adds PR Review Zoom call to README, held every Tuesday at 7:30-8 AM PT
- per NSM WG, an additional weekly zoom call has been added to review pull requests

add PR Review call to README

---

scripts/prepare-generate.sh

Do not use a master version of generation tools.

Fix versions of generation tools

---

.circleci/config.yml

Pull cloudtest with fix for https://github.com/networkservicemesh/cloudtest/pull/19

Use cloudtest from latest master

---

README.md

Zoom meeting room has been updated for PR Review weekly meeting to > https://zoom.us/j/562817928
Meeting room needs to match details on NSM calendar for 7:30am PT Networkservicemesh PR/Issue Review Weekly Meeting 
https://calendar.google.com/calendar/embed?src=iae5pl3qbf2g5ehm6jb2h7gv08%40group.calendar.google.com&ctz=America%2FLos_Angeles

Update PR Review Zoom call meeting room

---

.mk/aws.mk
.mk/packet.mk
applications/nsmrs/go.mod
scripts/aws/destroy-kubernetes-cluster.go
scripts/packet/destroy-old-clusters.sh

Fix broken cleanup scripts
Fix broken make scripts
- cleanup tool does not remove aws and packet clusters
- make k8-load-images does not work with aws and packet

Fix broken scripts

---

.cloudtest/azure.yaml

Temporarily disable testing on Azure

---

build/Dockerfile.vppagent-forwarder
forwarder/build.mk
forwarder/vppagent/conf/supervisord/telemetry.conf
forwarder/vppagent/pkg/vppagent/metrics_collector.go
test/build.mk
test/integration/basic_monitor_crossconnect_metrics_test.go

https://github.com/networkservicemesh/networkservicemesh/issues/1512

Use stats poller service for vpp-agent forwarder metrics

---

.cloudtest/executions/example-icmp-kernel-forwarder-wireguard.yaml
.mk/helm.mk
deployments/helm/nsm/templates/nsmgr.tpl
deployments/helm/nsm/values.yaml

https://github.com/networkservicemesh/networkservicemesh/issues/2126

Add wireguard helm example

---

side-cars/pkg/nsm-monitor/nsm-monitor.go

Signed-off-by: Dmitry Vlasov <dmitry.vlasov@xored.com>
Fix nil pointer in updateConnection from nsm-monitor.go
#2125

Update of TestUpdateConnectionOnNSEChange

---

forwarder/pkg/memifproxy/memif_proxy_test.go

Fixes case https://circleci.com/gh/networkservicemesh/networkservicemesh/121878

Fix: memif unit tests could affect each other on CI

---

.golangci.yml
sdk/client/clientlist.go
sdk/client/clientlist_test.go
sdk/common/configuration.go
sdk/common/connection.go

https://github.com/networkservicemesh/networkservicemesh/issues/2156

Fix: Annotations to connect to multiple NSEs connects to the same

---

applications/nsmrs/pkg/serviceregistryserver/cache.go

https://github.com/networkservicemesh/networkservicemesh/issues/2142

Expand logs:  BulkRegisterNSE registers endpoints with the wrong IP to NSMRS

---

.mk/k8s.mk
.mk/spire.mk
deployments/helm/nsm/charts/spire/templates/spire-namespace.tpl
docs/guide-helm.md
scripts/install-helm.sh
scripts/verify_vpn_gateway.sh
test/shell/crossconnect_monitor_test.sh
test/shell/icmp_test.sh
test/shell/interdomain_test.sh
test/shell/vpn_test.sh
test/shell/vpp_icmp_test.sh

v3 is an overall improvement over v2 and it seems right to switch to using it while the project's chart are completely compatible with v3.
major differences:
* no Tiller -> no need to install it (make helm-init)

Switch to Helm v3

---

.circleci/install-shellcheck.sh
scripts/nsc_ping_all.sh

Currently master failed with 
```
PS: Sorry for breaking your build :(
```

Fix install shellcheck script on CI

---

controlplane/pkg/nsmd/serviceregistry.go
k8s/pkg/proxyregistryserver/registry.go
scripts/gke/install-gcloud-sdk.sh
test/integration/floating_interdomain_few_clients_with_delay_test.go
test/integration/interdomain_floating_interdomain_monitor_test.go
test/kubetest/pods/nsmrs.go
test/kubetest/utils.go

https://github.com/networkservicemesh/networkservicemesh/issues/2142

Fix:  Interdomain NSM: BulkRegisterNSE registers endpoints with the wrong IP to NSMRS

---

pkg/tools/jaeger/jaeger.go
scripts/azure/create-aks-cluster.sh

We need to fix k8s version for azure clusters to avoid false-negative tests result.

Stabilize azure clusters

---

k8s/pkg/proxyregistryserver/discovery.go
test/integration/interdomain_single_node_test.go
test/kubetest/k8s.go
test/kubetest/pods/proxynsmd.go

This PR fixes bug 2169
https://github.com/networkservicemesh/networkservicemesh/issues/2169

fix: Interdomain NSM: client and endpoint on the same cluster node fails

---

pkg/tools/tools.go

Update GetCurrentNS: Use os.Stat to replace regular to get NS (#2176)

---

deployments/helm/nsm/charts/spire/templates/agent-daemonset.tpl
deployments/helm/nsm/charts/spire/templates/server-configmap.tpl
deployments/helm/nsm/charts/spire/templates/server-statefulset.tpl

Bump spire-agent and spire-server to 0.11.0

---

.cloudtest/azure.yaml
scripts/azure/create-aks-cluster.sh

fix: AKS testing on CI is not working

---

k8s/cmd/admission-webhook/const.go
test/kubetest/pods/common.go

Tune limits on containers introduced in #2188.
New limits:
|Container image  |Memory|   CPU|
|-----------------|-----:|-----:|
|`nsm-monitor`    |`15Mi`|`100m`|
|`coredns`        |`15Mi`|`100m`|
|`nsm-init`       |`20Mi`|`200m`|
|`nsm-dns-init`   |`15Mi`|`200m`|
Changes made: tuned down CPU limit for `nsm-init` and `nsm-dns-init` from `500m` to `200m`.
The CPU limits were so high, so k8s was occasionally unable to allocate CPUs on the CI.
Evidence: the following string found in these CI logs.
```
\"reason\":\"Unschedulable\",\"message\":\"0/2 nodes are available: 1 Insufficient cpu
```
* https://app.circleci.com/pipelines/github/networkservicemesh/networkservicemesh/9115/workflows/ef506fb2-e44a-488f-b9de-81a193ded542/jobs/122567
* …

Tune limits

---

sdk/endpoint/endpoint.go

Before to this PR, `NsmEndpoint` performed only a single `RegisterNSE` gRPC call during the execution of the `Start()` method. Considering that multiple `NsmEndpoint` couldn't share a single client socket, it was not possible to register multiple NSEs per single container.
This PR extends `NsmEndpoint` constructor to accept options. Multiple registrations could be specified using the new option `WithRegistrations`.
This change should be mostly backward compatible with the old code since only the optional variadic argument is added.
#2186

Multiple services per one endpoint

---

controlplane/pkg/nsmd/nsmd.go

This fix attempts to fix nsmd's client grpc fd leakage by reusing
the existing workspace when nsmdp requests for workspace with
socket id which was already available. It would fix #2189 issue.
Signed-off-by: Periyasamy Palanisamy <periyasamy.palanisamy@est.tech>

Reuse available workspace for new client

---

k8s/pkg/proxyregistryserver/discovery.go

https://github.com/networkservicemesh/networkservicemesh/issues/2202

fix: proxy-nsmd-k8s always filters for local NSEs

---

README.md

Update links for PR Review and community meetings

---

.circleci/config.yml
.cloudtest.yaml
pkg/probes/health/grpc_health.go
scripts/aws/create-kubernetes-cluster.go
scripts/azure/create-aks-cluster.sh

fix: nsmd gRPC health memory leakage

---

controlplane/pkg/nsm/nse_manager.go
controlplane/pkg/tests/nsmd_remote_test.go

Signed-off-by: Anatoly Loskutnikov <anatoly.loskutnikov@gmail.com>
#2230

Allow connect to remote endpoint with specified endpoint name

---

scripts/azure/create-aks-cluster.sh

#2243 
Signed-off-by: Artem Glazychev <artem.glazychev@xored.com>

issue #2243 Improving azure cluster stability
