networkservicemesh/networkservicemesh

Gopkg.lock
Gopkg.toml
vendor/github.com/ligato/cn-infra/core/event_loop.go

This pulls in the following fix [1]. This allows EventLoopWithInterrupt to
handle SIGTERM, meaning when NSM is run as a daemonset it will handle
SIGTERM when the daemonset is deleted.
[1] https://github.com/ligato/cn-infra/pull/268

Update to latest version of cn-infra

---

conf/sample/networkservice-daemonset.yaml

K8S API access can be restricted more based on API being used. This provides a starting point to deploy NSM in k8s cluster. Without this API access keeps failing and no CRDs can be created.
Signed-off-by: Prateek Gogia <prateekgogia@hotmail.com>

Allows pod to access API using in-cluster config, adding RBAC rule

---

conf/sample/networkservice.yaml

This fixes #66. We need to fix how we're creating channels as a part of
networkservice's in the yaml, because as it stands now, the errors
seen in #66 are a result of this not being setup correctly. This
addresses the issue by removing the channel from the sample yaml file.

Fix creating a networkservice

---

plugins/crd/crd_queue.go
plugins/crd/plugin_impl_crd.go

This commit closes #59.
This commit modifies how we process delete events from the queues.
Specifically, it does a few things:
* Saves off informers as a part of the CRD Plugin for use in queue
processing.
* Uses GetByKey() to get an object instead of directly using the sharedfactory
Lister function.
* GetByKey() allows us to determine if an item existed already, thus signaling
a deletion.
* Retries SplitMetaNamespaceKey() and GetByKey() errors up to five times to
handle transient errors.
With this change, the CRD code is now much more robust.

Correctly handle deletions from queues

---

.travis.yml
scripts/cluster-up-dind.sh
scripts/cluster-up-minikube.sh
scripts/cluster_common.bash
scripts/integration-tests

This will close issue #50.
This commit add some basic integration tests to verify that once the Docker
image is built we can create CRD resources in a minikube.

Add integration tests

---

.travis.yml
scripts/verify-codegen.sh

Closes #84
Run the verify-codegen.sh script to verify the generated code as a part
of the travis-ci runs.

Verify generated code during the build

---

Gopkg.lock
plugins/crd/plugin_impl_crd.go
plugins/crd/plugin_impl_crd_test.go
scripts/integration-tests

This PR adds unit tests for CRD validation. Since the actual validation is done by the server, it must run against a live k8s cluster as a result `--kube-config` parameter must be passed to test:
Example: `go test -v --kube-config=/Users/sbezverk/.kube/config`
These tests are targeted for new CI environment, where a live k8s cluster gets build.

Adding unit tests for crd validation

---

plugins/crd/plugin_impl_crd_test.go
scripts/integration-tests

Since CRD objects are created as a separate task in CI, removing their creation from Validation Unit Tests.

Optimizing crd validation

---

plugins/crd/crd_queue.go
plugins/crd/plugin_impl_crd.go

Commit 060979e introduced a problem when refactoring the workqueue
code. It solely used the NetworkService informer, which meant that
we were not properly dequeueing NetworkServerChannels or
NetworkServiceEndpoints. This commit corrects this bug.

Fix informer factory usage

---

nsmdp/nsmdp.go

Closes: #100 
After this fix:
```
Jun 18 13:21:56 kube-5.sbezverk.cisco.com kubelet[1356]: I0618 13:21:56.639130    1356 manager.go:290] Got registration request from device plugin with resource name "nsm.ligato.io/socket"
Jun 18 13:21:56 kube-5.sbezverk.cisco.com kubelet[1356]: E0618 13:21:56.640441    1356 endpoint.go:132] listAndWatch ended unexpectedly for device plugin nsm.ligato.io/socket with error EOF
```

device plugin name fix

---

plugins/crd/plugin_impl_crd.go

No need to use per-CRD informers when a single one works and makes
the code easier to read as a bonus.

Use a single shared informer for all CRDs

---

plugins/crd/crd_queue.go
plugins/crd/plugin_impl_crd.go
plugins/handler/plugin_api_handler.go
plugins/handler/plugin_impl_handler.go

This closes #115.
Create Events to store in the worker queue for CRD operations. This allows us to store metadata with each object, making it easier to eventually interface and interact with the object store.

Create and store events for CRD object operations

---

plugins/crd/plugin_impl_crd.go

We can pass in all the informers in a single call.

Optimize cache.WaitForCacheSync

---

cmd/nsm-init/nsm-init.go
conf/sample/nsm-client.yaml

This PR adds nsm-init container an ability to get client's desired NetworkServices from k8s ConfigMap.

Adding ConfigMap parsing code

---

plugins/objectstore/networkservice_test.go
plugins/objectstore/networkservicechannels.go
plugins/objectstore/networkservicechannels_test.go
plugins/objectstore/networkserviceendpoints.go
plugins/objectstore/networkserviceendpoints_test.go
plugins/objectstore/objectstore_api.go
plugins/objectstore/objectstore_plugin.go

This commit adds an objectstore backend for channels and endpoints,
including Create/Delete/List methods for each as well. The objectstore
will be complete after this commit, and can cache all CRD objects
for NSM clients to utilize.

Add channels and endpoints into the objectstore

---

flavors/netmesh/netmesh_flavor.go
plugins/crd/crd_queue.go
plugins/crd/crd_utils.go
plugins/crd/plugin_impl_crd.go
plugins/handler/plugin_impl_handler.go

Removing duplicated code in setting up informers and moving non controller related code into crd_utils.go
Also closes: #137 

Remove duplicated code in crd plugin

---

.travis.yml
Makefile

The following Makefile targets are defined:
* verify
* check
* docker-build
The idea is the ensure we run the same build commands in the Makefile as are
executed in the Travis CI builds. This simplifies the process of building
Network Service Mesh code and images for first time users.

Add a Makefile to ease building Network Service Mesh code and images

---

Makefile
build/nsm/docker/Test.Dockerfile

When trying to use the Makefile to build on a machine behind a proxy, it
was observed the docker build commands all failed. This commit adds support
for using a proxy with the docker build commands in the Makefile. It also
fixes an explicit usage of "wget" in the nsm Test.Dockerfile to use a proxy.

Add proxy support to docker build commands in the Makefile

---

Makefile

Closes #187
Specifically, this will export GOPATH, which is needed by the shell scripts
run by the `make verify` target.

Export Makefile variables so they can be used by shell scripts

---

plugins/logger/impl.go
plugins/logger/options.go

If logger.Plugin.init() produces an error before
setting the FieldLogger field, downstream consumers
can get a nil panic.

Fix for corner case which can throw nil panic

---

conf/sample/networkservice-daemonset.yaml
conf/sample/nse.yaml
plugins/finalizer/api.go
plugins/finalizer/finalizer_plugin.go
plugins/finalizer/finalizer_queue.go
plugins/finalizer/options.go
plugins/nsmcommand/options.go
plugins/nsmserver/nsmserver_client.go
plugins/objectstore/networkservice_test.go
plugins/objectstore/networkservicechannels.go
plugins/objectstore/networkservicechannels_test.go
plugins/objectstore/networkservices.go
plugins/objectstore/objectstore_api.go
plugins/objectstore/objectstore_plugin.go

Currently there is no any cleanup when pod providing nse channel goes away, same issue is with nsm client. This controller in  form of another plugin will watch for this event (label based) and attempt to clean up.
Since PR became kind of large, dataplane clean up for NSE will be in the next PR.

Adding a controller to watch for pod  delete event (control plane clean up fir NSE)

---

.travis.yml
.travis/update-docker.sh

This PR ensures our travis nodes are running the latest version of
Docker before we run tests on them.

Ensure we update docker to the latest version

---

plugins/crd/options.go
plugins/crd/plugin_impl_crd.go
plugins/finalizer/finalizer_plugin.go
plugins/finalizer/finalizer_queue.go
plugins/finalizer/options.go
plugins/handler/plugin_impl_handler.go
plugins/k8sclient/api.go
plugins/k8sclient/deps.go
plugins/k8sclient/docs.go
plugins/k8sclient/impl.go
plugins/k8sclient/options.go
plugins/k8sclient/options_test.go

This plugin provides access to rest.Config and kubernetes.Clientset
in a common location. Today, many plugins define their own usage of
these as follows:
k8sClientConfig *rest.Config
k8sClientset    *kubernetes.Clientset
This is inefficient as it replicates this code across many different
plugins.

Add a k8sclient plugin

---

.nsm.mk

For now, we should push images to Docker Hub each time we merge to master.
Eventually we'll want to do this based on tags or branches, but given the
velocity of development, I think it's prudent to push with each merge.

Push images to Docker Hub on each merge to master

---

.nsm.mk
.travis.yml
Makefile

If we're building from travis-ci, tag the images with ${COMMIT},
which comes from ${TRAVIS_COMMIT}.
Without this commit, the `docker push` commands were failing from travis-ci because they were expecting the image to be tagged with ${COMMIT}.

Conditionally tag the docker images with ${COMMIT}

---

.nsm.mk

In a Makefile, it turns out it's tricky to set environment variables in a
target and then use them. This was being done in .nse.mk by setting $REPO
to whatever repository was being worked on, and it was failing: it was
never set.
It turns out this is an unnecessary optimization, so simply removing this
should allow the `docker push` operations to succeed.

Correct environment variable usage when pushing docker images

---

.nsm.mk
.travis.yml

Move this into .travis.yml instead of in each `docker push` Makefile
target. This removes duplication, but more importantly these variables
need to be defined outside the Makefile targets themselves.

Change where the TAG variable is defined

---

.nsm.mk

This was preventing `docker push` from working for all repositories
because the Makefile targets it was incorrectly trying to run had
.PHONY entries but no actual entries.
*sigh*

Fix embarrassing spelling error in Makefile targets

---

.travis.yml
Makefile

Similar to the Ligato vpp-agent [1], add the dumping of a bunch of useful
information for each travis-ci run.
[1] https://github.com/ligato/vpp-agent/blob/pantheon-dev/Makefile#L217-L228

Dump more information for each travis-ci build

---

controllers/sriov-controller/dpapi-controller.go
controllers/sriov-controller/service-controller.go

Adding VF function was missing actual add to the map code, as a result number of VFs in the map was reported incorrectly. Deleting entries from configmap wilt `kubectl edit configmap blah` resulted the whole network service to be stopped advertising. This PR fixes this issue and add some robustness in terms of concurrent access of data structures.

Fixing add/delete multiple entries bug

---

.api_violations.report
pkg/apis/networkservicemesh.io/v1/openapi_generated.go
pkg/nsm/apis/common/common.pb.go
pkg/nsm/apis/dataplaneinterface/dataplaneinterface.pb.go
pkg/nsm/apis/dataplaneregistrar/dataplaneregistrar.pb.go
pkg/nsm/apis/dataplaneregistrar/dataplaneregistrar.proto
pkg/nsm/apis/netmesh/netmesh.pb.go
pkg/nsm/apis/nseconnect/nseconnect.pb.go
pkg/nsm/apis/nsmconnect/nsmconnect.pb.go
pkg/nsm/apis/pod2nsm/api.pb.go
pkg/nsm/apis/testdataplane/testdataplane.pb.go
plugins/dataplaneregistrar/dataplaneregistrar_reg.go
plugins/objectstore/objectstore_api.go
plugins/objectstore/objectstore_plugin.go

When an external dataplane controller finds itself unable to serve NSM requests, it will call UnRegister call so NSM will not waste time on it. Once this dataplane controller come back to its senses it will register with NSM again. 

Adding UnRegister api call

---

.circleci/config.yml

The plan is to use circle-ci as a test runner to hop over to packet.net
and run tests on real hardware. For now, this puts a template in to get
the hook to circle-ci. We'll want to replace this with the actual steps
to run on packet.net once it merges.

Add template circleci integration

---

.travis.yml
scripts/cluster-up-dind.sh
scripts/cluster-up-minikube.sh
scripts/integration-test-helpers.sh
scripts/integration-tests.sh
scripts/travis-integration-tests.sh

Closes #311
This updates the CI to use the latest minikube (v0.29.0) and kubernetes
(v1.12.0) for testing.
NOTE: I expect this to fail at the moment since the kubeadm bootstrapper seems to
have some issues here. Pushing this out to see if it fails the same way as it does
in my local environment.

Update the CI to use the latest minikube and kubernetes

---

scripts/ci-dind-images.sh
scripts/cluster-up-dind.sh

We're using kubeadm-dind-cluster now to run CI tests in travis-ci. This
means we first build the Docker images in the outer Docker, and then
spinup a Kubernetes cluster in the outer Docker, with it's own inner
Docker.
This PR ensures we're copying the images from the outer Docker into the
inner Docker of each Kubernetes node so we run tests against the freshly
built images rather than the ones from Docker Hub.

Copy images from outer to inner Docker

---

.api_violations.report
cmd/examples/nse/nse.go
pkg/apis/networkservicemesh.io/v1/openapi_generated.go
pkg/nsm/apis/common/common.pb.go
pkg/nsm/apis/dataplane/dataplane.pb.go
pkg/nsm/apis/dataplaneregistrar/dataplaneregistrar.pb.go
pkg/nsm/apis/netmesh/netmesh.pb.go
pkg/nsm/apis/nseconnect/nseconnect.pb.go
pkg/nsm/apis/nseconnect/nseconnect.proto
pkg/nsm/apis/nsmconnect/nsmconnect.pb.go
pkg/nsm/apis/pod2nsm/api.pb.go
pkg/nsm/apis/testdataplane/testdataplane.pb.go

Currently, there is no way to inform NSE about the interface name which the dataplane has programmed for the nsmclient/network service. This proto change adds a new message sent by NSM to  NSE with the interface name and corresponding network service. Based on this information NSE can start a listener or some other service routine on newly created interface.

Add grpc service to inform nse about interface name

---

.circleci/config.yml

Avoid build process going further to heavy cluster deploy phase in case of `make verify` failures

Add make verify to Circle CI sanity checks

---

.circleci/config.yml

packet-destroy as part of the packet-integraion-tests job
was slow and unstable, due to issue with pulling
the provision docker image from the remote_docker
being very very slow (sometimes taking 30 minutes, or
timing out).
This same docker image, when used as the basis for a standalone
job (as is done for packet-deploy) is zippy and reliable.
This patch breaks packet-destroy out into a separate job.
In the event that integration-tests fails, it will use
the CircleCI API to launch the packet-destroy job.
This is done by storing the /cncf/data needed in a cache
with key cncf-data-{{.Environment.CIRCLE_WORKFLOW_ID}}
and having the API set CIRCLE_WORKFLOW_ID in the packet-destroy
job to match.
This has been tested and works.

Make packet-destroy more stable

---

.circleci/config.yml

This is far from perfect, as it basically waits
10 minutes for packet-deploy to finish before triggering
packet-destroy.  I hate sleeps in tests... but its the best
we can do.
This has been tested:
1.  If the build is broken, cleanup happens correctly.
2.  If the build is broken *and* packet-deploy is broken,
the packet-destroy triggered by the broken build
does nothing, and reports success unless packet-deploy
has completed.
So the only available mode in which this doesn't behave well is:
packet-deploy succeeds more than 10 minutes after the build breaks.
In that case we can leak servers.
The additional drawback is that build fails will take a bit longer to report.

Add a cleanup step to build CircleCI Job

---

.circleci/config.yml
.travis.yml
scripts/circle-integration-tests.sh
scripts/dev-integration-tests.sh
scripts/dump_logs.sh
scripts/integration-test-helpers.sh
scripts/integration-tests.sh
scripts/travis-integration-tests.sh

Right now, if we break, the 'point of breakage' ends up
being buried behind all the log collection.
The log collection is epic.  This patch breaks log collection out
into a separate script:
./scripts/dump_logs.sh
And puts it into separate steps into TravisCI and CircleCI that *always*
collect logs (error or not).

Break out log collection to obvious seperate step in CI

---

dataplanes/vpp/pkg/nsmutils/nsm-utils.go
dataplanes/vpp/pkg/nsmvpp/nsm_vpp_xconnect.go

Current vpp-daemon implementation accepts namespaces in form of pid:xxxx only. This change makes it working with inode values provided for namespaces.

Make connection working with inode namespace parameters

---

scripts/vagrant/README.md
scripts/vagrant/scripts/load_images.sh

Check that /vagrant/images exists to avoid failure of the vagrant
provisioner when 'vagrant up' is run before nsm images are built

fix Vagrant README nits

---

scripts/vagrant/Vagrantfile
scripts/vagrant/scripts/install_docker.sh

Ubuntu is now providing docker 18.09 by default.
Kubeadm reports an incompatibility error which prevent k8s
to be installed in the Vagrant VM.

Vagrant: Install docker-ce 18.06

---

controlplane/pkg/nsmd/network_service_server.go
controlplane/pkg/nsmd/workspace.go

This causes each Workspace to be provided with MonitorConnectionService, reflecting
the connections between the Workspace and the nsmd.
It also allows each workspace to track its own connections, as the MonitorConnectionServer
does that in passing :)

Add local.MonitorConnectionServer to Workspace

---

controlplane/pkg/apis/remote/connection/constants.go
controlplane/pkg/apis/remote/connection/helpers.go
dataplane/vppagent/pkg/converter/remote_connection_converter.go
dataplane/vppagent/pkg/vppagent/vppagent.go

The remote VXLAN enablement was modelled based on the Kernel interface implementation form the local mechanism.
Tests are still TBD.

Enable the VXLAN Mechanism in the vpp-dataplane (#342)

---

k8s/cmd/nsmdp/nsmdp.go

This is best accomplished by inserting into NewNSMDeviceServer a call to WaitForPortAvailable to Wait until nsmd is responding before proceeding.
See #493

nsmpd waits for nsmd to be available

---

controlplane/pkg/nsmd/nsmd.go

This change enforce a proper order of events as described in #493
The proper order of events is:
1. Dataplane registers with nsmd
1. nsmd begins listening for incoming NSMD.RequestClientConnection(..) calls
This can be easily rectified in StartNSMServer by looping over a call to model.SelectDataplane() until it returns a non-nil value.

nsmd begins listening for incoming calls after data plane registers

---

controlplane/pkg/model/model.go
controlplane/pkg/nsmd/network_service_server.go
controlplane/pkg/selector/match_selector.go
controlplane/pkg/selector/round_robin_selector.go
controlplane/pkg/selector/selector.go

This implements an exact match when requesting a NSE selection.
Based on PR https://github.com/ligato/networkservicemesh/pull/537

controlplane: implement a simple Ednpoint selection. Implements 534

---

.circleci/config.yml
.docker.mk
.k8s.mk
controlplane/pkg/model/model.go
controlplane/pkg/tests/mode_test.go
docker/Dockerfile.crossconnect-monitor
k8s/cmd/crossconnect-monitor/crossconnect_monitor.go
k8s/conf/crossconnect-monitor.yaml
scripts/debug.sh
scripts/integration-tests.sh

1. crossconnect-monitor is packaged as pod, listening for K8s NSM registered and starting looking for cross-connect events happening.
2. packaged as pod and deployed to test configuration.
3. make k8s-crossconnect-monitor-logs could be used to take logs.

CrossConnect monitor tool

---

.k8s.mk
k8s/cmd/crossconnect-monitor/crossconnect_monitor.go
k8s/conf/crossconnect-monitor.yaml

The Cross Connect Monitor didn't really need the Node Name
and downward API pieces.  Also fixed some missing k8s-%-save rules
for it.

A bit of streamlining Cross Connect Monitor

---

examples/cmd/icmp-responder-nse/nse.go
examples/cmd/icmp-responder-nse/service.go
examples/cmd/vppagent-icmp-responder-nse/nse.go
examples/cmd/vppagent-icmp-responder-nse/service.go
k8s/conf/icmp-responder-nse.yaml
k8s/conf/vppagent-icmp-responder-nse.yaml

Implements #556 - Make IP address pools for icmp-responder-nse and vppagent-icmp-responser-nse configurable via Env variable

Make IP address pools configurable via Env variable

---

examples/cmd/vppagent-nsc/nsc.go

This ensures netNsInode tagging,
and thus showing up in skydive.

Fix vppagent-nsc to use NewMechanism

---

.k8s.mk

A wrong k8s-icmp-delete target is getting in the way.

Makefile: fix k8s-icmp-deploy

---

Makefile

We really need 'go' on the host mostly for checks nad CI/CD.
All the images are generated in Docker. There is no real need to
be noisy about the lack of go.

Makefile: don't make noise when go is not installed

---

Ubuntu.md
docs/CentOS.md
docs/OSX.md
docs/QUICK-START.md
docs/Ubuntu.md

Add separate instructions for CentOS, OSX and Ubuntu.

docs: split QUICK-START.md for different OS

---

.k8s.mk
.vagrant.mk
scripts/vagrant/README.md
scripts/vagrant/Vagrantfile

Use sshfs for mounting /vagrant directory.
Use generic/debian9 box that is compatible with libvirt
and generic/ubuntu1804 has resolver issues.

Allow using libvirt with vagrant

---

examples/cmd/icmp-responder-nse/complete.go
examples/cmd/icmp-responder-nse/nse.go
examples/cmd/icmp-responder-nse/service.go
k8s/conf/icmp-responder-nse.yaml

Use #572 extra prefixes for ICMP responder NSE.

Use #572 extra prefixes for ICMP responder NSE

---

examples/cmd/icmp-responder-nse/complete.go
examples/cmd/icmp-responder-nse/nse.go
examples/cmd/icmp-responder-nse/service.go
k8s/conf/icmp-responder-nse.yaml

This reverts commit 6c42abcab9a3d35b54b4aa7dbaa8248960559ac4.
It was causing breakage in master.  Apparently by issuing /32s 
to pods without providing correct 'glue' to make that work.

Revert "Use #572 extra prefixes for ICMP responder NSE (#645)"

---

utils/fs/fsutils.go

Check all /proc/* locations and do not exit if not pressent.

Check all /proc/* locations

---

pkg/tools/tools.go

As suggested in #660 this PR adds hostname to a service name in OpenTracing support.

Adds hostname to OpenTracing service name

---

controlplane/pkg/nsmd/network_service_server.go
controlplane/pkg/nsmd/nsmd_crossconnect_client.go
controlplane/pkg/remote/network_service_server/remote_network_service_server.go
controlplane/pkg/services/client_connection_manager.go
test/integration/death_handling_test.go

Bug was related to synchronization in nsmd. Sometimes it received CrossConnectEvent from dataplane before CrossConnect was saved to Model and ignored it.
Fix: save ClientConnection to Model before Request to dataplane. Cross-connect for that ClientConnection will be set later, when appropriate event from dataplane will be received.

Issue #669: Fix bug with cross-connect monitor

---

dataplane/vppagent/pkg/converter/kernel_connection_converter.go

GKE does not in its stock images have /dev/vhost-net available.
To get around this, we fall back to the slower veth pairs + AF_PACKET approach.

Adapt kernel_interface_converter to work in envs where /dev/vhost-net is unavailable.

---

docs/CentOS.md

Correcting document title to specify the instructions are for CentOS host

Correcting title for CentOS

---

controlplane/cmd/nsmd/nsmd.go
controlplane/pkg/apis/local/connection/helpers.go
controlplane/pkg/apis/local/networkservice/helpers.go
controlplane/pkg/apis/nsm/nsm.go
controlplane/pkg/apis/remote/connection/helpers.go
controlplane/pkg/apis/remote/networkservice/helpers.go
controlplane/pkg/model/model.go
controlplane/pkg/nsm/endpoint_client.go
controlplane/pkg/nsm/nse_requests.go
controlplane/pkg/nsm/nsm.go
controlplane/pkg/nsm/nsm_heal.go
controlplane/pkg/nsm/nsm_mechanims.go
controlplane/pkg/nsm/remote_nsm_client.go
controlplane/pkg/nsmd/network_service_server.go
controlplane/pkg/nsmd/nsmd.go
controlplane/pkg/nsmd/nsmd_crossconnect_client.go
controlplane/pkg/nsmd/workspace.go
controlplane/pkg/remote/network_service_server/remote_network_service_server.go
controlplane/pkg/services/client_connection_manager.go
controlplane/pkg/tests/nsmd_crossconnect_client_test.go
controlplane/pkg/tests/nsmd_local_test.go
controlplane/pkg/tests/nsmd_remote_test.go
controlplane/pkg/tests/nsmd_test_utils.go
test/integration/monitor_crossconnect_test.go
test/kube_testing/k8s.go

Right now NSMD select just one NSE and in case of error doesn't select another one, we need to update code base to support this scenarios.
* Unify local and remote NSMs codebase to be one generic NSM implementation with two concrete for local/remote request handling.
* Add basic Auto heal functionality
* Fix unit tests

Implement NSMD check for NSE troubles and initial Auto healing operation

---

scripts/terraform/packet.tf

Packet.net Terraform provider recently switched to
the public IPv4 address being .1 not .0:
https://github.com/terraform-providers/terraform-provider-packet/pull/89
We were getting the address from:
network.0.address
this patch switches to access_public_ipv4 to fix it.
Switching to using a more deterministic mechanism to get Packet.net public IPv4 address to restore the functioning of CI (which has been failing on master).
Since this is a fix to CI, passing CI is testing this fix.

Fix public IP for Packet.net Terraform Provider

---

.k8s.mk

Remove the use of `DEPLOY_ICMP_VPP` from the general `DEPLOYS` target.
In an effort to build only the infra components, noticed that `DEPLOY_ICMP_VPP` was still present due to its occurrence both in `DEPLOY_ICMP` and `DEPLOYS`.
Triggered a build with and one without the ICMP example commenting out the DEPLOY_ICMP

Remove duplicate use of DEPLOY_ICMP_VPP

---

examples/cmd/nsc/nsc.go
sdk/client/client.go

The SDK client does have wrong behaviour after 10 iterations of retries to connect.
This patch adds a proper error handling in SDK/client for the case where all iteration retries failed.
A wrong behaviour and crash were observed while the client runs in a volatile environment.
NSC for example just continues and finished its operation even though the Connect failed.

Handle Client connection failure

---

.integration.mk
Makefile

Add a make target to run the integration tests on a locally configured cluster.
Today we use packet to run the integration testing. However one might want to be able to run these on
an arbitrary Kubernetes deployment.
This PR adds:
* `make k8s-integration-tests` -> run all integration tests on the configured Kubernetes cluser
* `make k8s-integration-%-test` -> run a single test, e.g `make k8s-integration-TestDeployPodIntoInvalidEnv-test`
We might want to put specify these new targets in the developer's docs.

Adding a target to run local integration tests

---

controlplane/pkg/nsm/nse_requests.go
controlplane/pkg/nsm/nsm.go
controlplane/pkg/nsmd/network_service_server.go

Workspace name was not specified for Local NSE connections.
It is required by memif.

Workspace name was not specified for memif connections properly.

---

.circleci/config.yml
.docker.mk
k8s/cmd/nsmd-k8s/main.go
test/integration/vpn_test.go
test/kube_testing/crds/networkservice.go
test/kube_testing/k8s_exec.go.go
test/kube_testing/pods/vpn-gateway-nse.go
test/kube_testing/pods/vppagent-firewall-nse.go

Add the `secure-intranet-connectivity` integration test.
This also adds testing capabilities to describe NetworkService enabling more complex real-world scenarios.
This test exercises NSM's capabilities to implement NetwrokService CRD, link a couple of Endpoints and create complex deployments. It is setting a direction of increasing the number of integration tests and their coverage.
Currently only the simplest single host scenario is enabled. The remote test can be run  by defining `VPN_REMOTE_ENABLED`.
An option to run is:
VPN_REMOTE_ENABLED=1 make k8s-integration-TestVPN*-test

Adding VPN integration tests

---

.circleci/config.yml
.docker.mk
test/integration/nsmd_test_utils/test_utils.go
test/kube_testing/pods/alpine.go
test/kube_testing/pods/icmp_responder.go
test/kube_testing/pods/nsc.go
test/kube_testing/pods/nsmd.go
test/kube_testing/pods/versioning.go
test/kube_testing/pods/vppagent-firewall-nse.go
test/kube_testing/pods/vppagent_dataplane.go

The current CircleCI script invokes the `docker-%-push` target with TAG and BUILD_TAG refering
to the CircleCI SHA. The target then pushes to dockerhub but without specifying the image tag to push which results in pushing virtually all new images under the same name. The one that is not tagged gets an automatic :latest from dockerhub.
We get :latest images in dockerhub build out of PR branches. That is fundamentally wrong.
These images should be generated out of `master` branch only.
Need the CircleCI to test.

Fix CI push :latest to docker hub

---

.circleci/config.yml

Shift push-latest from rebuilding the images to simply pulling, tagging, and re-pushing.
No need to rebuild the images, we can just push them.

Make push-latest simpler

---

.circleci/config.yml
controlplane/cmd/nsmd/nsmd.go
controlplane/pkg/nsmd/probes.go
dataplane/vppagent/cmd/vppagent-dataplane.go
dataplane/vppagent/pkg/vppagent/probes.go
docs/spec/PROBES.md
k8s/conf/nsmd.yaml
k8s/conf/vppagent-dataplane.yaml
test/kube_testing/pods/nsmd.go
test/kube_testing/pods/vppagent_dataplane.go

Add liveness/readiness probes for nsmd and vppagent-dataplane. The changes consist of:
* Created `/liveness` and `/readiness` HTTP handlers for both components
* Each component sets specific flags stating if its dependencies initialized okay or not
* Updated the `kube-testing` description files to take into account these changes
* Updated the Kubernetes configuration files to enable liveness/readiness probing
Related to #711

Add liveness/readiness probes for nsmd and vppagent-dataplane

---

controlplane/pkg/apis/local/connection/mechanism_helpers.go
utils/fs/fsutils.go

Dataplane chose the first netns by inode that it finds in /proc directory. But sometimes it can be init-container's netns, so vppagent can't resolve it later. Now it checks that netns located in pause-container process directory.
[Issue #725](https://github.com/networkservicemesh/networkservicemesh/issues/725)

Bug: Add check of cmdline during resolving namespace by inode

---

k8s/cmd/admission-webhook/main.go
k8s/conf/admission-webhook-cfg.yaml

Signed-off-by: Andrey Platov <andrey@xored.com>
Initial admission webhook implementation mutate `deployments` only. This PR also let mutate `pods`

Admission Webhook handle pods

---

.integration.mk
.k8s.mk
docs/QUICK-START.md
k8s/cmd/nsmd-k8s/main.go
k8s/conf/crd-networkserviceendpoints.yaml
k8s/conf/crd-networkservicemanagers.yaml
k8s/conf/crd-networkservices.yaml
scripts/prepare-circle-integration-tests.sh
test/integration/nsmd_k8s_test.go
test/kube_testing/k8s.go

This creates NSM CRD bundle yaml and removes CRD generation and cleanup from code
Closes #736
```
$ make k8s-icmp-delete
$ make k8s-vpn-delete
$ make k8s-save
$ make k8s-infra-deploy
$ make k8s-icmp-deploy
$ make k8s-vpn-deploy
$ make k8s-check
```
Check CRDs are updated
```
$ kubectl get crd
NAME                                            CREATED AT
networkserviceendpoints.networkservicemesh.io   2019-02-13T12:18:43Z
networkservicemanagers.networkservicemesh.io    2019-02-13T12:18:44Z
networkservices.networkservicemesh.io           2019-02-13T12:18:43Z
```

Move CRDs to yaml

---

.circleci/config.yml
.integration.mk
scripts/prepare-circle-integration-tests.sh
scripts/run_integration_tests.sh
test/integration/const.go
test/integration/death_handling_test.go
test/integration/monitor_crossconnect_test.go
test/integration/nsc_deploy_test.go
test/integration/nsc_icmp_configuration_test.go
test/integration/nse_dataplane_heal_test.go
test/integration/nse_heal_test.go
test/integration/nsmd_deploy_test.go
test/integration/nsmd_k8s_test.go
test/integration/nsmd_test_utils/test_utils.go
test/integration/vpn_test.go
test/kube_testing/k8s.go
test/kube_testing/pods/nsmd.go
test/kube_testing/pods/utils.go
test/kube_testing/pods/vppagent_dataplane.go

Improve testing infrastructure for faster testing and fixing tests.
Integration tests are failing strangely. We add the following patches to improve:
* Mark broken tests and enable them with BROKEN_TESTS_ENABLED
* Disable forcing image pull
* Use global timeout definitions
* Increase gotest timeout to 30m
* Lower liveness/readiness probe times to speedup testing

tests integration: improve testing infrastructure and disable failing tests

---

k8s/cmd/admission-webhook/main.go
k8s/cmd/nsmdp/nsmdp.go
k8s/conf/icmp-responder-nse.yaml
k8s/conf/vpn-gateway-nsc.yaml
k8s/conf/vpn-gateway-nse.yaml
k8s/conf/vppagent-firewall-nse.yaml
k8s/conf/vppagent-icmp-responder-nse.yaml
k8s/conf/vppagent-nsc.yaml
test/kube_testing/pods/icmp_responder.go
test/kube_testing/pods/nsc.go
test/kube_testing/pods/vpn-gateway-nse.go
test/kube_testing/pods/vppagent-firewall-nse.go

`nsm.ligato.io` is an outdated name of the location of the NSM client socket, historically comming from the old organisation name. Changing to `networkservicemesh.io/socket` to keep it up-to-date and more descriptive
Closes #755
All tests are passing locally with `make k8s-integration-tests`

Replace nsm.ligato.io/socket

---

k8s/pkg/registryserver/nse.go
k8s/pkg/registryserver/registry_cache.go
k8s/pkg/registryserver/resource_cache/ns_cache.go
k8s/pkg/registryserver/resource_cache/nse_cache.go
k8s/pkg/registryserver/resource_cache/nse_cache_test.go
k8s/pkg/registryserver/resource_cache/nsm_cache.go
k8s/pkg/registryserver/resource_cache/resource_cache.go
k8s/pkg/registryserver/server.go
test/integration/nsmd_k8s_test.go
test/integration/nsmd_test_utils/test_utils.go

Implement caches for the following custom resources: `NetworkService`, `NetworkServiceEndpoint`, `NetworkServiceManager`. Each resource cache listens k8s-registry using `Informer` as well as handles `Add(...)` or `Delete(...)` requests from `nsmd-k8s`

Implement cache for registry

---

.circleci/config.yml
controlplane/pkg/apis/nsm/nsm.go
controlplane/pkg/model/model.go
controlplane/pkg/nsm/nsm.go
controlplane/pkg/nsm/nsm_heal.go
controlplane/pkg/prefix_pool/prefixpool.go
controlplane/pkg/prefix_pool/prefixpool_test.go
dataplane/vppagent/pkg/converter/acl_converter.go
dataplane/vppagent/pkg/converter/memif_interface_converter.go
dataplane/vppagent/pkg/converter/memif_interface_converter_test.go
dataplane/vppagent/pkg/converter/remote_connection_converter.go
examples/cmd/vppagent-firewall-nse/vppagent.go
examples/cmd/vppagent-icmp-responder-nse/vppagent.go
examples/cmd/vppagent-nsc/vppagent.go
test/kube_testing/pods/jaeger.go

The changes consist of adding another check in the Circle CI configuration file to run a `go fmt` check and fail the build if it finds something that is not compliant.
The first commit is with the changes related to enabling that kind of check in the CI configuration and the second applies the result from running a `go fmt ./... or make format` locally.
**Update:**
Thought that it would be useful to add an additional `golint` run(not breaking the build if errors are found though).
Using `go fmt` makes the code easier to read and write and overall it helps to keep it in better shape.
Also most of the IDEs already have `go fmt` plugins that run upon saving which forces having the content of the file formatted.

Enforce build to fail if code is not go fmt compliant

---

.github/ISSUE_TEMPLATE.md
.github/ISSUE_TEMPLATE/bug.md
.github/ISSUE_TEMPLATE/spec.md

* Add a Github issue template to ease the creation
* Leverage Github's support for multiple templates
* When creating an issue, the user will choose if it's a bug or a spec related and so it will be redirected to the corresponding template.
Alternative solutions:
* Decide if it makes more sense to have everything in a single template and let the user refactor the content by itself.

Create Github issue templates for both "spec" and "bug" use-cases

---

dataplane/vppagent/build/Dockerfile.vppagent-dataplane
dataplane/vppagent/cmd/vppagent-dataplane.go
dataplane/vppagent/pkg/vppagent/egress_interface.go
dataplane/vppagent/pkg/vppagent/server.go
dataplane/vppagent/pkg/vppagent/vppagent.go
docker/Dockerfile.vppagent-firewall-nse
docker/Dockerfile.vppagent-icmp-responder-nse
docker/Dockerfile.vppagent-nsc
k8s/conf/vppagent-dataplane.yaml

This temporarily involves switching to edwarnicke/vpp-agent:v1.8.1 images
while the ligato team spins new updates with fixes in vpp to workaround
a kernel issue.
The basic kernel issue hit was this:
When running in hostNetwork:true, mmap for Hugepages returns without an error
(even though no Hugepages are available to be mmaped) and then the kernel
throws a SIGBUS when we try to use them.  This should *never* happen, but
does.  To work around it, we employ an alternate means to detect that
we don't actually have the pages involving mincore.

Convert to using hostNetworking:true

---

.mk/docker.mk

Currently, docker builds will not fail, because the make rule
was swallowing the failure and returning exit code 0.

Make docker build failures actually fail.

---

controlplane/pkg/nsmd/nsmd.go

nsmd was listening on the socket for nsmdp requests...
but then went and did a bunch of other stuff before having
the grpc ClientAPI Serve on that socket.  This led to a race
condition.

Fix race condition in nsmd/nsmdp startup.

---

controlplane/pkg/tests/nsmd_remote_test.go
sdk/endpoint/composite/ipam.go

IpamCompositeEndpoint was not properly excluding IPv6 loopback addresses from the IP Neighbors.  Since those addresses are on loopbacks, and loopbacks have no HW addresses, IPNeighbors without HW addresses were being sent and broke the Dataplane.

Fix IPAM to properly handle IPv6 Loopbacks

---

.mk/k8s.mk
.mk/kind.mk
docs/guide-kind.md
scripts/kind.yaml

K8s in Docker is a standard way to run K8s tests. We use this tool
here as an alternative cluster provider. Kind is lighter than bringing
up full VMs.
The setup consists of master and 2 nodes. It successfuly runs
make k8s-integration test, so can be used in the CI.
`kind` can help us have a simpler and lighter weight development environment. We coudl even consider it to become part of our CI.
The `vagrant` environment is complex, slow and resources hungry. Kind provides lighter means to have Kubernetes, depending just on a simple Docker installation.

Adding initial support for kind.sigs.k8s.io

---

dataplane/impl/dataplaneregistrarclient/dataplaneregistrarclient.go

Fix initial dataplane connection delay if NSMD is not start enough.

Fix delay with dataolane startup connect to NSMD

---

.mk/docker.mk
dataplane/vppagent/build/Dockerfile.vppagent-dataplane
docker/Dockerfile.vppagent-firewall-nse
docker/Dockerfile.vppagent-icmp-responder-nse
docker/Dockerfile.vppagent-nsc

https://github.com/networkservicemesh/networkservicemesh/pull/818
Closed by my mistake - apologize for inconvienence and thanks for your help.
Signed-off-by: Stanislav Chlebec <stanislav.chlebec@pantheon.tech>
Where the docker image is used ligato/vpp-agent in different Dockerfiles it was replaced by parameter.
The parameter is going to be set up in the file .mk/docker.mk 
Parameter VPP_AGENT is used to define proper docker image according to detected platform x86_64 or aarch64
This change is required if we want to have docker building process on ARM64 platform executed by command: make k8s_save
It should be somewhere mentioned where is the point where it is possible to change version of ligato/vpp-agent docker image

parametrize docker image ligato/vpp-agent to satisfy also ARM64 platform

---

controllers/sriov-controller/README.md
controllers/sriov-controller/sriov-client.yaml
controllers/sriov-controller/sriov-controller.yaml
deployments/helm/icmp-responder/templates/icmp-responder-nse.tpl
deployments/helm/icmp-responder/templates/nsc.yaml
deployments/helm/nsm-monitoring/templates/crossconnect-monitor.tpl
deployments/helm/nsm-monitoring/templates/skydive.tpl
deployments/helm/nsm/templates/cluster-role-binding.yaml
deployments/helm/nsm/templates/nsmgr.tpl
deployments/helm/nsm/templates/vppagent-dataplane.tpl
deployments/helm/vpn/templates/vpn-gateway-nsc.tpl
deployments/helm/vpn/templates/vpn-gateway-nse.tpl
deployments/helm/vpn/templates/vppagent-firewall-nse.tpl
deployments/helm/vpp-icmp-responder/templates/vppagent-icmp-responder-nse.tpl
deployments/helm/vpp-icmp-responder/templates/vppagent-nsc.tpl
k8s/conf/cluster-role-binding.yaml
k8s/conf/crossconnect-monitor.yaml
k8s/conf/debug/nsmgr-debug.yaml
k8s/conf/icmp-responder-nse.yaml
k8s/conf/nsc.yaml
k8s/conf/nsmgr.yaml
k8s/conf/skydive.yaml
k8s/conf/vpn-gateway-nsc.yaml
k8s/conf/vpn-gateway-nse.yaml
k8s/conf/vppagent-dataplane.yaml
k8s/conf/vppagent-firewall-nse.yaml
k8s/conf/vppagent-icmp-responder-nse.yaml
k8s/conf/vppagent-nsc.yaml
scripts/vagrant/skydive.yaml

This moves `apiVersion` from `v1beta1` to `v1` for all resources for which `v1beta1` is old and updates changed configs to match the latest API requirements
Closes #830
Tested locally with infra, imp and vpn deploy

Update apiVersion to latest API

---

dataplane/vppagent/pkg/converter/kernel_connection_converter.go
test/integration/nsmd_test_utils/test_utils.go
test/integration/usecase_nsc_icmp_configuration_test.go
test/kube_testing/pods/nsmd.go
test/kube_testing/pods/vppagent_dataplane.go

Fix VPPAgent Dataplane VETH mode.
The veth devices are virtual Ethernet devices.  They can act as tunnels between network namespaces to create a bridge to a physical network device in another namespace, but can also be used as standalone network devices.

VPP Agent Dataplane VETH mode is not working

---

k8s/pkg/registryserver/nsm.go
k8s/pkg/registryserver/registry_cache.go
test/integration/basic_nsmd_k8s_test.go

If nsmd-k8s restarts, old info from registry will rewrite new actual info about NSM. 
Fix: even if there is NSM in cache, update will unconditionally happen.

Fix bug with lost update of NSM in registry

---

test/kube_testing/pods/vppagent_dataplane.go

Raise vpp-agent log level in integration tests
Set vpp-agent log level to `debug`
We need to get more details in vpp-agent logs to troubleshoot dataplane issues.

Raise vpp-agent log level

---

scripts/prepare-circle-integration-tests.sh
test/integration/nsmd_test_utils/test_utils.go
test/integration/usecase_nsc_icmp_configuration_test.go
test/kube_testing/k8s.go

Before that change Admission Webhook was pre-deployed via script
in order to be used by only two tests. This moves all related
resources to be created within the test methods
Closes #847

Move Admission Webhook test deployment to golang

---

scripts/vagrant/scripts/configureK8smaster.sh
scripts/vagrant/scripts/install_kubernetes.sh

The Vagrant environment is failing due to a lack of v1.14.0 support from the NSM side.
Until we resolve that, the k8s version is pinned to 1.13.4.

Vagrant setup: Pin K8s to 1.13.4 instead of latest(1.14.0) until we support it

---

docker/Dockerfile.vppagent-firewall-nse
docker/Dockerfile.vppagent-icmp-responder-nse
docker/Dockerfile.vppagent-nsc

Fixes #894
Supervisord needs to be run as PID 1 to receive kill signals from kubelet and forward them to the processes it manages. Once SIGTERM received, NSM endpoint will properly unregister themselves.

Run supervisord as process with PID 1

---

test/integration/basic_nsmdp_test.go
test/integration/recover_nse_nsm_heal_test.go
test/kube_testing/k8s.go

If you are deleting pod with Grace Period 0 - the Pod may not be terminated instantly.
It may return error next time, when nsmdp will try to allocate not freed resource.
Following tests are not stable:
- TestNSMDDP
- TestNSMDRecoverNSE
- TestNSMHealRemoteDieNSMD_NSE
With the fix test will wait while previous nsmd pod will be terminated before creating new one.

Fix nsmd pod deletion in tests (#860)

---

test/integration/nsmd_test_utils/test_utils.go
test/integration/recover_death_handling_test.go

We use ping as our main link probe tool. Alpine's ping "-A"
allows for the next packet to be sent as soon as the previous
arrives. That speeds the overal ping time.

CI: make ping faster

---

controlplane/pkg/model/model.go
controlplane/pkg/nsm/nsm.go
controlplane/pkg/nsmd/dataplanes.go
controlplane/pkg/nsmd/serviceregistry.go
controlplane/pkg/tests/nsmd_remote_test.go
controlplane/pkg/tests/nsmd_test_utils.go
controlplane/pkg/tests/test_dataplanes.go

Wait for dataplane mechanisms before using it
nsmd starts working with dataplane right after registration. I cause errors with missing mechanisms (issue #884)
Waiting for mechanisms configuration added.
Component test added.
Issue #884

Wait for dataplane mechanisms before using it

---

.circleci/config.yml
.circleci/destroy-cluster.sh
.circleci/provision.sh

Lates changes to CircleCI 2.1 yaml schema fail when invoking the API:
https://discuss.circleci.com/t/api-job-trigger-fails-on-2-1-circle-project/27010/11
Replace the `curl` invocation with the 2.1 commands.
We get dangling servers in Packet when the tests fail.

CI: replace curl API invocation with a command

---

test/integration/basic_nsmd_k8s_test.go

There is no `kubeadm-config` on GKE, AWS or Azure. Add check to skip `TestClusterConfig` on these clusters.

Skip TestClusterInfo on clusters without kubeadm-config

---

docs/spec/glossary.md

Moved the network manager domain section to the end of the different NSMgr descriptions
More sensible flow of definitions
Simple txt formatting

Updated the ordering of the NSMgr section of glossary

---

dataplane/pkg/memifproxy/memif_proxy.go
dataplane/pkg/tests/memif_proxy_test.go

Fix for issue  https://github.com/networkservicemesh/networkservicemesh/issues/926
This fix will close the memif_socket connection on getting stop request

Memif file socket descriptor is using on memif proxy closing

---

.circleci/config.yml
.dockerignore
build/Dockerfile.nsmd-k8s
controlplane/build/Dockerfile.nsmd
dataplane/vppagent/build/Dockerfile.vppagent-dataplane
dataplane/vppagent/build/Dockerfile.vppagent-dataplane-dev
docker/Dockerfile.admission-webhook
docker/Dockerfile.crossconnect-monitor
docker/Dockerfile.vppagent-firewall-nse
docker/Dockerfile.vppagent-icmp-responder-nse
docker/Dockerfile.vppagent-nsc
examples/build/Dockerfile.icmp-responder-nse
examples/build/Dockerfile.nsc
k8s/build/Dockerfile.nsmdp
scripts/go-mod-download.sh

Prevent infinite loop of `go mod download` attempts
In case of invalid/inaccessible go dependencies sanity-check will lust forever.  This PR limits a number of attempts. 
Prevent infinite loop of `go mod download` attempts

Limit dependencies download attempts

---

scripts/prepare-circle-integration-tests.sh
test/integration/basic_exec_test.go
test/integration/basic_k8s_version_test.go
test/kube_testing/k8s.go
test/kube_testing/rbac/cluster_roles.go

This moves the creation of roles to the golang code, allowing flexibility of how many and what types of roles to be created, as well as specifing different roles (or excluding them) for different tests. This also allows them to be configurable trough code
Blocker for merging #770

Implement RBAC in tests

---

.mk/vpp_agent.mk
dataplane/vppagent/build/Dockerfile.vppagent-dataplane
dataplane/vppagent/build/Dockerfile.vppagent-dataplane-dev
docker/Dockerfile.vppagent-firewall-nse
docker/Dockerfile.vppagent-icmp-responder-nse
docker/Dockerfile.vppagent-nsc

Cleanup unneeded kafka.conf deleteion.
Enable the VPN tests again.
The VPN usecase CI tests are disabled.

vpp update to v2.0.1

---

controlplane/pkg/nsmd/nsmd.go
controlplane/pkg/nsmd/workspace.go
test/integration/nsmd_test_utils/test_utils.go

This fix can solve problems when in new workspace exist outdated content from the previous session. A most potential problem that if in workspace exist .sock files than it's can throw error 'address already in use'

Cleanup workspace if exist content on workspace creation

---

test/integration/usecase_vpn_test.go
test/kube_testing/crds/networkservice.go

Since the VPN tests were disabled for a while, the Namespace PR #770 missed it while testing.
Fix CI.

test: fix VPN with namespace tests

---

.mk/integration.mk

Add separate make targets for the integration test groups for basic, usecase and recover.
Sometimes when testing you don't want to test against the whole `make k8s-integration-tests` suite or on the other hand against a single one.

Add separate make targets for the integration test groups

---

.mk/vagrant.mk
Makefile
docs/guide-kind.md
scripts/vagrant/Vagrantfile

The WORKER_COUNT can be set to control the number of k8s workers to deploy with vagrant.
We can then easily set the number of worker to 0 for development.

Set number of workers with venv

---

controlplane/pkg/nsm/nsm.go

Fixes: https://github.com/networkservicemesh/networkservicemesh/issues/1007
Signed-off-by: Bart Smykla <bsmykla@vmware.com>
If you tried to install nsm using helm chart and then install
some example (ie. icmp-responder) also with helm,
nsmd was panicking because of nil pointer of resolution
related to networkServiceManager.excludedPrefixes.
It was probably related with some synchronisation issues
(some things should be deployed first, before other,
which was not forced by helm).
I fixed it by initializing new NetworkServiceManager
with empty excludedPrefixes immediately.
Installing `icmp-responder` or other examples via helm was crashing. It should fix the issues related to that.

Fixed nil pointer dereference problem when installing with helm

---

.mk/vagrant.mk

https://github.com/networkservicemesh/networkservicemesh/pull/1001 improved bash script for deploying images for nodes worker 1...n. 
But this script doesn't run on mac. For example
```
users-iMac:networkservicemesh user$ make vagrant-admission-webhook-load-images
/bin/bash: -c: line 1: syntax error: unexpected end of file
make: *** [vagrant-admission-webhook-load-images] Error 2
```

Fix vagrant-%-load-images for mac users

---

dataplane/pkg/common/egress_interface.go
dataplane/vppagent/pkg/vppagent/vppagent.go

Configure arp entries for vpp
Signed-off-by: Artem Belov <belov3004@gmail.com>
Add system arp entries to vppagent transaction
AWS needs configured arp entries to reach gateway

Add arp entries to vppagent transaction

---

k8s/pkg/registryserver/registry_cache.go
k8s/pkg/tests/registry_cache_test.go

After last merges, we have a couple of failing tests.
Root cause: PR #1003 has added regression which has been covered by PR #989

Fix failing tests after last merges

---

.mk/vagrant.mk

The forgotten "-c" was preventing new docker images to be uploaded to vagrant workers

Fix to be able to load images to vagrant workers

---

test/integration/basic_dataplane_standalone_test.go
test/integration/basic_excluded_prefixes_test.go
test/integration/basic_exec_test.go
test/integration/basic_k8s_version_test.go
test/integration/basic_memif_test.go
test/integration/basic_monitor_crossconnect_metrics_test.go
test/integration/basic_monitor_crossconnect_test.go
test/integration/basic_namespace_test.go
test/integration/basic_nsc_deploy_test.go
test/integration/basic_nsmd_deploy_test.go
test/integration/basic_nsmd_deploy_time_test.go
test/integration/basic_nsmd_k8s_test.go
test/integration/basic_nsmdp_test.go
test/integration/bench_connection_test.go
test/integration/recover_death_handling_test.go
test/integration/recover_nse_dataplane_heal_test.go
test/integration/recover_nse_heal_test.go
test/integration/recover_nse_nsm_heal_test.go
test/integration/recover_remote_nse_nsm_heal_test.go
test/integration/usecase_nsc_icmp_configuration_test.go
test/integration/usecase_vpn_test.go
test/kube_testing/k8s.go
test/kube_testing/rbac/cluster_roles.go

This PR moves the `PrepareDefault` code as part of the `NewK8sWithoutRoles` which simplifies the integration test setup and ensures test integrity especially when run locally.
Issue #999.

Fix integration failing roles

---

controlplane/pkg/nsmd/serviceregistry.go
k8s/cmd/nsmd-k8s/main.go
k8s/pkg/registryserver/registry_cache.go
k8s/pkg/registryserver/resource_cache/ns_cache.go
k8s/pkg/registryserver/resource_cache/nse_cache.go
k8s/pkg/registryserver/resource_cache/nsm_cache.go
k8s/pkg/registryserver/server.go
k8s/pkg/tests/registry_cache_test.go
test/integration/basic_nsmd_k8s_test.go

Add fetching real k8s-registry state before starting cache
TestLostUpdate is not stable

TestLostUpdate stabilization

---

controlplane/pkg/nsm/nsm_prefix_collector.go

Fix empty exclude prefix fault 
Skip empty subnets on prefix pool formation
icmp-responder returns fault on AWS cluster. Cause of the fault is request from nsmd with empty pod subnet.

Fix empty exclude prefix fault 

---

.circleci/config.yml

Push latest vppagent-firewall-nse on circleci success build
Add vppagent-firewall-nse to docker-push-latest circleci job
Networkservicemesh docker hub does not contains latest vppagent-firewall-nse image.

Push latest vppagent-firewall-nse on circleci success build

---

.circleci/config.yml
controlplane/pkg/nsm/nsm.go
controlplane/pkg/tests/restore_state_test.go
test/integration/basic_nsmd_deploy_restart_test.go
test/integration/nsmd_test_utils/test_utils.go
test/kube_testing/k8s.go

1. Fixes one part of issue #919.
2. Enable execution of all tests.
3. Collect previous logs if container restarts on CI tests.

Fix restart of nsmd in case of RestoreConnection and add previous container log retrieval.

---

k8s/conf/icmp-responder-nse.yaml
k8s/conf/vpn-gateway-nse.yaml

The command used in k8s deployments need to be in an array, not a single string

Fix command value in k8s deployments

---

.circleci/config.yml
scripts/install-kubectl.sh

Do not fix the `kubectl` version in our test scripts, use the latest stable instead.
Just stay up with the current version.

ci: always install latest kubectl

---

.mk/vagrant.mk

Clean the old, unnecessary images before loading the new ones.
When loading new images to a node, the old ones are renamed and left there consuming space.

Clear leftover copies of docker images in Vagrant

---

test/integration/nsmd_test_utils/test_utils.go
test/integration/recover_death_handling_test.go
test/kube_testing/k8s.go

Issue https://github.com/networkservicemesh/networkservicemesh/issues/1081 needs additional check to figure out whether the whole node is unavailable or api server only

Checking availability of k8s api server in case of error

---

.circleci/cleanup-aws.sh
.circleci/config.yml
scripts/aws/destroy-kubernetes-cluster.go

AWS cluster destroy optimization
- Delete Kubernetes services before deleting cluster to allow resources to be properly released
- Remove AWS network interfaces first on EKS nodes deletion fail
AWS cluster returns DELETE_FAILED status if resources are not properly released #1101

AWS cluster destroy optimization

---

test/integration/basic_nsmd_k8s_test.go
test/integration/nsmd_test_utils/test_utils.go

Sometimes NSE can't start because of:
```
time=\"2019-05-16T19:39:01Z\" level=fatal msg=\"unable to register endpoint rpc error: code = Unknown desc = attempt to pass through from nsm to upstream registry failed with: rpc error: code = Unavailable desc = transport is closing\"
```

Move waiting for nsmd-k8s to SetupNodes

---

.golangci.yml

Disable goimports linter
Linter returns an error even after goimports (no changes required)

Disable goimports linter

---

k8s/pkg/registryserver/discovery.go
k8s/pkg/registryserver/nse.go
k8s/pkg/registryserver/registry_cache.go
test/integration/basic_nsmd_k8s_test.go

Since k8s-registry doesn't support transactions and doesn't have kind of *createOrUpdate* method we can't atomically figure out resource existence and call appropriate (create/update) method. That's why we always can get error. I provided additional attempts during error handling

Add infinity number of attempts for create/update NSM

---

k8s/conf/skydive.yaml

Switch to the official skydive docker image with the NSM probe
The NSM probe is now included in skydive

Skydive: switch to the official docker image

---

k8s/cmd/nsmdp/nsmdp.go
test/integration/nsmd_test_utils/test_utils.go
test/integration/recover_remote_nse_nsm_heal_test.go
test/integration/usecase_vpn_test.go

Seems like there is no guarantee that kubelet immediately call ListAndWatch. Now wait only registration of nsmdp.
https://circleci.com/gh/networkservicemesh/networkservicemesh/52401

Waiting for start of nsmdp instead of waiting for ListAndWatch calling

---

test/integration/basic_nsmd_deploy_restart_test.go
test/kubetest/k8s.go
test/kubetest/utils.go

Adds `K8s::WaitLogsContainsRegex()` and replaces:
```
k8s.WaitLogsContains(nsmd, "nsmd", "NSM gRPC API Server: [::]:5001 is operational", timeout)
```
With:
```
k8s.WaitLogsContainsRegex(nsmd, "nsmd", "NSM gRPC API Server: .* is operational", timeout)
```
Issue #1161

Add K8s::WaitLogsContainsRegex()

---

test/kubetest/k8s.go

Add timeout for retrying to get logs after failure
Issue #1178

Add timeout for retrying to get logs after failure

---

dataplane/vppagent/pkg/converter/kernel_connection_converter.go

Both ends of the VETH pair were assigned with the same IP address
Some of the IPv6 tests were failing sporadically due to a strange race condition caused by the fact that we assign the same IP address on both ends of the VETH pair. 
This was causing the IPv6 interface to stay in a `tentative` and `dadfailed` state.
The solution is to assign an address only to the VETH end that will be used in the container.
Related to https://github.com/networkservicemesh/networkservicemesh/issues/1191

Fix dadfailure when configured with IPv6

---

.circleci/config.yml

Extend timeout for AWS destroy on failed tests
Extend timeout for AWS destroy on failed tests
#1198

Extend timeout for AWS destroy on failed tests (#1198)

---

OWNERS.md

Include Andrey Sobolev to owners.md file.

Include ASobolev to owners.md file

---

controlplane/pkg/monitor/monitor_client.go
controlplane/pkg/nsmd/nsmd_crossconnect_client.go

Add `nil` check for event receiving in `nsmd_crossconnect_client`.
Sometimes `monitorClient.EventChannel()` is getting closed at the same time with last error sent in `monitorClient.ErrorChannel()` and `select` breaks on event channel.
```
select {
case <-ctx.Done():
logrus.Infof(logFormat, name, "Removed")
return nil
case err = <-monitorClient.ErrorChannel():
...
case event := <-monitorClient.EventChannel():
...
}
```
https://circleci.com/gh/networkservicemesh/networkservicemesh/65816

Add nil check for received event

---

dataplane/vppagent/pkg/converter/kernel_connection_converter.go

Plus make the supplied routes global and not LINK local
Make sure that when the vpp-agent injects the interfaces it also sets a GW for the supplied routes. Also, the routes are not really Link Local in the broader sense. The patch is inspired by the memif converter approach to routes.
When a Linux (kernel) client get its routes it does not have a GW for them. Make that GW to be the DST IP in the link, effectively the endpoint.

Make kernel interface converter have a GW

---

.mk/k8s.mk

Cleanup `icmp-responder` networkservice on `make k8s-icmp-responder-nse-delete`
Issue #1123

Cleanup icmp-responder networkservice on k8s-icmp-responder-nse-delete

---

k8s/conf/vppagent-icmp-responder-nse.yaml

closes #1301
The IPAddress in the vppagent-icmp-responder-nse yaml file must be a prefix
Fix the crash described in 1301

vppagent-icmp-responder-nse: Initialize the allocation pool correctly

---

test/cloudtest/pkg/commands/main.go

Wait for deleting cluster goroutine is finished before finish testing
AWS leaking resources #1306

Fix deleting testing clusters

---

sdk/vppagent/acl.go

Quick fix to put back the license header for the ACL composite that was removed in #1304

Put back the license header for ACL composite

---

.mk/k8s.mk
k8s/cmd/admission-webhook/utils.go
k8s/conf/admission-webhook.yaml

Also, set the ImagePullPolicy to PullIfNotPresent
Fixes #1342 
After the introduction of the new repo networkservicemeshci and the new methodology where we do not have "latest" the admission webhook is having issues deploying the right images for the init container.

Fix the name of init container by setting the proper env

---

.mk/k8s.mk

Fix k8s-admission-webhook-* to depend on nsm-init

---

test/cloudtest/pkg/commands/main.go
test/cloudtest/pkg/model/tests.go
test/cloudtest/pkg/utils/process.go

CloudTest should fail if finding go tests are failed.
Right now if some of tests was not able to be compiled, we are not able to find tests, so only logging to console about this was happened, and build was green, but this is not right,
CloudTest should fail build in case product are broken.

CloudTest should fail if test find are failed

---

test/applications/build/Dockerfile.test-common
test/applications/cmd/proxy-xcon-monitor/main.go
test/integration/basic_monitor_crossconnect_metrics_test.go
test/integration/basic_monitor_crossconnect_test.go
test/integration/recover_xcon_monitor_test.go
test/kubetest/monitor_utils.go

Create proxy monitor for crossconnects
There are several tests that somehow check `CrossConnectMonitor`. They forward 5001 port from nsmd and receive `CrossConnectEvent` directly from the monitor. 
But #737 introduces TLS securing of grpc connections. Certificates are issued by spire-agent based on pod's service account. That's why for simplifying events reading outside the cluster this PR introduces proxy-xcon-monitor. Proxy-xcon-monitor will establish secure connection with nsmd:5001 and forward CrossConnectEvents to insecure 6001 port.

Security #1: Proxy monitor for crossconnects

---

.mk/docker.mk
k8s/cmd/admission-webhook/const.go
k8s/cmd/admission-webhook/main.go
k8s/cmd/admission-webhook/utils.go

Since the mutating webhook admission controller adds the nsm-init container for NSCs, this change optionally adds the env vars for Jaeger tracing to the injected NSC initContainer if they are defined in the admission-webhook.
To be able to configure NSCs to send tracing info to Jaeger for troubleshooting and GRPC sequence information.
- [ x ] Tested locally
Testing without the env vars set is covered by the existing CI/integration tests.
- [ x ] New feature (non-breaking change which adds functionality)

Admission webhook: propagate jaeger host and port env vars to NSCs init containers

---

test/integration/usecase_deployment_order_test.go
test/kubetest/crds/icmpresponder.go
test/kubetest/crds/networkservice.go
test/kubetest/crds/secureintranetconnectivity.go
test/kubetest/utils.go

This PR adds tests to verify how NetworkService, NSE and NSC deployment order changes NSM behaviour.
We need to ensure that NSM can operate no matter the deployment order.

Add tests to verify NetworkService and NSE deployment order

---

.golangci.yml
controllers/sriov-controller/dpapi-controller.go
controlplane/pkg/monitor/tests/monitor_server_test.go
controlplane/pkg/nsmd/client.go
controlplane/pkg/nsmd/dataplanes.go
controlplane/pkg/nsmd/nsmd_crossconnect_client.go
controlplane/pkg/nsmd/serviceregistry.go
controlplane/pkg/nsmd/workspace.go
controlplane/pkg/tests/nsmd_crossconnect_client_test.go
controlplane/pkg/tests/nsmd_test_utils.go
controlplane/pkg/tests/test-listener.go
dataplane/pkg/common/dataplaneregistrarclient.go
dataplane/vppagent/pkg/vppagent/metrics_collector.go
dataplane/vppagent/pkg/vppagent/vppagent.go
k8s/cmd/crossconnect-monitor/crossconnect_monitor.go
k8s/cmd/nsmdp/nsmdp.go
pkg/tools/socket.go
pkg/tools/tools.go
sdk/common/connection.go
sdk/vppagent/flush.go
test/applications/cmd/proxy-xcon-monitor/main.go
test/applications/cmd/vppagent-nsc/vppagent.go
test/integration/basic_dataplane_standalone_test.go
test/integration/basic_monitor_crossconnect_metrics_test.go
test/kubetest/monitor_utils.go

Wrap `grpc.Dial` to `tools.Dial` with adding specific for project `grpc.DialOption` (configuring opentracing and security)
Throughout the project we have several ways to establish connections, lots of timeouts and opentracing is configured from scratch every time. 
To simplify adding security interceptors and credentials much better to have one configurable Dial that will be used everywhere in project.

Security #2: Refactor Dial methods

---

scripts/aws/create-kubernetes-cluster.go

AWS cluster starting script is printing nodes ssh private key for debug purposes. This log entry is not needed now so it has to be removed.

Remove aws cluster ssh private key printing

---

test/cloudtest/pkg/providers/packet/packet_provider.go

Errors from Packet.net cluster handling caused CloudTest to crash, 
and some clouds could leak because of this.

#1341 Fix crash to prevent cloud leaking.

---

k8s/cmd/nsm-coredns/plugin/fanout/fanout_test.go
k8s/cmd/nsm-coredns/plugin/fanout/health_test.go
k8s/cmd/nsm-coredns/plugin/fanout/persistent_test.go

The fanout tests wich using more then one DNS can fails. 
Root cause: used dns.HandleFunc() which should be used only for tests with one DNS server.
This PR fixed the problem

Stabilize fanout tests

---

test/cloudtest/pkg/commands/main.go
test/cloudtest/pkg/k8s/validator.go
test/cloudtest/pkg/tests/sample/sample_interdomain_test.go
test/cloudtest/pkg/tests/sample/sample_tagged_test.go
test/kubetest/k8s.go

Cloud testing fixes to make test failures in case of cluster failed more informative
Cloud testing tool should write a proper information about number of available nodes.
+ few fixes to prevent test to crash, they should fail instead of it.

Cloud testing fixes

---

test/integration/basic_monitor_crossconnect_test.go
test/integration/recover_xcon_monitor_test.go
test/kubetest/monitor_utils.go
test/kubetest/monitor_utils_test.go

Add new types of EventCheckers
There are bunch of tests that checks events from CrossConnectMonitor. Checker waits for `INITIAL_STATE_TRANSFER` with single crossconnect. But there is no guarantee that `INITIAL_STATE_TRANSFER` will be empty and we will see crossconnect only in the following `UPDATE` event. That situation reproduces in #1380, probably because of increasing delays.

Refactor EventCheckers

---

k8s/conf/crd-networkserviceendpoints.yaml
k8s/conf/crd-networkservicemanagers.yaml
k8s/conf/crd-networkservices.yaml

Changes the CRDs scope to `Namespaced` to align with a CVE fix in k8s here: https://github.com/kubernetes/kubernetes/commit/9d3c8b36d992cdbea00040f2c31d39f46e4c4219
We have failures with the release of the latest 1.15.2 and 1.14.5 which include CVE fixes. This update targets getting the latest versions of the associated code in order to fix these failures.
Fixes #1440

Make our CRDs namespaced

---

.cloudtest/aws.yaml
.cloudtest/azure.yaml
.cloudtest/gke.yaml
.cloudtest/packet.yaml
.mk/helm.mk
deployments/helm/nsm/templates/crd-networkserviceendpoints.yaml
deployments/helm/nsm/templates/crd-networkservicemanagers.yaml
deployments/helm/nsm/templates/crd-networkservices.yaml
docs/guide-helm.md

Add a unified `helm-init` make target to assist in deploying helm to the cluster where NSM is to be installed with the helm chart.
Have a convenient and unified way of initialising helm in the work cluster.

Introduce `make helm-init`

---

deployments/helm/nsm-monitoring/templates/jaeger.tpl
deployments/helm/nsm-monitoring/templates/skydive.tpl
deployments/helm/nsm-monitoring/values.yaml
deployments/helm/nsm/charts/admission-webhook/templates/admission-webhook-secret.tpl
deployments/helm/nsm/templates/nsmgr.tpl
deployments/helm/nsm/templates/vppagent-dataplane.tpl
deployments/helm/nsm/values.yaml

- include var for setting monitoring k8s service types
- fix missing namespace settings for templates in nsm-monitoring chart
Signed-off-by: Tim Swanson <tiswanso@cisco.com>
Add the ability to enable Jaegar tracing on components in the NSM helm charts.  Additionally, add a setting that maps to the monitoring services k8s service types--e.g. NodePort. 
| Chart | New setting | Possible Values | Description |
|---|---|---|--|
| deployments/helm/nsm |  global.JaegerTracing | `true`, `false` |  Enables the env vars for Jaeger tracing in each NSM component |
|  deployments/helm/nsm-monitoring | monSvcType | `ClusterIP`, `NodePort`, `LoadBalancer` | The service type for the monitoring UIs--currently Jaeger and Skydive |
Example usage of the settings:
```
helm template deployments/helm/nsm …
```

helm: Add option for enabling jaeger tracing in NSM components

---

.mk/gke.mk
scripts/aws/create-kubernetes-cluster.go

Allow inbound traffic for aws and gke clouds for interdomain connection purposes
Required for Interdomain NSM connection (#1298) #714

Allow inbound traffic for aws and gke clouds

---

.mk/k8s.mk

It was removed from the infra deployment by mistake in
"NSM init monitoring container (#1363)"

Fix crossconnect_monitor deployment

---

.cloudtest.yaml
test/cloudtest/pkg/runners/shelltest_runner.go

Example-helm-icmp waits for all pods in all namespaces. It might be a reason for failing tests on CI as by the link bellow. We should use `kubectl wait` onl y for current namespace.
https://circleci.com/gh/networkservicemesh/networkservicemesh/88010

Fix wait for Example-helm-icmp

---

.cloudtest.yaml

Cleanup Custom Resources after cloudtest examples to avoid affecting on integration tests.
Examples tests break all next integration tests

Cleanup crds after cloudtest examples

---

test/cloudtest/pkg/commands/main.go
test/cloudtest/pkg/model/tests.go

Keep order of tests clusters from configuration file
Add clusters names to keys of tests map.
Some tests are skipped because of duplicating of tests names for one cluster. (#1480)
Tested on integration tests:
https://circleci.com/gh/networkservicemesh/networkservicemesh/89208

Fix cloudtest to run tests on multiple clusters

---

.circleci/config.yml
.mk/code_analysis.mk
scripts/lint-download.sh

Last version of golang-ci linter has memory management problems, for example:
1) https://github.com/golangci/golangci-lint/issues/634
2) https://github.com/golangci/golangci-lint/issues/628
Resource class of current linter job (xlarge) takes much resources. It could affect to the containers builds.

Downgrade version of linter to 1.16.0 to reduce resource class of linter job

---

controlplane/pkg/apis/plugins/connection_plugin_helpers.go
controlplane/pkg/nsm/nsm.go
controlplane/pkg/plugins/connection_plugin.go

Jaeger client iterating Connection structure at the same time when we are trying to change it, so we need to make a deep copy before using it.
Failed tests in a few open pull requests:
https://90920-127937836-gh.circle-artifacts.com/0/home/circleci/project/.tests/cloud_test/gke-2_packet-1/logs/TestInterdomainVPNNSCRemote/nsmgr-gke-gke-2-2019-8-20-9092-default-pool-70c83abb-7027%3Ansmd-previous.log
The same issue with another request: #901

Fix concurrent access to Connection structure

---

controlplane/pkg/selector/match_selector.go

Signed-off-by: Tutkovics András <tutiandras@gmail.com>
A little typo in logs fixed
There was a typo in controlplane/pkg/selector/match_selector.go line 53. (ednpoint --> endpoint)

Fix typo in match_selector.go

---

deployments/helm/nsm-monitoring/templates/skydive.tpl
k8s/conf/skydive.yaml

Since the move of nsm API to v1alpha1, skydive is not able to fetch data from nsmgr.
A PR is trying to fix the issue upstream: https://github.com/skydive-project/skydive/pull/1875
Until this PR merges, I propose to fetch the skydive image from an alternative hub.docker repository.
Nsm is also using containerd+docker for vagrant deployment. The skydive configuration file need to be adapted to find netns.

Fix skydive issues with latest nsm libs and deployments

---

test/cloudtest/pkg/runners/gotest_runner.go

There are could be namespaces with pods left after failed tests (for example if test was failed by timeout). Clearing namespaces will remove affecting on next tests
https://circleci.com/gh/networkservicemesh/networkservicemesh/93507?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-checks-link
TestMovingConnection was failed first on timeout. Pods were not deleted. All next tests were failed because of busy node ports

Clear k8s namespaces on failed tests

---

scripts/aws/destroy-kubernetes-cluster.go
scripts/aws/kubernetes-cluster.go

Cleanup aws clusters older than N hours
AWS cluster consist of many parts (cluster, stack, nodes, keys, etc...). This tool helps to cleanup aws from old clusters

Cleanup old aws clusters tool

---

test/kubetest/k8s.go

Clear roles list after success deleting to avoid "role not found" error
TestNSMDDeploy sometimes fails with "role not found" error
https://94838-127937836-gh.circle-artifacts.com/0/home/circleci/project/.tests/cloud_test/packet-2/011-TestNSMDDeploy-run.log

Fix error on second k8s cleanup

---

.env/vendoring.env
.gitignore
.mk/docker.mk
.mk/vpp_agent.mk
build/Dockerfile.nsmd-k8s
build/Dockerfile.proxy-nsmd-k8s
controlplane/build/Dockerfile.nsmd
controlplane/build/Dockerfile.proxy-nsmd
dataplane/kernel-forwarder/build/Dockerfile.kernel-forwarder
dataplane/vppagent/build/Dockerfile.vppagent-dataplane
dataplane/vppagent/build/Dockerfile.vppagent-dataplane-dev
docker/Dockerfile.admission-webhook
docker/Dockerfile.crossconnect-monitor
docker/Dockerfile.nsm-coredns
docs/guide-build.md
k8s/build/Dockerfile.nsmdp
scripts/go-mod-download.sh
scripts/vagrant/Vagrantfile
side-cars/build/Dockerfile.nsm-init
side-cars/build/Dockerfile.nsm-monitor
test/applications/build/Dockerfile.test-common
test/applications/build/Dockerfile.vpp-test-common

Passing VENDORING="-mod vendor" will enable local vendoring
To speedup local development, local Vendoring cloud be enable by passing environment variable
```
export VENDORING="-mod vendor"
```
It will call `go mod vendor` to store all deps into vendor folder and will trigger all docker images to use vendored sources.

Allow local vendoring

---

dataplane/vppagent/pkg/converter/cross_connect_converter.go
dataplane/vppagent/pkg/vppagent/vppagent.go

Clear old mechanism configuration before updating connection
Taps should not be touched
SRv6 mechanism will add new segments list to policy instead if update:
```
[0].-    BSID: fd25::1:2
Behavior: Encapsulation
Type: Default
FIB table: 0
Segment Lists:
[0].- < fe80::a00:27ff:fec6:ca82, fd25::1:3 > weight: 0S
[1].- < fe80::a00:27ff:fec6:ca82, fd25::1:5 > weight: 0
```
Also old mechanism configuration may not be cleared if changing remote mechanism

Clear old mechanism configuration before update

---

.cloudtest.yaml
.cloudtest/packet.yaml
go.mod
go.sum
test/cloudtest/pkg/commands/main.go
test/cloudtest/pkg/config/config.go
test/cloudtest/pkg/providers/packet/packet_provider.go
test/cloudtest/pkg/tests/shell_provider_test.go

1. Fix for use of global timeout in CloudTest
2. Fix Packet.Destroy to use timeout and wait for devices to be really destroyed.
3. Fix CloudTest to stop operation on cluster if both start/destroy caused errors.

Fix CloudTest to work with timeouts and make Packet Destroy more smart.

---

test/integration/interdomain_nse_nsm_heal_test.go
test/integration/interdomain_vpn_test.go

Enabling TestInterdomainNSMHealRemoteDieNSMD_NSE and TestInterdomainVPNNSCRemote
Tests were fixed with #1538 and another fixes of stability

Enable interdomain tests

---

dataplane/kernel-forwarder/pkg/kernelforwarder/common.go

Replace the constant with its value. For some reason on Mac the `netlink.NUD_REACHABLE` constant cannot be found in the `netlink` package resulting in a vet error.

Fix vet error about not finding a constant in case of MacOS host machine

---

.circleci/config.yml
.cloudtest.yaml

Change NSM_NAMESPACE system env to nsm-system for all cloud tests
Go tests does not cleanup stacked pods because of different namespaces
https://circleci.com/gh/networkservicemesh/networkservicemesh/96707

Unify nsm namespaces for cloudtest

---

scripts/aws/destroy-kubernetes-cluster.go

Filter out deleted stacks when deleting all clusters
cloudformation.ListStacksInput api function returns limited result of stacks. Filtering out deleted stacks give full list of active stacks.

Add stack filter for deleting all aws clusters tool

---

test/integration/bench_connection_test.go

Do recover if "done" channel is already closed. 
Pods are not cleaned up properly if "done" channel is already closed.
```
panic: send on closed channel
goroutine 429 [running]:
github.com/networkservicemesh/networkservicemesh/test/integration.createNscAndPingIcmp(0xc000333cd0, 0xc0003c0510, 0x2, 0xc0002cd080, 0xc000193440, 0x21e9660, 0x21e9680)
/Users/artem/go/src/github.com/networkservicemesh/networkservicemesh/test/integration/bench_connection_test.go:152 +0x2da
created by github.com/networkservicemesh/networkservicemesh/test/integration.testMovingConnection
/Users/artem/go/src/github.com/networkservicemesh/networkservicemesh/test/integration/bench_connection_test.go:102 +0x391
```

Fix panic error in test moving connection

---

.cloudtest.yaml

Do force pods deleting to be sure that nsmgr release node ports.
Sometimes pods are stuck at _Terminating_ status after helm-delete-* command. Stucked pod does not release node port and breakes next tests
https://circleci.com/gh/networkservicemesh/networkservicemesh/96707

Do force deleting of stucked pods after examples tests

---

sdk/client/client.go
sdk/client/clientlist.go
side-cars/pkg/nsm-init/nsm-init.go
test/applications/cmd/monitoring-nsc/main.go
test/kubetest/k8s_exec.go.go

Restore nsm monitor to retry connecting to network service. Should fix #1622 
+ Fixes issue with K8s.Exec() in case pod is not available.

Nsm init retry

---

scripts/nsc_ping_all.sh
scripts/verify_vpn_gateway.sh

- Get rid of '-ti' flags for exec
- Increase ping attempts
[circleci](https://circleci.com/gh/networkservicemesh/networkservicemesh/101390#tests/containers/0)
According to logs of `k8s-check`: 
```
>>>>>>Running: make k8s-check:<<<<<<
===== >>>>> PROCESSING vpn-gateway-nsc-d545dc984-dttmf  <<<<< ===========
Defaulting container name to alpine-img.
Use 'kubectl describe pod/vpn-gateway-nsc-d545dc984-dttmf -n nsm-system' to see all of the containers in this pod.
Unable to use a TTY - input is not a terminal or the right kind of file
Defaulting container name to alpine-img.
Use 'kubectl describe pod/vpn-gateway-nsc-d545dc984-dttmf -n nsm-system' to see all of the containers in this pod.
Unable to use a TTY - input is not a terminal or the …
```

Get rid of '-ti' flags for exec, add attempts to ping

---

controlplane/go.mod
controlplane/go.sum
controlplane/pkg/tests/dataplane_heal_test.go
controlplane/pkg/tests/heal_nse_test.go
controlplane/pkg/tests/nsmd_local_test.go
controlplane/pkg/tests/nsmd_plugin_registry_test.go
controlplane/pkg/tests/nsmd_registry_test.go
controlplane/pkg/tests/nsmd_remote_test.go
controlplane/pkg/tests/nsmd_test_utils.go
controlplane/pkg/tests/restore_state_test.go
controlplane/pkg/tests/select_dataplane_test.go
dataplane/go.sum
go.sum
side-cars/go.mod
side-cars/go.sum
side-cars/pkg/nsm-monitor/nsm_monitor_test.go

It does because nsm_monitor tests were mistakenly put in controlplane/
This patch moves them to the right place under side-car/
In the process, various test utils needed to be exposed outside
their package.

Move nsm_monitor tests to nsm monitor in sidecar/ to avoid dep      controlplane/go.mod should not depend on side-car

---

test/kubetest/log_utils.go

https://github.com/networkservicemesh/networkservicemesh/issues/1605

Fix Missing logs from second cluster in interdomain circleci tests

---

.github/workflows/rebase.yaml
.yamllint.yml

Also disable 'truthy' yamllint rule, which will fail on the
GitHub Actions yaml file key 'on' even though its completely valid.

Add ability to rebase with /rebase comment via GitHub Actions

---

controllers/sriov-controller/go.mod
controlplane/api/go.mod
controlplane/go.mod
dataplane/api/go.mod
dataplane/go.mod
dataplane/go.sum
go.mod
k8s/api/go.mod
k8s/go.mod
sdk/go.mod
side-cars/go.mod
test/go.mod
utils/go.mod

Version v0.1.0 is a real version, and not at all
what we are depending on in the main networkservicemesh repo.
According to:
https://golang.org/cmd/go/#hdr-Pseudo_versions
It appears we should shift to v0.2.0 here so we can using v0.2.0-${timstamp}-${git commit id} in downstream projects like example to reference the modules.

Fixing internal dependency versions.

---

.mk/k8s.mk

There is no `k8s-coredns-build` target, leading to failure in `k8s-build`

Fix k8s-coredns-build target missing

---

test/kubetest/rbac/cluster_roles.go

Related to https://github.com/networkservicemesh/networkservicemesh/pull/1651
Added missed waiting for the service account creating
https://circleci.com/gh/networkservicemesh/networkservicemesh/103716
https://github.com/networkservicemesh/networkservicemesh/issues/1495

Fix Right after namespace creation "default" service account does not exist #2

---

scripts/for-each-module.sh

If each module has a vendor folder then script for-each-module.sh will visit all vendor modules...

Exclude vendor folder for script 'for-each-module'

---

.circleci/config.yml

Wait for spire build before start integration testing
Helm cannot start spire pods ("ImagePullBackOff") and shows:
`Error: release spire failed: timed out waiting for the condition`

Circleci - wait for spire build

---

scripts/for-each-module.sh

command execution happens inside a subshell, so changing 'res' variable doesn't do the work.
Do command invocation inside main shell

fix for-each-module script to return proper exit code

---

deployments/helm/nsm-monitoring/templates/skydive.tpl

Signed-off-by: Wayne <wayne@flickswitch.co.za>
Update skydive helm chart to use Release.namespace, instead of hardcoded namespace nsm-system
Deploying helm chart in other namespaces does not work.

Update helm chart to use release namespace

---

controlplane/pkg/nsm/nse_manager.go
controlplane/pkg/nsm/nsm.go
controlplane/pkg/nsm/nsm_heal_processor.go
controlplane/pkg/nsm/nsm_heal_processor_test.go
controlplane/pkg/nsmd/nsmd.go
controlplane/pkg/nsmd/registry.go
controlplane/pkg/nsmd/serviceregistry.go
controlplane/pkg/serviceregistry/serviceregistry.go
controlplane/pkg/tests/nsmd_test_utils.go
k8s/pkg/proxyregistryserver/discovery.go
k8s/pkg/registryserver/discovery.go
k8s/pkg/registryserver/nse.go
test/integration/basic_nsmd_k8s_test.go
test/kubetest/utils.go

Refactoring service registry - adding context to the registry clients
There is no way to cancel request (we were using context.Background())
May be required for the new features.

Add context to the request for registry service clients

---

test/cloudtest/pkg/utils/shell_utils.go
test/cloudtest/pkg/utils/shell_utils_test.go

In the investigation of failing https://circleci.com/gh/networkservicemesh/networkservicemesh/105477 I found that sometimes cloudtest shell script result can be not saved.  
Root cause: we using async read from stdout/stderr and in the case when the command exits we can lose the output.
https://circleci.com/gh/networkservicemesh/networkservicemesh/105477

Fix: Cloudtest sometimes does not save shell script's stdout/stderr

---

.circleci/config.yml

Helm could interpret passed commit id as not valid number, causing spire to not be uploaded properly.
${CIRCLE_SHA1:8:8} == 33207503
--set org=“networkservicemeshci”,tag=“33207503"
And helm some how intepreter it as value “3.3207503e+07”,

Use better commit id

---

.cloudtest.yaml

There is an issue with resolving Proxy NSMD service address on AWS cluster
The most Interdomain tests fails on aws cluster #1603

Disable aws-azure interdomain tests

---

test/integration/basic_dns_test.go

https://github.com/networkservicemesh/networkservicemesh/issues/1731

Add skip for TestNsmCorednsNotBreakDefaultK8sDNS if cluster dns not works

---

test/kubetest/k8s_exec.go.go

Return error from doExec if executed command timed out
doExec does not return error if executed command timed out. It does not affect on test result

Fix tests failing when executed command timed out

---

controlplane/api/remote/connection/constants.go
controlplane/pkg/nsm/nsm_mechanims.go
controlplane/pkg/remote/proxy_network_service_server/proxy_network_service_server.go
test/integration/interdomain_vpn_test.go

Keep original src ip and external dst ip to compare ip addresses properly
Enable TestInterdomainVPNFirewallRemote which was broken because of VNI selection issue 
#1695, #1354

VNI Selection improvement for interdomain

---

test/cloudtest/pkg/commands/main.go
test/cloudtest/pkg/config/config.go

If you add only-run to .cloudtest configuration it will only run the listed tests.
Super useful for running a small subset of tests that are failing in order to debug quickly.

Add only-run to cloudtest

---

Makefile
sdk/compat/networkservice_server.go
test/cloudtest/pkg/commands/main.go

'vet' and 'generate' targets were not updated upon switch to multi-module architecture.
A couple of errors has sneaked into master branch since then.

Fix make vet

---

dataplane/pkg/common/egress_interface.go
dataplane/pkg/common/egress_interface_test.go

Signed-off-by: Wayne <wayne@flickswitch.co.za>
User Scanner instead of reader.
refactored ParseProc, updated tests
[Issue](https://github.com/networkservicemesh/networkservicemesh/issues/1614)

update ParseProc to use scanner instead of reader

---

sdk/monitor/tests/monitor_server_test.go

https://github.com/networkservicemesh/networkservicemesh/issues/1814
The root cause of #1814: sometimes cross-connect monitor server goroutine can wrong handle a queue of events. 
For example:
1) Send update cross-connect event
2) Add new client
In some cases server at first will handle 1., in some cases will handle 2.
It is ok behavior but the test expects only case 1.

Fix: Unit test TestSimple is unstable on CI

---

controlplane/pkg/nsmd/discovery.go
controlplane/pkg/nsmd/workspace.go

There will be occasions when NSCs (particularly those which are also NSEs) may need
to make more sophisticated and programatic decisions than can be expressed in the NS resource
about Endpoint Selection.  This allows them to discover the NSEs to which to apply that criteria.

Expose Discovery Service to NSCs.

---

test/kubetest/k8s.go

Disable the span searching to speedup CI.
Currently, on CI we searching jaeger spans and storing jaeger traces.
We do not need to search spans if we store jaeger traces.

Do not search jaeger spans on CI

---

test/integration/basic_monitor_crossconnect_metrics_test.go

1) Expand VPP Agent logs for stats
2) Exclude case when an interface is created and removed within polling timeout https://github.com/ligato/vpp-agent/issues/1537#issuecomment-545464108
https://github.com/networkservicemesh/networkservicemesh/issues/1673

Metrics: Exclude case when interface is created and removed within polling timeout

---

test/integration/basic_nsmd_deploy_time_test.go
test/kubetest/k8s.go

In the [last PR](https://github.com/networkservicemesh/networkservicemesh/pull/1794) related to TestNSMDDeploy was improved logging. 
With new logs was found the root cause: sometimes on test time k8s pulling the image. 
We do not need to measure this time in the test.
```
time="2019-11-05T05:48:18Z" level=info msg="Pod nsmgr-aks-nodepool1-65165126-vmss000000 event: {\"metadata\":{\"name\":\"nsmgr-aks-nodepool1-65165126-vmss000000.15d42e213ed0e019\",\"namespace\":\"nsm-system-zjngh\",\"selfLink\":\"/api/v1/namespaces/nsm-system-zjngh/events/nsmgr-aks-nodepool1-65165126-vmss000000.15d42e213ed0e019\",\"uid\":\"d94340cf-ff8f-11e9-9f0b-0aa9205ebeef\",\"resourceVersion\":\"1904\",\"creationTimestamp\":\"2019-11-05T05:48:10Z\"},\"involve …
```

Do not measure image pulling time for TestNSMDDeploy

---

.mk/integration.mk
.mk/k8s.mk

- Use system value of NSM_NAMESPACE environment if exists
- Run integration tests from test module directory
- NSM_NAMESPACE is taken from yaml config file even if environment variable exists in system. NSM namespace could not been cleaned up after failed tests
- Integration tests cannot be runnable by make scripts

Fix broken make scripts

---

test/cloudtest/pkg/commands/main.go
test/cloudtest/pkg/providers/packet/packet_provider.go
test/cloudtest/pkg/shell/shell_manager.go

Remove some output info which has duplications in log files
Optimize Duration print format
Print less statistics info
Only the last 400000 characters are displayed in circleci log. Optimizing cloudtest output help to get more information while testing is in progress

Optimize cloudtest output

---

test/kubetest/k8s.go
test/kubetest/pods/common.go
test/kubetest/rbac/cluster_roles.go

The previous fix(https://github.com/networkservicemesh/networkservicemesh/pull/1655) was broken after landing https://github.com/networkservicemesh/networkservicemesh/pull/1380, [line](https://github.com/networkservicemesh/networkservicemesh/blob/master/test/kubetest/rbac/cluster_roles.go#L217). 
Root cause: not good fixing, do not wait for service accounts on creating role bindings.
https://114224-127937836-gh.circle-artifacts.com/0/home/circleci/project/.tests/cloud_test/aws-3_azure-5/001-TestInterdomainNSEHealRemote-run.log

Add wait for default service account on creating nsm service accounts

---

test/cloudtest/pkg/commands/main.go

it happens when one of the required by a test clusters is disabled, test gets 'Skipped' state in createTasks(), but the state is then ignored by assignTasks(), then a crash happens in executeTask():
`panic: runtime error: index out of range [1] with length 1
goroutine 3833 [running]:
github.com/networkservicemesh/networkservicemesh/test/cloudtest/pkg/commands.(*executionContext).executeTask.func1(0xc0002a0fc0, 0xc0003ee1e0, 0xc00093f260, 0x1, 0x1, 0x163dde0, 0xc000bd8d08, 0xc0002bd328, 0x5, 0x1644ce0, ...)
/home/circleci/project/test/cloudtest/pkg/commands/main.go:693 +0x166b
created by github.com/networkservicemesh/networkservicemesh/test/cloudtest/pkg/commands.(*executionContext).executeTask
/home/circleci/project/test/cloudtest/pkg/commands/main.go:660 +0x16e
`

fix cloudtest crash caused by ignoring test's Skipped state

---

test/kubetest/pods/versioning.go

To match the default container tag in k8s.mk (CONTAINER_TAG)

cloudtest: set default container tag to 'master'

---

.cloudtest/kind.yaml
.cloudtest/vagrant.yaml

replace non-existent target 'spire-start' with 'spire-install'

Fix typos in spire setup for vagrant and kind

---

docs/spec/dns-integration.md

This commit improves the DNS integration
documentation focusing on how the user can enable
the capability.
Signed-off-by: john-a-joyce <joycej@cisco.com>
This is a documentation only change.   It provides more detail on all the components in the 
DNS integration path.  It adds more information on the role of the NSE in DNS integration
and includes the key user config options of setting NSE environmental variables to trigger
updates of the DNS configuration in the application pod.  
The key user steps to set environmental variables was missing. 
Documentation only. 
Documentation.

Improve DNS documentation

---

docs/examples/icmp-responder.md
docs/examples/vpn.md
docs/examples/vpp-icmp-example.md

The examples docs refer to `master/scripts/nsc_ping_all.sh`, which
might be changed in `master`. Replace it with
`release-0.2/scripts/nsc_ping_all.sh` instead.
Signed-off-by: Nikolay Nikolaev <nnikolay@nnikolay-a01.vmware.com>

Change reference to master in examples docs

---

test/integration/recover_death_handling_test.go

NSE dead handling tests check for 100% packet transmit, but it could not be true, so check for at least one packet send is more stable approach.

Fix #1872 Check only for all packets loss

---

controlplane/pkg/nsm/nsm.go

https://github.com/networkservicemesh/networkservicemesh/issues/1914

Fix: Invalid memory address or nil pointer dereference on networkServiceManager.getEndpoint

---

test/cloudtest/pkg/commands/main.go
test/cloudtest/pkg/tests/shell_provider_test.go

* Remove multiple chaotic calls to printStistics() during clusters startup
* Remove statistics from 'test complete' message

Cleanup cloudtest messages

---

deployments/helm/nsm/templates/nsmgr.tpl
k8s/conf/debug/nsmgr-debug.yaml
k8s/pkg/registryserver/helpers.go
test/integration/basic_delete_nsm_custom_resource_test.go
test/kubetest/k8s.go
test/kubetest/pods/nsmd.go
test/kubetest/utils.go

Delete nsm custom resource from registry when pod deleted
OwnerReferences  resource option removes child resource if parent deleted 
#927

Delete nsm custom resource when pod deleted

---

scripts/nsc_ping_all.sh

Client/endpoint namings were not updated in the nsc_ping_all.sh script
causing the k8s-check target to fail/do nothing.

Fix k8s-check due to wrong client/endpoint naming

---

scripts/vagrant/env.sh

Steps to reproduce:
1) `make vagnrat-start`
2) `scripts/vagrant/env.sh`
3) `make k8s-load-images`
Actual:
```Loading image admission-webhook.tar to kind
Delegated to kind-admission-webhook-load-images
Loading image crossconnect-monitor.tar to kind
Delegated to kind-crossconnect-monitor-load-images
Loading image kernel-forwarder.tar to kind
...
```
Expected: images loading to vagrant.

Fix image loading to vagrant via k8s-load-images

---

.cloudtest.yaml
.mk/vagrant.mk
controlplane/pkg/local/endpoint_selector_service.go
pkg/tools/spanhelper/span_helper.go
test/cloudtest/pkg/commands/main.go
test/cloudtest/pkg/config/config.go
test/cloudtest/pkg/model/tests.go
test/cloudtest/pkg/tests/retest_test.go
test/cloudtest/pkg/tests/sample/restart_restart_test.go
test/cloudtest/pkg/tests/shell_provider_test.go
test/cloudtest/pkg/utils/process.go
test/cloudtest/pkg/utils/utils.go
test/cloudtest/pkg/utils/utils_test.go
test/integration/basic_exec_test.go
test/integration/usecase_vpn_test.go
test/kubetest/k8s.go
test/kubetest/utils.go

Our test framework should detect a CNI network plugin problems during deploy of pods and try to re-deploy if this situation is detected.
Tests could fail because of CNI plugin failed to assign IP address, we need to retry pod deploy in such situations.

Support re-deploy on CNI network errors

---

test/cloudtest/pkg/tests/retest_test.go
test/cloudtest/pkg/utils/utils.go

The order of log messages can change because the code producing them is executed in concurrent goroutines.

Adjust retest unit tests for concurency (goroutine)

---

scripts/for-each-module.sh

Use the POSIX `eval` when invoking the command as specified
as an argument to ./scripts/for-each-module.sh. This ensures
better command handling and the ability to use the module name
in the command. 
Example:
```bash
./scripts/for-each-module.sh "eval 'echo  \${d#\.\/}'"
```
To improve the capabilities of our modules tooling.

Use eval in for-each-module.sh

---

.cloudtest/kind.yaml
.mk/kind.mk
docs/guide-build.md
docs/guide-kind.md

Updated Kind is now using kubectl context to point to the right cluster. Drop all the oldschool `kubeconfig-path` references in the make machinery and in the docs.
The old way of referring to the cluster is obsoleted and will be deprecated at some point. It is automatically set now, so no need to do anything for a single deployed kind cluster.

Kind uses context now, drop KUBECONFIG

---

forwarder/sdk/vppagent/commit.go
forwarder/vppagent/pkg/vppagent/vppagent.go

Call downstream resync on failed vpp-agent update
Failed vpp-agent update might be the cause of vpp - vppagent desynchronization
#853 
```
time="2019-12-02T11:00:21Z" level=warning msg="VPP health check probe timed out after 250ms (1. timeout)"
time="2019-12-02 11:00:22.03173" level=error msg="no reply received within the timeout period 1s" loc="descriptor/interface_crud.go(27)" logger=vpp-ifplugin.if-descriptor
time="2019-12-02T11:00:22Z" level=warning msg="Received reply to an already closed binary API request" seqNum=28
time="2019-12-02T11:00:22Z" level=warning msg="ignoring received reply: &{seqNum:28 msgID:56 data:[0 56 0 6 0 28 0 0 0 0 0 0 0 2] lastReceived:false err:<nil>} (expecting: vxlan_add_del_tunnel_reply)" channel=3 …
```

Call downstream resync on failed vpp-agent update

---

.cloudtest.yaml
test/cloudtest/pkg/commands/main.go
test/cloudtest/pkg/config/config.go
test/cloudtest/pkg/tests/all_cluster_fail_test.go
test/cloudtest/pkg/tests/shell_provider_test.go

Cloud test somehow could assign test on inter domain and on regular single cloud test, this is attempt to figure out why it is happening.
1. Fixes issue with cluster failures detect warmup delay.
2. Add ability to configure interval for printing statistics.
3. Add ability to shuffle tests from different executions to find dependency errors.

CloudTest improvements

---

test/cloudtest/pkg/commands/health.go
test/cloudtest/pkg/commands/main.go
test/cloudtest/pkg/tests/cloud_config_test.go

```
panic: send on closed channel
goroutine 40 [running]:
github.com/networkservicemesh/networkservicemesh/test/cloudtest/pkg/commands.RunHealthChecks.func1(0xc000146620, 0x1, 0x1, 0xc000378310, 0xc00036c780, 0x0)
/home/circleci/project/test/cloudtest/pkg/commands/commands.go:1602 +0x343
created by github.com/networkservicemesh/networkservicemesh/test/cloudtest/pkg/commands.RunHealthChecks
/home/circleci/project/test/cloudtest/pkg/commands/commands.go:1588 +0xaf
```
where commands/commands.go = commands/main.go on master branch
build:
https://circleci.com/gh/networkservicemesh/networkservicemesh/117053?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-checks-link

cloudtest health check: fix panic 'send on closed channel'

---

test/kubetest/k8s.go

Fix test failing if pod was not created properly
Take a look at TestInterdomainNSMHealRemoteDieNSMD_NSE:
https://circleci.com/gh/networkservicemesh/networkservicemesh/116774

Fix test failing if pod was not created properly

---

.cloudtest/packet.yaml
.cloudtest/packet/create-kubernetes-cluster.sh
.cloudtest/packet/download-postmortem-data.sh
scripts/terraform/create-kubernetes-cluster.sh
scripts/terraform/download-postmortem-data.sh

Add `IdentitiesOnly=yes` option to ssh command
Packet start script fails with error:
`Received disconnect from <ip> port 22:2: Too many authentication failures`
https://117120-127937836-gh.circle-artifacts.com/0/home/circleci/project/.tests/cloud_test/packet-6/032-start.log

Fix ssh fail on packet start

---

scripts/aws/amazon-eks-nodegroup.yaml

Change AWS instance type to t2.large
TestInterdomainVPNNSERemote is unstable with an error
```time="2019-12-09T02:55:57Z" level=error msg="blockUntilPodReady failed. Cause: pod vppagent-passthrough-nse-5 deploy error: Failed create pod sandbox: rpc error: code = Unknown desc = failed to set up sandbox container \"dd00e008078d2a0bd5689c48b2d051bb27399c25e84c1af539ca33cc5613dd26\" network for pod \"vppagent-passthrough-nse-5\": NetworkPlugin cni failed to set up pod \"vppagent-passthrough-nse-5_nsm-system-bhhf4\" network: add cmd: failed to assign an IP address to container. pod: vppagent-passthrough-nse-5"```
Cause of the issue:
t2.medium has a limit of 17 pods (limited ip addresses per interface), which is reached with all default …

Change AWS instance type

---

controlplane/pkg/tests/nsmd_registry_test.go
deployments/helm/icmp-responder/templates/icmp-responder-nse.tpl
deployments/helm/vpn/templates/vpn-gateway-nse.tpl
deployments/helm/vpn/templates/vppagent-firewall-nse.tpl
deployments/helm/vpn/templates/vppagent-passthrough-nse.tpl
deployments/helm/vpp-icmp-responder/templates/vpp-icmp-responder-nsc.tpl
deployments/helm/vpp-icmp-responder/templates/vpp-icmp-responder-nse.tpl
k8s/conf/vppagent-passthrough-nse.yaml
sdk/README.md
sdk/client/client.go
sdk/client/clientlist.go
sdk/common/configuration.go
sdk/endpoint/endpoint.go
sdk/tests/firewall_test.go
test/integration/basic_excluded_prefixes_test.go
test/integration/basic_nsmd_k8s_excluded_prefixes_test.go
test/integration/interdomain_death_handling_test.go
test/integration/interdomain_nsc_icmp_configuration_test.go
test/integration/interdomain_nse_forwarder_heal_test.go
test/integration/interdomain_nse_heal_test.go
test/integration/interdomain_nse_nsm_heal_test.go
test/integration/interdomain_vpn_test.go
test/integration/usecase_vpn_test.go
test/kubetest/utils.go

Renames the SDK env configuration variables as follows:
* `ADVERTISE_NSE_NAME` -> `ENDPOINT_NETWORK_SERVICE`
* `ADVERTISE_NSE_LABELS` -> `ENDPOINT_LABELS`
* `OUTGOING_NSC_NAME` -> `CLIENT_NETWORK_SERVICE`
* `OUTGOING_NSC_LABELS` -> `CLIENT_LABELS`
Deprecates #931 and closes #866.
Our env variable naming in the SDK is a bit confusing and refers ro NSE and NSC which we want to replace with the terms Endpoint and Client.

Rename config env

---

scripts/aws/create-kubernetes-cluster.go
scripts/aws/kubernetes-cluster.go

Restart cluster creation script if Throttling error
Creating few clusters in parallel may cause AWS Throttling error
https://circleci.com/gh/networkservicemesh/networkservicemesh/117730

Repeat AWS cluster creation if catched Throttling error

---

test/integration/usecase_vpn_test.go

Added few ping attempts in vpn tests check.
Sometimes for some reason ping fails on first attempt, but starts passing on the second. 
https://github.com/networkservicemesh/networkservicemesh/issues/1940

Fix failed ping in vpn tests

---

controlplane/pkg/nsm/nsm_heal_processor.go
controlplane/pkg/nsmd/nsmd.go
test/integration/basic_delete_dirty_nse_test.go

Removed code in method `DeleteEndpointWithBrokenConnection`, which skips deleting endpoint when it has active client connection. 
It was expected that `MonitorNetNsInodeServer` handles that case, but this logic wasn't implemented. 
So when endpoint has no handlers to cleanup itself from the registry once it's killed, it will never be deleted from the registry. 
Also we had  `TestDeleteDirtyNSEWithClient` to test case, but it was invalid, so I fixed it too.  
#1898

Broken connections handling fix

---

test/integration/interdomain_vpn_test.go
test/integration/usecase_vpn_test.go

We need to figure out why sometimes vpn tests failing with "command terminated with exit code 1",
https://circleci.com/gh/networkservicemesh/networkservicemesh/117856?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-checks-link

Improve logging for vpn tests

---

test/cloudtest/pkg/providers/packet/packet_provider.go

Check packet facilities by one per request
If packet facilities contains facility "iah1", request returns 
`500 Oh snap, something went wrong! We've logged the error and will take a look - please reach out to us if you continue having trouble. `

Fix packet provider

---

test/cloudtest/pkg/commands/main.go
test/cloudtest/pkg/commands/poll_events_test.go

https://github.com/networkservicemesh/networkservicemesh/issues/1981

Fix: 'CloudTest: Test doesn't get rescheduled when cluster fails'

---

.cloudtest.yaml

Sometimes, the whole CI run fails because of a single docker registry glitch:
`message\":\"Failed to pull image \\\"networkservicemeshci/nsmd:ci_772866e5-22ed-4ed5-a4d3-ced57a16ee40_c5613003\\\": rpc error: code = Unknown desc = Error response from daemon: Get https://registry-1.docker.io/v2/networkservicemeshci/nsmd/manifests/ci_772866e5-22ed-4ed5-a4d3-ced57a16ee40_c5613003: dial tcp: lookup registry-1.docker.io on 147.75.207.208:53: read udp 139.178.88.101:58317-\\u003e147.75.207.208:53: i/o timeout\"
`
In such situations seems reasonable to make another try, so the PR adds a re-test pattern.
https://circleci.com/gh/networkservicemesh/networkservicemesh/118570?utm_campaign=workflow-failed&utm_medium=email&utm_source=notification

CloudTest: re-run test if docker registry was unavailable

---

controlplane/pkg/local/forwarder_service.go
forwarder/sdk/vppagent/chained_forwarder_server.go
forwarder/sdk/vppagent/chained_forwarder_server_test.go
forwarder/sdk/vppagent/clear_mechanisms.go
forwarder/sdk/vppagent/commit.go
forwarder/sdk/vppagent/connect.go
forwarder/sdk/vppagent/context.go
forwarder/sdk/vppagent/direct_memif_interfaces.go
forwarder/sdk/vppagent/kernel_interfaces.go
forwarder/sdk/vppagent/next.go
forwarder/sdk/vppagent/request_validator.go
forwarder/sdk/vppagent/use_crossconnect_monitor.go
forwarder/sdk/vppagent/use_ethernet_context.go
forwarder/vppagent/pkg/vppagent/vppagent.go

Sometimes vpn test not passing because ping is not a success with 1 attempt. By logs from https://circleci.com/gh/networkservicemesh/networkservicemesh/118345 I found that ARP entry was not set on NSC interface. Because at now [EthernetContext using only for remote cases](https://github.com/networkservicemesh/networkservicemesh/blob/master/controlplane/pkg/remote/forwarder_service.go#L314) (Before we did not face with ARP problem for local cases).
1) https://circleci.com/gh/networkservicemesh/networkservicemesh/118345
2) https://github.com/networkservicemesh/networkservicemesh/issues/1774

Fix: Sometimes VPN tests not passing because ping is not a success with 1 attempt

---

test/cloudtest/pkg/commands/main.go
test/cloudtest/pkg/tests/all_cluster_fail_test.go
test/cloudtest/pkg/tests/retest_test.go

Currently, in a situation when one of the providers is completely down, the tests scheduled for its clusters appear as failed at the end of testing.
This should not happen.

CloudTest: do not report as failed tests skipped due cluster unavailability when a whole cloud is down

---

controlplane/pkg/nsm/nsm_heal_processor.go
controlplane/pkg/tests/heal_nse_test.go
controlplane/pkg/tests/nsmd_local_test.go
controlplane/pkg/tests/nsmd_registry_test.go
controlplane/pkg/tests/nsmd_test_utils.go
controlplane/pkg/tests/test_model.go

Added handling of the case when client connection is closed while healing. 
Now all healing connections are stored in healProcessor, and are checked in method CloseConnection.
There are some cases when healing continues, if client died while healing.

Handle case when client connection is closed while healing

---

controlplane/pkg/services/client_connection_manager.go
forwarder/pkg/common/monitor_netnsinode_server.go
test/integration/recover_nse_heal_test.go

Wait until healing state is done before closing connection.
Reduced interval between NetNsInode checks.
Canceling healing context is done in pull request #1932
Healed connection creates duplicated interface: #2015

Fix closing connection in healing state

---

test/kubetest/k8s.go
test/kubetest/pods/common.go

If the test started on the newly created cluster then it can fail with `Authorization error (user=kube-apiserver-kubelet-client, verb=create, resource=nodes, subresource=proxy)`. It means that the system cluster roles were not created at the test moment,
https://circleci.com/gh/networkservicemesh/networkservicemesh/119583
**Logs:**
Test error:
```
Test execution failed TestNSCAndICMPLocal
Execution attempt: 0 Output file: .tests/cloud_test/packet-4/011-TestNSCAndICMPLocal-run.logStarting TestNSCAndICMPLocal on packet-4
...
utils.go:409:
Expected
<*errors.withStack | 0xc00039e8c0>: {
error: {
cause: {
s: "error upgrading connection: unable to upgrade connection: Authorization error (user=kube-apiserver-kubelet-client, verb=create, …
```

Add wait for cluster role 'system:kubelet-api-admin'

---

test/integration/interdomain_vpn_test.go

Sometimes VPN interdomain tests can have a packets loss for example:
https://circleci.com/gh/networkservicemesh/networkservicemesh/119534
```
Ping response: PING 172.16.1.2 (172.16.1.2): 56 data bytes\n64 bytes from 172.16.1.2: seq=1 ttl=255 time=35.549 ms\n64 bytes from 172.16.1.2: seq=2 ttl=255 time=34.186 ms\n64 bytes from 172.16.1.2: seq=3 ttl=255 time=33.041 ms\n64 bytes from 172.16.1.2: seq=4 ttl=255 time=37.760 ms\n64 bytes from 172.16.1.2: seq=5 ttl=255 time=36.520 ms\n64 bytes from 172.16.1.2: seq=7 ttl=255 time=36.853 ms\n64 bytes from 172.16.1.2: seq=8 ttl=255 time=36.373 ms\n64 bytes from 172.16.1.2: seq=9 ttl=255 time=36.848 ms\n\n--- 172.16.1.2 ping statistics ---\n11 packets transmitted, 8 packets received, 27% …
```

Fix: TestInterdomainVPNNSCRemote can fail because of some packets loss

---

deployments/helm/nsm/templates/forwarding-plane.tpl

Fix forwarding plane manifest's indent with kernel-forwarder.
When I runned `helm install` or `helm upgrade` with kernel-forwarder (use forwardingPlane: kernel), error with following message.
```
Error: UPGRADE FAILED: error validating "": error validating data: ValidationError(DaemonSet.spec.template.spec.containers[0].readinessProbe): unknown field "resources" in io.k8s.api.core.v1.Probe
```

fix to occor `unknown field "resources" in io.k8s.api.core.v1.Probe` error when helm install with kernel-forwarder

---

deployments/helm/nsm/templates/nsmgr.tpl

Fix liveness/readiness probe host in helm based deployment
Liveness/readiness probes are executed by default against PodIP, while with current helm installation nsmd is listening for them on localhost:
```
time="2020-01-10T11:24:58Z" level=info msg="Waiting for liveness probe: tcp:127.0.0.1:5000"
```
... what leads to loop like:
```
Normal   Started    24m (x2 over 25m)    kubelet, node5     Started container nsmd
Warning  Unhealthy  23m (x4 over 24m)    kubelet, node5     Liveness probe failed: Get http://10.233.70.17:5555/liveness: dial tcp 10.233.70.17:5555: connect: connection refused
Warning  BackOff    5m6s (x49 over 18m)  kubelet, node5     Back-off restarting failed container
Warning  Unhealthy  3s (x56 over 25m)    kubelet, node5     Readiness probe failed: Get …
```

Fix liveness/readiness probe host

---

.mk/helm.mk
scripts/helm-init-wrapper.sh
scripts/helm-nsm-install.sh
scripts/helm-nsm-uninstall.sh

This change adds support for Helm 3 while ensuring backward compatibility
with Helm 2. To accomplish this, affected make targets now invoke
wrapper scripts that determine the version of Helm available and invoke
helm accordingly.
Signed-off-by: Ryan Tidwell <rtidwell@suse.com>
* Introduce wrapper scripts for the 'helm init' step and the NSM install steps. These scripts check the version of the helm client available and proceed accordingly.
* Change .mk/helm.mk to invoke wrapper scripts so that makefiles are insulated from the differences in helm versions.
With the recent availability of Helm 3 and support for Helm 2 disappearing in about a year, a little housekeeping to ensure compatibility with Helm 3 is in order. See #1950

Add support for Helm 3 in make targets

---

scripts/verify_crossconnect_monitor.sh

Added wait for events
https://circleci.com/gh/networkservicemesh/networkservicemesh/119419
Sometimes Example-helm-crossconnect-monitor can fail.
Expected test behavior: the test waits for events some time.
Actual test behavior on the master branch:  the test doesn't wait for events.

 Fix: Crossconnect monitor example test doesn't wait for events

---

k8s/pkg/registryserver/nse.go
test/integration/interdomain_floating_interdomain_die_test.go
test/integration/interdomain_floating_interdomain_monitor_test.go
test/integration/interdomain_floating_interdomain_test.go

In integration tests proxy-nsmgr k8s service starting not instantly. So RegisterNSE request may be rejected. Added checking for BulkRegisterNSE request result to verify NSE registration.
#2077

Fix floating interdomain integration tests

---

docs/spec/admission.md

We need to clarify how nsm-init container is added to the list of POD by admission webhook.
Related to https://github.com/networkservicemesh/networkservicemesh/pull/2081#issuecomment-578634062

Update admission.md documentation

---

deployments/helm/client/templates/nsc.tpl
deployments/helm/endpoint/templates/icmp-responder-nse.tpl
deployments/helm/vpp-icmp-responder/templates/vpp-icmp-responder-nsc.tpl
deployments/helm/vpp-icmp-responder/templates/vpp-icmp-responder-nse.tpl

Clients are deployed into different nodes using anti-affinity to ensure
both remote and local connection cases are covered.
see  #2056 for details.

2 clients and 1 endpoint in vpp-icmp-responder, icmp-responder Helm charts

---

scripts/prepare-cluster.sh

fix for #2086 
Additionally, a waiting is added for unavailable services to become available, which prevents helm initialization errors on GKE, like here: 
https://120466-127937836-gh.circle-artifacts.com/0/home/circleci/project/.tests/cloud_test/gke-3/003-prepare.log

fix: cluster initialization failure ignored

---

scripts/aws/destroy-kubernetes-cluster.go

First run `DeleteStack` attempt without `RetainResources` parameter  
`RetainResources` parameter of `DeleteStack` request does not supported while cluster in `Failed` state

Fix aws cluster deleting

---

.cloudtest.yaml

Add cloudtest retest pattern
`Error response from daemon: Get https://.*docker.io/.*: net/http: request canceled while waiting for connection`
#2068

Add retest pattern for docker.io request timeout

---

.cloudtest/azure.yaml

This reverts commit 2810d98ce9b4c7ca82c937567b0818702dca6f52.
Looks like the problem with device plugin on azure clusters is fixed and we can enable azure.
https://github.com/networkservicemesh/networkservicemesh/issues/2106

Revert "Temporarily disable testing on Azure (#2109)"

---

applications/nsmrs/pkg/serviceregistryserver/cache.go
k8s/pkg/proxyregistryserver/registry.go

1. https://github.com/networkservicemesh/networkservicemesh/issues/2142
2. Fixes spam in logs 
```
time="2020-05-11T18:17:22Z" level=warning msg="Cannot connect to Proxy NSMGR pnsmgr-svc:5005 : error forwarding BulkRegisterNSE request to pnsmgr-svc:5005 : Connection to Network Registry Server is not available: Connection to Network Registry Server is not available" operation=ProxyNsmgr.BulkRegisterNSE span="{}"
time="2020-05-11T18:17:22Z" level=warning msg="Cannot connect to Proxy NSMGR pnsmgr-svc:5005 : error forwarding BulkRegisterNSE request to pnsmgr-svc:5005 : Connection to Network Registry Server is not available: Connection to Network Registry Server is not available" operation=ProxyNsmgr.BulkRegisterNSE span="{}" …
```

Fix: proxy nsmd-k8s could infinity times try to reconnect

---

deployments/helm/nsm/templates/nsmgr.tpl

Define variable PREFERRED_REMOTE_MECHANISM for nsmd container (in addition to nsmdp)
According to our tests, the variable `PREFERRED_REMOTE_MECHANISM` is also used by the `nsmd` container.
Whether the `nsmdp` container actually uses the variable, has not been tested by us.

Define variable PREFERRED_REMOTE_MECHANISM for nsmd container

---

controlplane/pkg/metrics/helpers.go
controlplane/pkg/metrics/prometheus.go
deployments/helm/nsm/charts/admission-webhook/templates/admission-webhook-secret.tpl
deployments/helm/nsm/charts/admission-webhook/values.yaml
docs/spec/metrics.md
k8s/cmd/crossconnect-monitor/crossconnect_monitor.go
test/integration/basic_monitor_crossconnect_metrics_test.go

A bug was reproduced after testing metrics with the 4g-network example:
cross-connect id did not always map event metrics properly. This change
provides a fix. It also updates the documentatation with more details
how to use metrics observability features

Fix cross-connect metrics mapping

---

pkg/tools/tools.go

In some cases for better readability requested network service annotations can be specified in this form:
```
ns.networkservicemesh.io: l3vpnnse/vrf_red?vpn=100:100, l3vpnnse/vrf_blue?vpn=101:101, l3vpnnse/vrf_green?vpn=105:105
``` 
Currently In this case leading space, is considered as a part of the name and as a result request to find such name fails. It is very difficult to spot in the error message because the output is not quoted.
```
time="2020-06-21T12:38:32Z" level=error msg="nsm client: Failed to connect rpc error: code = Unknown desc = NSM:(7.1.5) <nil>. Last NSE Error: rpc error: code = Unknown desc = no NetworkService with name:  l3vpnnse. Retry attempts: 9 Delaying: 5s" operation="nsmClient.Connect.attempt:1" span="{}"
``` …

Trimming possible leading spaces from network service name

---

.circleci/config.yml

We are planning to update cloudtest with these issues:
https://github.com/networkservicemesh/cloudtest/issues/34
https://github.com/networkservicemesh/cloudtest/issues/35
https://github.com/networkservicemesh/cloudtest/issues/33
So it looks like we need at first fix up version of cloudtest on ci to avoid potential new problems.

fix: Use a concrete version of cloud testing tool to avoid problems with updating

---

forwarder/kernel-forwarder/pkg/kernelforwarder/remote/wireguard.go

Currently, we are using the wrong prefix in wireguard device logger that can confuse the users/developers. For example, all wireguard device entries in logs start with string `Wireguard Error `

fix: wireguard device logger prefix shouldn't confuse

---

forwarder/vppagent/pkg/converter/kernel_connection_converter.go

This change fixes the gateway address assignment for kernel-forwarded NS Endpoint.
Fixes https://github.com/networkservicemesh/networkservicemesh/issues/2179 .

Fix GW address assignment for kernel-forwarded NSE

---

.circleci/config.yml
.mk/helm.mk
deployments/helm/nsm/charts/admission-webhook/templates/admission-webhook-secret.tpl
deployments/helm/nsm/charts/admission-webhook/values.yaml
k8s/cmd/admission-webhook/const.go
k8s/cmd/admission-webhook/main.go
k8s/cmd/admission-webhook/mutate.go
k8s/cmd/admission-webhook/patches.go
k8s/cmd/admission-webhook/utils.go
test/kubetest/pods/common.go
test/kubetest/pods/coredns_injection.go
test/kubetest/pods/nsc.go

Make the Admission Webhook assign a hardcoded set of limits to the containers it creates if the original pod matches the requirements of the Guaranteed QoS class.
Use the following set of limits:
|Container image        | Memory|   CPU|
|-----------------|------:|-----:|
|`nsm-monitor`| `15Mi`|`100m`|
|`coredns`        |`15Mi`|`100m`|
|`nsm-init`       |`20Mi`|`500m`|
|`nsm-dns-init`   |`15Mi`|`500m`|
Also, to prove that these limits are sufficient, impose them on the CI tests unconditionally (including the containers created directly rather than by the Admission Webhook).
Closes #2187.

Put limits on containers created by admission-webhook

---

sdk/client/client.go

It looks like creating of wireguard device can take time more than the client expected in case of interdomain
https://github.com/networkservicemesh/networkservicemesh/issues/2198

fix: Increase connect time for TestInterdomainKernelForwarderWireguard

---

docs/guide-build.md
scripts/kind.yaml

The instructions provided by [this guide](https://github.com/networkservicemesh/networkservicemesh/blob/master/docs/guide-build.md#install) seems to be out of dated.
- KinD has [dropped](https://github.com/kubernetes-sigs/kind/commit/3abbcbbb99cec020a052c97eeaf427229b7514ac) `v1alpha3`
- `SPIRE_ENABLED` and `--spire_enabled` aren't validated in the `helm-nsm-install.sh` script.
- `NSM_NAMESPACE` uses `nsm-system` as default value which is not created.
-  `SPIRE_ENABLED` is enabled by default
These changes allow the creation and installation of a KinD cluster.

Update Kind setup instructions

---

deployments/helm/nsm/charts/spire/Chart.yaml
deployments/helm/nsm/charts/spire/templates/server-statefulset.tpl

SPIRE 0.11.0 has two new CVEs, discovered during a CNCF security audit. While I believe neither of them affects NSM's use case, it should still be fixed. 
SPIRE 0.11.3 should be API-identical to SPIRE 0.11.0.
Links to security advisories:
https://github.com/spiffe/spire/security/advisories/GHSA-q7gm-mjrg-44h9
https://github.com/spiffe/spire/security/advisories/GHSA-h746-rm5q-8mgq
Signed-off-by: Daniel Feldman <daniel@scytale.io>

Update SPIRE to version 0.11.3

---

scripts/helm-nsm-install.sh

This change fixes issue #2245 . It updates the helm-nsm-install script to create the NSM_NAMESPACE if it does not already exist. Helm no longer will create namespaces if they don't exist, and so this is required so that the install that happens later in the script does not fail.
See issue #2245 . This fixes an error that can be encountered when running `make helm-install-nsm`
Tested locally by deleting the `nsm-system` namespace, then by running `make helm-install-nsm`
Unless there are docs I didn't see for this script, I think this is fine?

Fix #2245 Create NSM_NAMESPACE if missing on helm-install-nsm

---

docs/guide-aws.md

The document title said to register inside GCP while we are in the AWS guide.
The document is about AWS and GCP is mentioned at its place.
It solves incoherence between title and real context
- [ X ] Have not tested
Test not really necessary. It is a small change in the documentation. All tests should pass as before.
- [ X ] Bug fix (non-breaking change which fixes an issue)
- [ X ] My change requires a change to the documentation.
- [ X ] I have updated the documentation accordingly.

Modified title to show AWS instead of GCP
